### ISSUE TITLE
add ssl support to connect to mqtt broker

### ISSUE THREAD

**Issue by superyarik** [1technophile/OpenMQTTGateway#101]
now it can only connect via not secure port, so connection is not secure.

**Comment by superyarik** [comment]
no, i'm using 0.3.1, and can not connect to ssl port of broker. maybe problem in pubsubclient, maybe there is some settings need to be setted additionally.

**Comment by 1technophile** [comment]
Coudl you give more inputs, what are the settings you set  ?

**Comment by superyarik** [comment]
I use cloudmqtt
https://www.cloudmqtt.com/docs.html

Port 13378 work perfect, but ssl port is notwork, client not connect.

**Comment by 1technophile** [comment]
ssl seems not supported by pubsubclient:
https://github.com/knolleary/pubsubclient/pull/251

**Comment by superyarik** [comment]
yep, another clients(mqtt dashboards for android) work well.

look like this is another part of joke that "S" in "IoT" is Security :)

**Comment by 8666** [comment]
I think that SSL is possible on ESP but not on the Arduino (there are libraries). Arduino UNO does not have memory for whole SSL magic (https://github.com/256dpi/arduino-mqtt)

**Comment by 1technophile** [comment]
thanks for the link

**Comment by Legion2** [comment]
For TLS we need a the current time as unix epoch, this could be hardcoded which is bad and will require to update the sketch from time to time. The better solution is to use the NTP protocol and let the esp request the time from a time server.

**Comment by Legion2** [comment]
I found this library https://github.com/arduino-libraries/NTPClient which can be used.

**Comment by Legion2** [comment]
I now have TLS working on ESP8266 with server certificate, but it does not work with the root ca certificate.

@1technophile thanks for sponsoring me 👍

**Comment by 1technophile** [comment]
> I now have TLS working on ESP8266 with server certificate

Good news! It's already a good step

> @1technophile thanks for sponsoring me 👍

With pleasure, you have made very good contributions to this project

**Comment by Legion2** [comment]
Ok it now also works on ESP32 but there only the root ca certificate works and not the server certificate. I will create a PR in the next days.

**Comment by Legion2** [comment]
The NTP library is not needed, ESP8266 and ESP32 have them build in and also the CA certificate works now (I don't know why, I did not change anything). Here is the PR #699
