### ISSUE TITLE
Esp32

### ISSUE THREAD

**Issue by danielpondruff** [1technophile/OpenMQTTGateway#103]
Hi,

Is esp32 supported so that the use of a hm10 becomes obsolete?

**Comment by 1technophile** [comment]
Hi,

I didn t tested yet esp32 mainly because it is not enough mature in my point of view : 
https://github.com/sui77/rc-switch/issues/133
https://github.com/espressif/arduino-esp32/issues/383

**Comment by 1technophile** [comment]
I close this question, if you have others don't hesitate to ask with the gitter chat on readme page

**Comment by 1technophile** [comment]
ESP32 IDE is now enough mature to begin the work

**Comment by 1technophile** [comment]
see https://github.com/1technophile/OpenMQTTGateway/pull/145
