### ISSUE TITLE
Support for Rainpoint Bluetooth Soil Moisture sensor

### ISSUE THREAD

**Issue by garudaonekh** [1technophile/OpenMQTTGateway#1034]
I want to integrate this sensor.

https://rainpointus.com/products/%E3%80%90tcs005arf%E3%80%91bluetooth-soil-moisture-sensor-105

Can you give me hint on how to integrate new BLE? BLE is new to me. I cannot get its specs. I saw it using bLE scanner.

**Comment by 1technophile** [comment]
You need to check what data the sensor advertize with a mobile app like nRf Connect. Note that the sensor should be disconnected so as to be visible.
Write down or screenshot the hexadecimal values seen into nRF connect. Check supposed values and try to find correlation between them. You can post here the screenshots of several scan and the expected moisture measurement.
Also you can contact the manufacturer, if they are willing to collaborate for this integration I will provide a contact to them. This would be the easiest way.

**Comment by 1technophile** [comment]
Were you able to go further on this? I'm interested in this sensor as an alternative to Mi Flora.

**Comment by garudaonekh** [comment]
I try it but too many devices popup in nrfConnect and no clear pattern yet, maybe because too many devices nearby. i will try to find a place without any interference and try again

**Comment by garudaonekh** [comment]
Yes, it is a good alternative. It is outdoor and cheaper price. I bought the sensor alone at 11$. But it has only moisture sensor.

**Comment by 1technophile** [comment]
Hi @garudaonekh,

Any progress on this?

You may also put OMG on an ESP32 and set to true these macros:
`pubBLEManufacturerData`
`pubBLEServiceUUID`

It would be easier to analyze the data on [MQTT explorer](http://mqtt-explorer.com/)

**Comment by garudaonekh** [comment]
Sorry i am busy recently. will do it next week. I tried ot once but cannot find any specific pattern maybe due to too many Bluetooth devices nearby so no idea which one is which one. I used NRfconnect as you suggested

**Comment by 1technophile** [comment]
This sensor doesn't seem to have a Bluetooth component but rather rely on a gateway to convert its RF signals into Bluetooth

**Comment by garudaonekh** [comment]
I think so. So it work like most weather station which use RF chip. Do you have more detail about its RF chip and its spec?

**Comment by NorthernMan54** [comment]
Did a bit of googling and rtl_433 has a decoder for this device https://github.com/merbanan/rtl_433/blob/master/src/devices/rainpoint.c

But it uses Manchester encoding which isn't supported by rtl_433_ESP https://github.com/merbanan/rtl_433/blob/9e6c8476748dabd274737d214fb6ce0d9b4c3f35/src/devices/rainpoint.c#L141

**Comment by garudaonekh** [comment]
> Did a bit of googling and rtl_433 has a decoder for this device https://github.com/merbanan/rtl_433/blob/master/src/devices/rainpoint.c
> 
> But it uses Manchester encoding which isn't supported by rtl_433_ESP https://github.com/merbanan/rtl_433/blob/9e6c8476748dabd274737d214fb6ce0d9b4c3f35/src/devices/rainpoint.c#L141

@NorthernMan54 Thanks for your info.
This RTL_433 is a stranger to me. However, I intent to use this sensor for my irrigation project. I have two questions:
1. Which chip is compatible for this?
2. What is the estimated distance it can communicate on open field.

Thanks;

**Comment by NorthernMan54** [comment]
rtl_433 is another open source radio signal decoder package, and is quite popular in the community for receiving signals from temperature, weather and other RF sensor devices.  Full details are here - https://github.com/merbanan/rtl_433/blob/master/README.md

`Which chip is compatible for this?`

Devices like this are compatible https://www.amazon.ca/NooElec-NESDR-Mini-Compatible-ESD-Safe/dp/B00PAGS0HO/ref=sr_1_12?gclid=CjwKCAiAiKuOBhBQEiwAId_sK2roOBHuLy3JdbKccdUn6gC7Ut5KSSnKXXfAXWN1RU4XPM9XxoAlWhoCOZcQAvD_BwE&hvadid=538535012620&hvdev=c&hvlocphy=9000891&hvnetw=g&hvqmt=e&hvrand=13674738682221435229&hvtargid=kwd-350903603168&hydadcr=14279_10126889&keywords=usb+rtlsdr&qid=1640748091&sr=8-12

`What is the estimated distance it can communicate on open field ?`

This really depends on a lot of factors but the range of these is not that far, typically around 50 feet.  You would need to get one and see what works for you.

**Comment by garudaonekh** [comment]
> rtl_433 is another open source radio signal decoder package, and is quite popular in the community for receiving signals from temperature, weather and other RF sensor devices. Full details are here - https://github.com/merbanan/rtl_433/blob/master/README.md
> 
> `Which chip is compatible for this?`
> 
> Devices like this are compatible https://www.amazon.ca/NooElec-NESDR-Mini-Compatible-ESD-Safe/dp/B00PAGS0HO/ref=sr_1_12?gclid=CjwKCAiAiKuOBhBQEiwAId_sK2roOBHuLy3JdbKccdUn6gC7Ut5KSSnKXXfAXWN1RU4XPM9XxoAlWhoCOZcQAvD_BwE&hvadid=538535012620&hvdev=c&hvlocphy=9000891&hvnetw=g&hvqmt=e&hvrand=13674738682221435229&hvtargid=kwd-350903603168&hydadcr=14279_10126889&keywords=usb+rtlsdr&qid=1640748091&sr=8-12
> 
> `What is the estimated distance it can communicate on open field ?`
> 
> This really depends on a lot of factors but the range of these is not that far, typically around 50 feet. You would need to get one and see what works for you.

Based on their poster, they said it's 80meters. Do you think this distance is realistic? 80meters is what I want because it's suitable for most greenhouse size in my country.

<img width="720" alt="Screen Shot 2021-12-29 at 10 41 31 AM" src="https://user-images.githubusercontent.com/2074857/147625383-0fc32d8a-775e-4ab4-95ee-8d0ff8b8cf0d.png">

**Comment by NorthernMan54** [comment]
My distance numbers are based on my experience with Accurite and LaCrosse temperature and weather sensors, and with those I get those distances.  Hence the YMMV comment

One other thought, with the rtl_sdr dongle, you could drop a raspberry with the dongle installed into the middle of the green house, and back haul the signal over ethernet or wifi back to your main building.

**Comment by garudaonekh** [comment]
Do we need to use RTL_SDR to receive the message? Can't we use normal RF receiver?
RTL_SDR is very costly around 20 to 40$ based on my recent price check.

**Comment by NorthernMan54** [comment]
Based on my review of OMG, the pilight and rtl_433_ESP RF signal decoder's don't have support for this device ( based on grepping for 'rainpoint' in the the device decoders ).  But a quick check of rtl_433 shows that support was added in the the fall.  So if you want to start receiving signals now, you will need to use a rtl_sdr and rtl_433 on a RPI.

**Comment by garudaonekh** [comment]
> Based on my review of OMG, the pilight and rtl_433_ESP RF signal decoder's don't have support for this device ( based on grepping for 'rainpoint' in the the device decoders ). But a quick check of rtl_433 shows that support was added in the the fall. So if you want to start receiving signals now, you will need to use a rtl_sdr and rtl_433 on a RPI.
--
`"So if you want to start receiving signals now, you will need to use a rtl_sdr and rtl_433 on a RPI."`
You are referring to the library or the hardware?

**Comment by NorthernMan54** [comment]
That is the library and not hardware

**Comment by garudaonekh** [comment]
ok, so based on rtl_433_ESP, we can use CC1101 transceiver to decode the data from this RainPoint, when the library is updated for it?

**Comment by garudaonekh** [comment]
@NorthernMan54 I got my RainPoint soil moisture sensor working with my RTL_SDR today.
Anyhow, I need to make it works with rtl_433_ESP for my ESP32 project. Can you give me some suggestion on how to integrate this RapointPoint decoder into your rtl_433_ESP?

Thanks;

**Comment by NorthernMan54** [comment]
With a bit of fiddling with platformio you should be able use a cloned copy of rtl_433_esp

then put the additional device decoder in the contrib directory and run the script in the tools directory called update_rtl_433_devices.sh

it will update all the various files except 1 to include the additional device decoder.  You need to update src/rtl_433_ESP.cpp with rtl_433_ESP.fragment".  You can ignore most of the rest of the comments, they are just reminders for me to manually update the various rtl_433 files in case of changes.

that will add it to the code base, build and upload it to your device, and be prepared for it to crash the first time it receives a signal.  Likely stack exhausted or something.  You will the need to work thru the decoder code to find the issue and resolve.

I had not included any devices that i did not support ask modulation or had a code pattern likely to cause an issue, and this one did. My rule of thumb was no code changes to the device decoders, to minimize maintaining the cloned device decoders.  As I didn’t have one, their was no urgency to port it

**Comment by garudaonekh** [comment]
thanks for your detail explanation. I will try
