### ISSUE TITLE
RFtoMQTT sometimes receive invalid value (5471).

### ISSUE THREAD

**Issue by danielpondruff** [1technophile/OpenMQTTGateway#105]
Sometimes when I send a command with my remote control, the gateway does not receive what I expect.
Instead, the code "5471" is received. 

I don't suppose this is a reception problem. 
Anybody else have the problem?

Hardware:
XD RF 5V 
FS1000A
Burning stool 433 mhz Remote Control.

**Comment by 1technophile** [comment]
Hello,

Could you try with receive example from RCSwitch library and see if you reproduce?

**Comment by 1technophile** [comment]
@danielpondruff did you try with basic rcswitch examples ?

**Comment by 1technophile** [comment]
Please reopen the issue if needed
