### ISSUE TITLE
Lora settings in captive portal

### ISSUE THREAD

**Issue by derekmurawsky** [1technophile/OpenMQTTGateway#1056]
**Is your feature request related to a problem? Please describe.**
LoRa requires the band and syncword to be properly set for devices to talk to each other. Right now, the only way to change these settings is to recompile the project. This adds to the confusion/complexity when you consider that bin files are released for Target systems.

**Describe the solution you'd like**
I would like the LoRa settings to be configurable via the captive web portal. The existing defines can be used to establish defaults to ensure backwards compatibility.

**Describe alternatives you've considered**
Recompiling - not user friendly. I'm having trouble with getting my board to work connecting to MQTT with a compile while the bin works perfectly. But the bin doesn't have the proper band or syncword, so it's useless for me. I will get this working eventually, but noticed the issue and wanted to log a suggestion.

**Additional context**
I'm willing to try to build this feature if there is interest, though I'm very new to c/c++.

**Comment by 1technophile** [comment]
Good point, this makes even more sense now that the upload process can be done through the web
