### ISSUE TITLE
Webpage BLE Gateway

### ISSUE THREAD

**Issue by wst-tdb** [1technophile/OpenMQTTGateway#1066]
https://docs.openmqttgateway.com/setitup/ble.html

not so much a bug as it is misleading documentation.  The pictures show the correct connections, but the table 
![image](https://user-images.githubusercontent.com/63517776/130383509-59287e67-15c0-4a98-b4eb-eafce57582cf.png)

while meaning to show connections that match the pictures, give the appearance of reversing the connections by saying D6 to HM10 TX/ D7 to HM10 RX.

**Comment by 1technophile** [comment]
Thanks for pointing that. If you are interested in, feel free to [submit a PR ](https://github.com/1technophile/OpenMQTTGateway/edit/development/docs/setitup/ble.md)
