### ISSUE TITLE
Values swapped for ds1820 sensor

### ISSUE THREAD

**Issue by amatamalas** [1technophile/OpenMQTTGateway#1072]
Hi all,

I have spotted a bug/typo for the DS1820 sensor in the development branch. The values for tempf and tempc are currently swapped. I'm happy to submit a PR as it's a trivial change in code and be able to provide my small grain of sand to this amazing project.

I have been looking into the code history and seems that it was introduced on #703 and carried on during some refactoring of the code.

Kind regards,
Antoni

**Comment by 1technophile** [comment]
Hi,

Feel free to submit a PR!
