### ISSUE TITLE
Support for new Mi soil sensor MAX version

### ISSUE THREAD

**Issue by garudaonekh** [1technophile/OpenMQTTGateway#1073]
hi,
please add support for new outdoor version of Mi Flora soil sensors. 
https://a.aliexpress.com/_mL15QNt[MAX version](https://a.aliexpress.com/_mL15QNt) 

I got one. and here is its NRF Connect specs

0x020106030295FE141695FE712098006734786C8D7CC40D09100200000C09466C6F7765722063617265

**Comment by garudaonekh** [comment]
![Screenshot_20210908-195915](https://user-images.githubusercontent.com/2074857/132513764-21ac5473-ac28-491e-9c74-db844e022207.jpg)
![-10984284881772230041](https://user-images.githubusercontent.com/2074857/132513862-04823567-7371-41ac-b6cb-7f6cba666f04.jpg)

**Comment by 1technophile** [comment]
Checking the service data on the screenshot format it should be compatible with the all the OMG versions that support Mi Flora, did you try already?

**Comment by 1technophile** [comment]
Already compatible

**Comment by garudaonekh** [comment]
@1technophile Sorry, I was confused with another Mi Flora. Actually, it has some change in compared with the Mi Flora.
Please take a look at this: https://github.com/custom-components/ble_monitor/issues/43
