### ISSUE TITLE
Sensor for esp32's touchpad pins (PR proposal)

### ISSUE THREAD

**Issue by flo-x** [1technophile/OpenMQTTGateway#1074]
Dear all,

I implemented an OMG sensor for esp32's capacitive touch sensing (ZsensorTouch). It generates "button pressed" and "button released" mqtt messages for touch-enabled gpios of esp32. It can handle up to 10 touch buttons, features a kind of self-calibration and filtering for glitches. Works well for me, hope it will be useful for others.

Would this be an interesting addition to OMG ? If so, let me know, I'll make a PR for it.

**Comment by 1technophile** [comment]
Hi,

That's nice, 
yes feel free to add a PR, you may have to do some maintenance on it if required or have questions from users.
