### ISSUE TITLE
new BLE Soil Moisture Sensor

### ISSUE THREAD

**Issue by garudaonekh** [1technophile/OpenMQTTGateway#1076]
Hi,
How to add support for this soil sensor? It's very good quality and it include EC, Moisture, Light and Temperature.

![2021-09-13 16 48 05](https://user-images.githubusercontent.com/2074857/133062968-c4f907ad-3058-4cd6-9b6b-3d346bd79bab.jpg)
![2021-09-13 16 47 54](https://user-images.githubusercontent.com/2074857/133062988-7d776e43-8f5e-4523-ac7e-d171f7017813.jpg)

Here's its raw data from NrfConnect:

0x02010503198001050212180F1807FF453B9D38C1A40B0941692D5468696E6B6572

Thanks;

**Comment by 1technophile** [comment]
Hi,

You need to add also the values seen on the app along as the raw data.
Ec= ? 
Temperature= ? 
Moisture= ? 
Lux= ? 
Screenshots showing raw data or detailled data (manufacturer data, service data, service data uuid )

At leat for 3 set of values.

**Comment by 1technophile** [comment]
Do you have a link to this sensor by the way?

**Comment by garudaonekh** [comment]
Its app is in Chinese. I cannot figure out how to use it yet.

**Comment by garudaonekh** [comment]
![IMG_20210913_165144__01](https://user-images.githubusercontent.com/2074857/133185115-0f4debdb-89a1-470b-95bb-c119168ef3b2.jpg)
now I have these three.
Biggest one is Mi Max version, medium one is the one I mentioned here. smallest one is Mi Flower care

**Comment by garudaonekh** [comment]
Biggest one is Mi Max version, medium one is the one I mentioned here. smallest one is Mi Flower care

**Comment by garudaonekh** [comment]
![photo_2021-09-14 10 32 05](https://user-images.githubusercontent.com/2074857/133191057-a2c28e6e-6127-44bb-bc77-15ed0715bffb.jpeg)
![photo_2021-09-14 10 32 25](https://user-images.githubusercontent.com/2074857/133191066-2b697171-2337-4d89-82e4-22e586e21330.jpeg)
Here're the two test cases.From its app and NrfConnect

**Comment by 1technophile** [comment]
> Here're the two test cases.From its app and NrfConnect

I see on the app that the values are changing but unfortunately the value seen on NRFconnect are constant, Raw data and Details are the same between the 2 screenshots.
Could you verify if the Raw data and Details are changing between several measurements?

**Comment by h2zero** [comment]
Breaking down the raw data you have:
`02 01 05` = Advertising flags, (BLE_HS_ADV_F_DISC_LTD | BLE_HS_ADV_F_BREDR_UNSUP) which is interesting, it's using rapid advertising here, good way to burn up batteries.

`03 19 8001` = Appearance is type 0x0180, Generic Remote Control

`05 02 12180F18` = Incomplete service uuids, 16bit, 0x1812, 0x181F.

`07 FF 453B9D38C1A4` = Manufacturer data, this is where you'll find the values you're looking for.

`0B 09 41692D5468696E6B6572` = Device name, "Ai-Thinker"

**Comment by 1technophile** [comment]
> Biggest one is Mi Max version, medium one is the one I mentioned here. smallest one is Mi Flower care

Do you have a link to the one at the middle (shopping link), I tried HJPSWLO2 but no chance

**Comment by garudaonekh** [comment]
@1technophile When I click on "Recheck" in the app, NRFConnect ask me "Do you want to debug the connection" thus it looks like the device needs wait for connection from app. And when I click on debug, i saw these value change in "Clinet" section of NRFConnect
![photo_2021-09-15 10 25 27](https://user-images.githubusercontent.com/2074857/133366119-f47e38c6-1a0d-4834-a68b-f1843369ee30.jpeg)
![photo_2021-09-15 10 28 12](https://user-images.githubusercontent.com/2074857/133366126-ae67fb93-c723-4d95-ba4b-bf25d82f86fe.jpeg)

**Comment by garudaonekh** [comment]
> > Biggest one is Mi Max version, medium one is the one I mentioned here. smallest one is Mi Flower care
> 
> Do you have a link to the one at the middle (shopping link), I tried HJPSWLO2 but no chance

It's not available on AliExpress yet. Its price is 10$. Waterproof rating is IP65.

**Comment by 1technophile** [comment]
@garudaonekh 
> When I click on "Recheck" in the app, NRFConnect ask me "Do you want to debug the connection" thus it looks like the device needs wait for connection from app. And when I click on debug, i saw these value change in "Clinet" section of NRFConnect

This page is the result of the device connection. As a first attempt we can look of the broadcasted data (easier)

THe issue that I have with the 2 screenshots given is that they have the same raw values, if you take a second look to you see these raw value changing depending on the temperature or other sensor values?

**Comment by garudaonekh** [comment]
Checked with the manufacturer. The data is encrypted and need to be decrypted from their cloud server and send back to app.

**Comment by h2zero** [comment]
>The data is encrypted and need to be decrypted from their cloud server and send back to app.

That's insane, another app for someone to monitor users telemetry data, using encryption to force the app use? Sorry, that irks me, makes me want to hack it just to spite them lol. Do you have a link to order these?

**Comment by garudaonekh** [comment]
> > The data is encrypted and need to be decrypted from their cloud server and send back to app.
> 
> That's insane, another app for someone to monitor users telemetry data, using encryption to force the app use? Sorry, that irks me, makes me want to hack it just to spite them lol. Do you have a link to order these?

It's sold on Taobao.com only. You can buy it only if you have shipping agent in China(they only ship within China).
