### ISSUE TITLE
A6/A7 is obsolete. TTGo T-Call  is an alternative

### ISSUE THREAD

**Issue by garudaonekh** [1technophile/OpenMQTTGateway#1089]
** My Use case is to connect my board thru GPRS(2G) to my cloud-based MQTT server(without Wifi)**

I checked with Ai-Thinker, they said A6/A7 is out of production and they only produce A9/A9G for now. As for A9/A9G, it's not Arduino compatible thus it'll not work with OMG at least for now. Thus, a good alternative is T-Call by TTGO which I have tested for several months and they are very stable in compared with other Sim800L/800C which I have used, I think due to power issue of Sim800L.

I want to use OMG with this T-Call GPRS module(without Wifi), and I see that OMG use this Zgateway2G for 2G. 
I have two questions:
1-Can OMG work directly with 2G without the need to have wifi to connect to first(as I don't have A6/A7 to test)?
2-Since T-Call is based on TinyGSM, so I need to use customize this Zgateway2G to TinyGSM?

Or is there any suggestion?

Ref: https://docs.openmqttgateway.com/use/gsm.html#receiving-sms-from-2g

Thanks;

**Comment by Odyno** [comment]
I don't have any answers for you, but just a question to understand better... I am also interested in switching to GPRS, could you tell me (or link) which board you want to use and which one is deprecated?

**Comment by garudaonekh** [comment]
AI Thinker stop producting A6/A7. Personnally, I am quite satisfied with T-Call's stability: https://grobotronics.com/ttgo-t-call-esp32-with-sim800l-gprs-module.html?sl=en. Its original price is 10$ but now increased to 15$ due to chip shortage.

Besides, I also use A9 GPRS which is very good and cheap. It's 5$
