### ISSUE TITLE
Please add PC-60FW Fingertip Oximeter 

### ISSUE THREAD

**Issue by yeuking** [1technophile/OpenMQTTGateway#1095]
![WhatsApp Image 2021-11-03 at 5 00 22 PM](https://user-images.githubusercontent.com/3224525/140033868-593da50c-199d-4d75-940a-c0cb3c21e5ca.jpeg)

**Is your feature request related to a problem? Please describe.**
No, this is new device.

**Describe the solution you'd like**
Just add support read info for battery, Sp02, PR and wave.

**Describe alternatives you've considered**
None.

**Comment by 1technophile** [comment]
Do you see manufacturer data like below if you wait:
![image](https://user-images.githubusercontent.com/12672732/140050039-0aae1c01-5b75-4bfb-bbed-2804f04de6fc.png)

**Comment by 1technophile** [comment]
Some usefull resources:
https://github.com/pythag/pc-60fw

**Comment by yeuking** [comment]
> 
> 
> Do you see manufacturer data like below if you wait: ![image](https://user-images.githubusercontent.com/12672732/140050039-0aae1c01-5b75-4bfb-bbed-2804f04de6fc.png)

Sorry, can't see manufacturer data like above.

**Comment by yeuking** [comment]
> 
> 
> Some usefull resources: https://github.com/pythag/pc-60fw

Thanks, I found another usefull resources as below (more detail for this device) :
https://anaesthetics.app/blog/posts/2020/bluetooth/
