### ISSUE TITLE
Please add Unbrand Smart Scale

### ISSUE THREAD

**Issue by yeuking** [1technophile/OpenMQTTGateway#1097]
![image](https://user-images.githubusercontent.com/3224525/140236799-bdc483e0-8a31-4975-a93a-1aabbffce18b.png)
![image](https://user-images.githubusercontent.com/3224525/140236816-2fda0806-86c3-4009-bc35-1591b0600175.png)

Is your feature request related to a problem? Please describe.
No, this is new device.

Describe the solution you'd like
Just add support read info for battery, weight and other if possible like below:-
![image](https://user-images.githubusercontent.com/3224525/140237718-d175f324-5b97-42cf-92b6-4317420fccf9.png)

Describe alternatives you've considered
None.

**Comment by 1technophile** [comment]
Could you take another screenshot of nrfConnect please with some weight on it, along with the corresponding weight (different from the one displayed above)?
This would enable to confirm the parsing.

I need also the battery value that you see in the app

**Comment by yeuking** [comment]
![Screenshot_20211106_153027](https://user-images.githubusercontent.com/3224525/140601775-dbf562c0-cadf-41a3-a934-7784a7327f2a.jpg)
`is it correct?`

**Comment by yeuking** [comment]
![Screenshot_20211106_153329](https://user-images.githubusercontent.com/3224525/140601842-da1574c0-f3df-4fe0-b255-9358c269eb7c.jpg)
Hope above 2 picture can help you.

**Comment by 1technophile** [comment]
@yeuking what is the corresponding weight and battery level when you capture these data?

**Comment by yeuking** [comment]
Some Weight data capture...
0x10FFC0711F4A13880000250000000000000609596F646130


0x10FFC07406CC13880000250000000000000609596F646130


0x10FFC0770A7813880000250000000000000609596F646130


0x10FFC07B0E1013880000250000000000000609596F646130

**Comment by 1technophile** [comment]
Could you give the corresponding weight in kg please @yeuking

**Comment by 1technophile** [comment]
@yeuking could you add the value seen in the app along with each data capture please?
