### ISSUE TITLE
Missing discovery message for BT devices

### ISSUE THREAD

**Issue by Odyno** [1technophile/OpenMQTTGateway#1102]
**Short Description**
With the current develop no discovery messages are sent for BT devices

**My configuration is:**
```
platformio]
default_envs = az-delivery

[env:az-delivery]
lib_ldf_mode =  deep+
platform = espressif32
board = az-delivery-devkit-v4
check_tool = cppcheck, clangtidy
check_flags =
  cppcheck: -v
  clangtidy: -fix-errors -format-style=mozilla
#check_patterns = main/
#check_severity = medium, high



lib_deps =
  ${env:esp32dev-all-test.lib_deps}
build_flags =
  ${com-esp.build_flags}
  '-DZgatewayBT="BT"'
  '-DZgatewayRF="RF"'
  '-DLED_RECEIVE=2'
  '-DLED_RECEIVE_ON=0'
  '-DpubUnknownBLEServiceData=false'
  '-DsimpleReceiving=true'
  '-DZmqttDiscovery="HADiscovery"'
  '-DGateway_Name="OMG_BTRF_3"'
  '-DESPWifiManualSetup=true'
  '-Dwifi_ssid="xxx"'
  '-Dwifi_password="xxx"'
  '-DMQTT_PORT="xxxx"'
  '-DMQTT_USER="xxx"'
  '-DMQTT_PASS="xxx"'
  '-DMQTT_SERVER="xxx"'
  '-DOMG_VERSION="0.9.9-1"'
  '-DLOG_LEVEL=LOG_LEVEL_VERBOSE'  ; Enable trace level logging
  '-DvalueAsASubject=true'
```

**More info**
After a code analysis, I traced back to this point and found that this variable is always = 0.

https://github.com/1technophile/OpenMQTTGateway/blob/dcbce352be38697cf66553a37b7b2a8866637aab/main/ZgatewayBT.ino#L1045

and finally I did not understand how this variable is incremented.

**Comment by 1technophile** [comment]
You are right I will submit a pr.

**Comment by 1technophile** [comment]
This is linked with the integration of [TheengsDecoder ](https://github.com/theengs/decoder), we are adding a way to retrieve the properties of a device for discovery from TheengsDecoder so that it will reduce significantly the discovery code into OMG.

**Comment by 1technophile** [comment]
PR done
