### ISSUE TITLE
Error in Documentatio

### ISSUE THREAD

**Issue by Gemikro1** [1technophile/OpenMQTTGateway#1125]
There is an error in the section "Advanced configuration of the gateway / Configure secure connection in the gateway" :
`#define MQTT_DEFAULT_SECURE`  must be   `#define MQTT_SECURE_DEFAULT` instead.

**Comment by 1technophile** [comment]
THanks for pointing this, feel free to submit a PR through [the edit option](https://github.com/1technophile/OpenMQTTGateway/edit/development/docs/upload/advanced-configuration.md) if you want
