### ISSUE TITLE
tempc not signed

### ISSUE THREAD

**Issue by tablatronix** [1technophile/OpenMQTTGateway#1138]
Latest, my Mi sensors do not report -C temps properly.

`BLEdata["tempc"] = (float)((pData[0] | (pData[1] << 8)) * 0.01);`

**Comment by tablatronix** [comment]
"tempc":648.16 ?
{"id":"A4:C1:38:xx:xx:xx","name":"ATC_xxxxxx","rssi":-83,"model":"LYWSD03MMC_PVVX","tempc":648.16,"tempf":1198.688,"hum":74.52,"batt":45,"volt":2.613}

**Comment by 1technophile** [comment]
This should be corrected in v0.9.9beta, are you using a previous version?

**Comment by tablatronix** [comment]
I should be using staging.. how do I check ?

`N: OpenMQTTGateway Version: version_tag`

**Comment by 1technophile** [comment]
When did you took this branch?

By the way a simple test is to do a web upload of the v0.9.9beta:
https://docs.openmqttgateway.com/upload/web-install.html
Take `esp32-dev-ble-cont`

**Comment by tablatronix** [comment]
Yesterday..

9a4db88cb251bd4ec21ccda6acfe2890de8983c9

**Comment by 1technophile** [comment]
Hmm, could you set [this ](https://github.com/1technophile/OpenMQTTGateway/blob/8b40b680811753c6cd80097657e9e82dda6aa33c/main/config_BT.h#L108) to true and share the servicedata here please

**Comment by tablatronix** [comment]
Of the sensor? Let me put it in the fridge

**Comment by 1technophile** [comment]
Yes please

**Comment by 1technophile** [comment]
Are you using platformio or arduino ide?

With arduino ide you may have to update to the[ latest version ](https://github.com/theengs/decoder/releases)of Theengs Decoder.
There is a correction for signed value in it.

**Comment by tablatronix** [comment]
Its fixed, I must have used an older bin when my ide was having issues, I was looking at historical data.
Sorry about that

: getDeviceByMac A4:C1:38:3F:8B:D4
T: update A4:C1:38:3F:8B:D4
T: Removing servicedatauuid
N: Send on /BTtoMQTT msg {"id":"A4:C1:38:3F:8B:D4","name":"ATC_3F8BD4","rssi":-39,"servicedata":"a4c1383f8bd4ffd55a2709f7af","brand":"Xiaomi","model":"LYWSD03MMC","model_id":"LYWSD03MMC_ATC","tempc":-4.3,"tempf":24.26,"hum":90,"batt":39,"volt":2.551}
T: jsonPubl - ON
T: [ OMG->MQTT ] topic: ble/OpenMQTTGateway_ESP32_BLE/BTtoMQTT msg: {"id":"A4:C1:38:3F:8B:D4","name":"ATC_3F8BD4","rssi":-39,"servicedata":"a4c1383f8bd4ffd55a2709f7af","brand":"Xiaomi","model":"LYWSD03MMC","model_id":"LYWSD03MMC_ATC","tempc":-4.3,"tempf":24.26,"hum":90,"batt":39,"volt":2.551} 
T: Creating BLE buffer
N: Device detected: 06:7D:D4:9E:35:D0
T: getDeviceByMac 06:7D:D4:9E:35:D0
T: Get services data number: 1
T: Converted service data (27) to 53fd2802c0aaaba1c0654806b7462ee675277edb58c4a81735e77f
T: Service data: 53fd2802c0aaaba1c0654806b7462ee675277edb58c4a81735e77f
T: Service data UUID: 0xfef1

**Comment by 1technophile** [comment]
Thanks, i will use these data to enrich the device decoding unit testing
