### ISSUE TITLE
Ibeacons with random MAC addresses

### ISSUE THREAD

**Issue by scribblrsam** [1technophile/OpenMQTTGateway#1139]
**Is your feature request related to a problem? Please describe.**

I would like to use the home assistant companion app to publish beacons over ble, collect these and track presence of people in the house like this. As far as I can see this is not currently possible as modern phones randomise the Bluetooth MAC address used and presence events are published with the mac as the device ID.

**Describe the solution you'd like**

Publish ibeacon presence events to HA/MQTT using the beacon uuid not the MAC or perhaps both to allow either event to be tracked. I am happy to look at this, would you consider a PR for this?

**Describe alternatives you've considered**

Carry a hardware ibeacon, clearly less practical and I don't always have the same set of keys!

I have also considered using esphome as this has functionally to track beacons by uuid, I would rather use OMG as I use this for other sensors. 

**Additional context**

**Comment by 1technophile** [comment]
>Publish ibeacon presence events to HA/MQTT using the beacon uuid not the MAC or perhaps both to allow either event to be tracked. I am happy to look at this, would you consider a PR for this?

You should [get the UUID](https://github.com/theengs/decoder/blob/3abed86931ffec8890ced8a3b12a05a55f92bd05/src/devices/iBeacon_json.h#L13) already with an ibeacon

With the v0.9.9 beta

Which version are you using?

**Comment by scribblrsam** [comment]
> Publish ibeacon presence events to HA/MQTT using the beacon uuid not the MAC or perhaps both to allow either event to be tracked. I am happy to look at this, would you consider a PR for this?

Sorry this was meant to say: 
Publish ibeacon presence events to HA/MQTT using the beacon uuid **as the device ID and** not the MAC or perhaps both to allow either event to be tracked. I am happy to look at this, would you consider a PR for this?

The messages are published to the `home/home_presence/<room name>` topics
`{"id":"50:54:99:B4:00:18","rssi":-82,"distance":11.4949,"brand":"GENERIC","model":"IBEACON","model_id":"IBEACON","mfid":"4c00","uuid":"e1e4448b54ea4a7eafc833522f901b6c","major":100,"minor":1,"power":-59}`

The mac addresses used for the ID are ever changing and therefore cannot be used to track a device according to [the HA docs for MQTT room presence](https://www.home-assistant.io/integrations/mqtt_room/). Using the uuid as the ID would allow these beacons to be tracked. 

[ESP Home ](https://esphome.io/components/binary_sensor/ble_presence.html) allows for similar tracking of UUID rather than MAC for this reason however only creates a binary sensor.

**Comment by 1technophile** [comment]
There is a macro that enables to leverage home_presence [here](https://github.com/1technophile/OpenMQTTGateway/blob/8b40b680811753c6cd80097657e9e82dda6aa33c/main/config_BT.h#L82), it enables to publish data in a single topic.
Not sure if it is still corresponding to room presence expectation but feel free to test it.

**Comment by scribblrsam** [comment]
Is that not the macro that publishes the message above to the home_presence topic?

**Comment by 1technophile** [comment]
> Is that not the macro that publishes the message above to the home_presence topic?

Yes

**Comment by scribblrsam** [comment]
Unless I'm missing something it doesn't work for my case in its current state. The mac of the device is published in the Id field. This is used in the home assistant config to track a device.

As beacons are being published from a phone the mac is randomised the beacons cannot be tracked. If the beacon uuid was to be used as the id a beacon from a phone could be tracked.

Although this would also fail to pass whitelist checks...

Can you recommend a solution?

**Comment by h2zero** [comment]
I think this would be doable. A simple macro to set `useBeaconUUIDasID`, then check if it's an iBeacon before publishing and change the ID to the uuid.

**Comment by h2zero** [comment]
@scribblrsam Here is a simple patch for you to try. Let me know if this is sufficient.
[uuid_as_id.txt](https://github.com/1technophile/OpenMQTTGateway/files/7920727/uuid_as_id.txt)

**Comment by ssikgun** [comment]
Hello. I have the same problem. How did you solve it?? The Bluetooth MAC address of my phone also changes randomly. So I want to use the UUID as the device ID.

**Comment by h2zero** [comment]
@ssikgun Try the patch I provided in my post above.

**Comment by scribblrsam** [comment]
@h2zero thanks for the patch. I tried but couldn't get it to work in conjunction with the mac whitelist. 

I did start to look at this further with logging set to trace but didn't get very far as I'm not familiar with the project and haven't had much time to spend on this.

Is there anything you can suggest?

**Comment by h2zero** [comment]
There would need to be much more code alteration for whitelist support unfortunately. Not a 5 minute change like the patch. 

If you want to hack around checkout the processBLEtask function.

**Comment by ssikgun** [comment]
@h2zero sorry. I don't know how to apply the patch. So, I directly modified the code using platformio.
(Fixed ZgatewayBT.ino)
![1](https://user-images.githubusercontent.com/74531048/151636851-9db84e39-c1df-4df4-87e4-a4ddc9b47b3b.jpg)


And set the mqtt-room in ha.

![2](https://user-images.githubusercontent.com/74531048/151636858-02abdf9c-2a22-4ef9-b441-2795c4f48380.jpg)

But it didn't work.
![3](https://user-images.githubusercontent.com/74531048/151636859-437aaee1-e0fb-4222-9d90-342f7b5ac36e.jpg)

What did I do wrong? 

And thanks for the reply.

**Comment by h2zero** [comment]
Did you add `-DuseBeaconUuidAsId` to your env config? Alternatively just remove the `#if` and `#endif` parts of the patch.

**Comment by ssikgun** [comment]
@h2zero Thank you very much. I modified the ZgatewayBT code.
![4](https://user-images.githubusercontent.com/74531048/151639606-27185826-9a17-409d-bfab-02b59bba1477.jpg)


It finally started to work.
![5](https://user-images.githubusercontent.com/74531048/151639607-fb1db83a-7053-4895-ab58-242293b08c97.jpg)


I will share it with people who have the same problem as me on the home assistant community in South Korea.

**Comment by mihsu81** [comment]
Hi @1technophile, Can this be included in the next release?
Looks like a good solution.

**Comment by 1technophile** [comment]
@mihsu81 yes indeed

**Comment by mihsu81** [comment]
Awesome. Having the UID as device id will allow the UID to be included in the whitelist?

**Comment by 1technophile** [comment]
That's a good question, I will need to identify the impacts of doing so.
