### ISSUE TITLE
0.9.9 does not read the data from MHO-C401

### ISSUE THREAD

**Issue by nonflammable** [1technophile/OpenMQTTGateway#1160]
0.9.8 works properly
{"id":"A4:C1:38:B3:CF:C0","name":"MHO_B3CFC0","rssi":-65,"model":"LYWSD03MMC_PVVX","tempc":19.93,"tempf":67.874,"hum":45.51,"batt":35,"volt":2.523}

0.9.9 (beta too) does not read the data (https://github.com/1technophile/OpenMQTTGateway/releases/download/v0.9.9/esp32dev-ble-firmware.bin)
{"id":"A4:C1:38:B3:CF:C0","name":"MHO_B3CFC0","rssi":-65,"servicedata":"c0cfb338c1a4c807c511a6091ead0e"}

MHO firmware:
https://github.com/pvvx/ATC_MiThermometer/blob/master/MHO_C401_v35c.bin

**Comment by 1technophile** [comment]
This is corrected in the development branch

**Comment by 1technophile** [comment]
Corrected in v0.9.10

**Comment by nonflammable** [comment]
Back in v1.2.0
