### ISSUE TITLE
Is it possible to get all the separate manufacturerdata?

### ISSUE THREAD

**Issue by saramlove** [1technophile/OpenMQTTGateway#1163]
**Is your feature request related to a problem? 
I want to get the second manufacturerdata of the Apple device.
Currently only the first of all manufacturerdata can be obtained.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
I can get the info I want in the second manufacturerdata.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
I want to get multiple like servicedata .

**Additional context**

Hello.
OMG collects only the first of several manufacturerdata.
Is it possible to collect all the manufacturerdata?

OMG is the best BLE data analysis solution.
Thank you.
![Screenshot_20220210-144724](https://user-images.githubusercontent.com/84359554/153346953-b0923108-6f00-410c-9f34-738170e2180b.png)

**Comment by h2zero** [comment]
This is interesting, I've not seen a device with multiple manufacturing data definitions before. This will require updating of the NimBLE repo to support correctly and could take some time.

**Comment by saramlove** [comment]
> This is interesting, I've not seen a device with multiple manufacturing data definitions before. This will require updating of the NimBLE repo to support correctly and could take some time.

Thank you very much for your reply.  : )
