### ISSUE TITLE
OpenMQTTGateway dont need RF2 to work with KAKU

### ISSUE THREAD

**Issue by animavitis** [1technophile/OpenMQTTGateway#118]
Hi,

There is simple way to use KAKU (transmit & recive) in OpenMQTTGateway, simply change rc-switch liblaryto this branch:

https://github.com/max-weller/rc-switch/tree/intertechno-receive

Tested with my KAKU switches & NodeMCU

**Comment by 1technophile** [comment]
Hello,

Thanks for the tip!
@dendeze could you test if it is working with your devices?

**Comment by animavitis** [comment]
after more testing i must tell that this version of rc-switch is not stable :/ 
After couple of hours my nodeMCU throws some exceptions & restart itself randomly, but still it can be used to read codes from KAKU remote.

**Comment by 1technophile** [comment]
do you have some inputs about these instabilities?
is the nodemcu that restart or do you have other symptons?

**Comment by animavitis** [comment]
NodeMCU restart itself randomly, usually when i try to use RF transmitter couple of times in short period of time. I will try to debug it

**Comment by animavitis** [comment]
I was testing it and same restart can happens on NewRemoteSwitch & rc-switch#intertechno-receive. 
I dont know how to debug root cause of restarts, so we can close this issue.

thx for help
