### ISSUE TITLE
typo in [env:esp32-wt32-eth01-ble-eth]

### ISSUE THREAD

**Issue by kroman666** [1technophile/OpenMQTTGateway#1181]
https://github.com/1technophile/OpenMQTTGateway/blob/08d8d108d2d7ec4ced0135badb7f54891b8e6100/platformio.ini#L559

Should look like this right?

  '-DETH_CLK_MODE=ETH_CLOCK_GPIO0_IN'

**Comment by 1technophile** [comment]
Yes you are right, feel free to submit a PR if you would like

**Comment by kroman666** [comment]
I did, hopefully correctly as it's my first one.
