### ISSUE TITLE
Light sensor working with OMG?

### ISSUE THREAD

**Issue by tomcat-xx** [1technophile/OpenMQTTGateway#1184]
For now it is not really a feature request, just a question: Does someone know any light (luminance) sensor working with OMG. Best option would be via BLE like Xiaomi temperature sensors. In general there a not much offers, I only found one from Xiaomi with ZigBee but my gateway does not support it.

Maybe I have to re-activate my soldering iron ... ?

**Comment by 1technophile** [comment]
Mi Flora and Qingping CGPR1 advertise luminance through ble.

**Comment by tomcat-xx** [comment]
Thanks for quick answer!

I already thought about buying and misusing a Mi Flora. Have already some but need all for the flowers and under the leaves values are not reliable. 

Qingping CGPR1 is already in the compatibility list. Sorry did not see it (or not realize it can be also used as light sensor).

Both are not easy (or cheap) to get at the moment but will have an eye on offers.

**Comment by NorthernMan54** [comment]
Personally I have several OMG’s deployed with a bh1750 lux sensor wired to the i2c bus on a esp32.
