### ISSUE TITLE
TRACE ZgatewayBT not working

### ISSUE THREAD

**Issue by davcx** [1technophile/OpenMQTTGateway#1185]
Hi,
I enabled TRACE facility (env esp32-m5stack-ble, define ZgatewayBT, , , but I don't see any log.trace about gatewayBT on platformio's monitor

I tried with uncomment global env build_flags = '-DLOG_LEVEL=LOG_LEVEL_TRACE'   , but I don't see any trace log reported from execution of ZgatewayBT.

**Comment by 1technophile** [comment]
here is an example of trace configuration that should work:
```
[env:esp32dev-ble]
platform = ${com.esp32_platform}
board = esp32dev
board_build.partitions = min_spiffs.csv
lib_deps =
  ${com-esp32.lib_deps}
  ${libraries.ble}
  ${libraries.wifimanager32}
  ${libraries.decoder}
build_flags = 
  ${com-esp32.build_flags}
  '-DZgatewayBT="BT"'
  '-DLOG_LEVEL=LOG_LEVEL_TRACE'
  ```
