### ISSUE TITLE
with GPRS/SMS but without WIFI scenario

### ISSUE THREAD

**Issue by garudaonekh** [1technophile/OpenMQTTGateway#1187]
Hi,
I am working on iOT for agriculture thus we don't have Wifi in most case. I normally use TTGO T-Call with SIM800L. 
GPRS is very slow in most rural area but SMS is the most reliable mean of communication.
Thus, I need two approaches:
1- MQTT connection to my MQTT Broker.
2- If GPRS not work, I will rely on SMS->MQTT thru ZGateway2g.ino.
I see that OMG has 2g gateway(Zgateway2g.ino) which will MQTT->SMS,SMS->MQTT which is very useful for my case.

My question is how will OMQ work if it doesn't connect to Wifi, will all the functionality exist?

I have try it without wifi, but nothing seem to works.

Regards;

**Comment by 1technophile** [comment]
Hi,

In the current implementation, OMG relies on Wifi and MQTT, you need to have both of them to be able to process the data.
