### ISSUE TITLE
how to update firmware using OTA

### ISSUE THREAD

**Issue by 0neday** [1technophile/OpenMQTTGateway#1188]
I found esphome use web_server component to update firmware  and show some informations .

so, how to start a web server for OMG

**Comment by 1technophile** [comment]
There are several possibilities:
* Arduino IDE OTA
* Platformio OTA by adding this to your env:
```
upload_protocol = espota
upload_port = 192.168.1.28
upload_flags =
  --auth=OTAPASSWORD
```
* [MQTT OTA](https://docs.openmqttgateway.com/use/gateway.html#switching-brokers-and-using-self-signed-and-client-certificates)

**Comment by 0neday** [comment]
Thank you
