### ISSUE TITLE
Restart causes loss of config/Whitelist not working

### ISSUE THREAD

**Issue by anarchking** [1technophile/OpenMQTTGateway#1189]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**

**To Reproduce**
1. Publish to home/Bedroom_OMG_BLE/commands/MQTTtoBT/config
Payload {"white-list":["xx:xx:xx:xx:xx:xx","xx:xx:xx:xx:xx:xx"]}

Also tryed retain flag
Publishing to the same topic but with payload
{"interval":3000} works fine but doesn't retain either.

3. Subscribe on home/home_presence/Bedroom_OMG_BLE
I updated from OMG 9.8 to 9.11 and cant seem to get it back to the way i had it. 

**Expected behavior**
A clear and concise description of what you expected to happen. When first starting the device after setting up Wi-Fi and mqtt creds, if I switch on ha presence I'm flooded with all kinds of eye beacon and other Bluetooth devices automatically discovered if I try white listing nothing is discovered if I restart the device it loses all config not sure what I'm doing wrong.

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by 1technophile** [comment]
>  if I switch on ha presence I'm flooded with all kinds of eye beacon and other Bluetooth devices automatically discovered if I try white listing nothing is discovered if I restart the device it loses all config not sure what I'm doing wrong.

This is corrected on the development branch, we are filtering out those devices.

Did you try:
` {"white-list":["xx:xx:xx:xx:xx:xx","xx:xx:xx:xx:xx:xx"],"interval":3000}`

**Comment by anarchking** [comment]
Awesome 👍, thanks I figured out my problem was that my HA wasn't following the state of the (publish Hass presence switch), so it looked like it was on but when I clicked the button it fixed the problem. For now setting config on restarts I'm just using an automation to send all config to each device. I didn't even think about adding the payloads together thanks for that tip as well 😁
