### ISSUE TITLE
configuration for domoticz ?

### ISSUE THREAD

**Issue by nikki-reprap** [1technophile/OpenMQTTGateway#119]
Hi please can someone tell me how to configure the mqtt for domoticz 

Thanks Nikki

**Comment by 1technophile** [comment]
I didn t heard about a user having done that, i would be happy to help you if you have questions

**Comment by 1technophile** [comment]
Did you succeeded in integrating with domoticz ?

**Comment by nikki-reprap** [comment]
No not yet I have setup  Home Assistant  to test the hardware first

**Comment by 1technophile** [comment]
If you succeed in integrating with Domoticz please let me know, I'm going to close this issue as I don't have infos to give you on that
