### ISSUE TITLE
configuration blocks the work nodemcuv2-rf-cc1101.bin  GPIO 0 (D3) 

### ISSUE THREAD

**Issue by Monya2016** [1technophile/OpenMQTTGateway#1191]
configuration blocks the work , cc1101 (rx) -GPIO 0  ESP8266 switches to the programming mode .
cc1101(TX)-GPIO3 interferes with work UART
RF_EMITTER_GPIO: 3 
RF_RECEIVER_GPIO: 0
please compile for others GPIO
I am a student, the project for arduino can be viewed with uncommented lines.

**Comment by DigiH** [comment]
When compiling your builds in the Arduino IDE or platformio you can define your own PIN DEFINITIONS as you require in

https://github.com/1technophile/OpenMQTTGateway/blob/development/main/config_RF.h#L124

Hope this helps

**Comment by Monya2016** [comment]
Thanks ! # delete in what lines for cc1101?

**Comment by DigiH** [comment]
Sorry, I don't quite understand that question, but maybe if you have a look at the CC1101 related documentation regarding the pinouts, as well as the required **ZradioCC1101** it becomes clearer

https://docs.openmqttgateway.com/setitup/rf.html#cc1101-pinout

In case you're using platformio you might also want to have a look at the predefined environment in platformio.ini

[env:nodemcuv2-rf-cc1101](https://github.com/1technophile/OpenMQTTGateway/blob/development/platformio.ini#L1019)

**Comment by Monya2016** [comment]
I use for ESP8266 + CC1101 
https://docs.openmqttgateway.com/upload/web-install.html

**Comment by Monya2016** [comment]
the device starts working if at the start mechanically disconnect cc1101 from GPIO0, after the start cc1101 can be connected

**Comment by DigiH** [comment]
On the web-install with predefined binaries there is no possibility to define your own GPIO pins or make any other build customisations. For that you would need to use the source code with the Arduino IDE or platformio.

I only have my CC1101s connected to ESP32s. Since this might be an issue with the default predefined RF_RECEIVER_GPIO: 0 on the ESP8266 it's best to leave this issue open for someone else to comment.

**Comment by Monya2016** [comment]
https://www.youtube.com/watch?v=QKiz63OB6Xo&t=286s
on video, the default firmware did not work, some receivers prevent the esp8266 from starting when GPIO0 (D3) are connected
is this the correct compilation?

**Comment by Monya2016** [comment]
in my case, connecting the receiver through a 5k resistor helped
