### ISSUE TITLE
Renaming Miflora device (HHCCJCY01HHCC) in HA doesn't rename the entity IDs, even if specified

### ISSUE THREAD

**Issue by mihsu81** [1technophile/OpenMQTTGateway#1192]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
Renaming Miflora device (HHCCJCY01HHCC) in HA doesn't rename the entity IDs, even if specified.

**To Reproduce**
1. Edit Miflora device and change the name
![image](https://user-images.githubusercontent.com/40715497/160248611-d5b4ca5a-876d-445e-87eb-dda1be4bfa75.png)
2. Click Rename when asked to rename entity IDs
![image](https://user-images.githubusercontent.com/40715497/160248623-5d60d99a-ecac-4901-bcf4-5d60ce021066.png)
3. Entity IDs keep the original name
![image](https://user-images.githubusercontent.com/40715497/160248632-0d5b559f-5b7a-4b22-b51e-42dfb0aa4f7d.png)

**Expected behavior**
Entity IDs should change from the generic name to the specified name of the device.
![image](https://user-images.githubusercontent.com/40715497/160248699-6706a6ea-a3eb-4883-8c32-04be71d3451d.png)

**Screenshots**
Added under the previous steps. I think it helps better explaining the issue.

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.11)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by 1technophile** [comment]
I think this is due to the fact that your device is created through Mqtt auto discovery.
If you want to have a particular entity id I suggest to define your sensor with yaml following the examples below:
https://docs.openmqttgateway.com/integrate/home_assistant.html#mijia-thermometer-ble

**Comment by mihsu81** [comment]
Hi @1technophile,
Probably yes, but on the other hand, the entities of a LYWSD03MMC with PVVX firmware get renamed fine when i rename the device.
![image](https://user-images.githubusercontent.com/40715497/160258386-08e2b8fd-6a6e-4339-810a-2e276bc44056.png)
![image](https://user-images.githubusercontent.com/40715497/160258397-f1ab99f8-dc86-4b65-abf2-43a016cde293.png)
![image](https://user-images.githubusercontent.com/40715497/160258374-af72fd0f-4433-473d-8d18-27e4258071c6.png)

**Comment by TBail** [comment]
Wouldn't it be an option to use the mac adress of an sensor and not the model name? I have 15 Miflora sensors and now a lot of entities starting with hhc... and if we add the mac to the device name as well it should really easy to identifiy things

**Comment by mihsu81** [comment]
> I think this is due to the fact that your device is created through Mqtt auto discovery. If you want to have a particular entity id I suggest to define your sensor with yaml following the examples below: https://docs.openmqttgateway.com/integrate/home_assistant.html#mijia-thermometer-ble

Yeah, but auto discovery is more convenient, and renaming works fine for model LYWSD03MMC_PVVX. Just for HHCCJCY01HHCC doesn't work properly.

Could this really be caused by HA and not the implementation of auto discovery in OpenMQTTGateway?

**Comment by mihsu81** [comment]
Closing.
