### ISSUE TITLE
add  support for irremoteESP8266 version 2.2.0 library

### ISSUE THREAD

**Issue by yzg011** [1technophile/OpenMQTTGateway#120]
构建选项已变更，全部重新构建
C:\Users\Administrator\Desktop\RasWxMusicbox-master\OpenMQTTGateway\ZgatewayIR.ino: In function 'boolean IRtoMQTT()':

ZgatewayIR:66: error: 'USECPERTICK' was not declared in this scope

       rawCode = rawCode + (results.rawbuf[i] * USECPERTICK);

                                                ^

exit status 1
'USECPERTICK' was not declared in this scope

**Comment by 1technophile** [comment]
Please be more detailled, which version of the gateway which version of irremote esp8266 ? 
In all the case you should use the libraries linked into the libraries directory.

**Comment by yzg011** [comment]
the last new version of gateway，irremote esp8266 version 2.1.1 ok
irremote esp8266 version 2.2.0 not work。

**Comment by gammelobst** [comment]
you have to copy the supplied library to your system arduino lib folder.
I got the same error when using another than the supplied version, but after copying IRRemoteESP8266 to the lib folder it compiles and work like a charm.
cya

**Comment by 1technophile** [comment]
@gammelobst are you able to compile with the last version of Irremote_esp8266?

**Comment by gammelobst** [comment]
i can compile with the here mentioned and linked lib.
But if i update to the latest version via lib-manager than i get the same error.

**Comment by 1technophile** [comment]
Ok thanks for the feedback i will include the last version on v0.5
