### ISSUE TITLE
gateway not support mDNS for mqtt

### ISSUE THREAD

**Issue by yzg011** [1technophile/OpenMQTTGateway#121]

**Comment by 1technophile** [comment]
https://github.com/mrdunk/esp8266_mdns

**Comment by yzg011** [comment]
https://github.com/mertenats/Open-Home-Automation/tree/master/ha_mqtt_light_with_WiFiManager_mDNS_and_OTA
for your referrence！ thank you

**Comment by yzg011** [comment]
very import for me ，to look for the IP address and the port of the local MQTT broker automation

**Comment by yzg011** [comment]
thanks very much！
