### ISSUE TITLE
Removal of Bluetooth device type TPMS

### ISSUE THREAD

**Issue by mihsu81** [1technophile/OpenMQTTGateway#1215]
**Is your feature request related to a problem? Please describe.**
Bluetooth TMPS devices keep appearing when HA Auto Discovery is enabled.

**Describe the solution you'd like**
Removal of Bluetooth device type TPMS, as already done in v0.9.12 for GAEN, MS_CDP and iBeacon.

**Describe alternatives you've considered**
.

**Additional context**
![image](https://user-images.githubusercontent.com/40715497/168416716-af507da8-8956-4dd6-93e3-406361577083.png)
![image](https://user-images.githubusercontent.com/40715497/168416775-ed7ff12e-57ca-464f-b892-d44ba230218a.png)

**Comment by 1technophile** [comment]
I'm suspecting a bug on the decoder or decoder processing, you should not have [TPMS](https://github.com/theengs/decoder/blob/development/src/devices/TPMS_json.h) entities created if you don't have a BLE TPMS.

Are those devices created with v0.9.12 or where there prior to it?

**Comment by mihsu81** [comment]
The entities are created with v0.9.12. They appeared a couple of days ago, while the update to v0.9.12 was performed approximately a week ago.

**Comment by 1technophile** [comment]
@mihsu81 Could you try this new version of the decoder and check if you still see TPMS ?
https://github.com/theengs/decoder

**Comment by mihsu81** [comment]
Sorry for the delay. Completely forgot about it. I've upgraded the gateways to v0.9.13. Let's see if the TPMS devices reappear.

**Comment by 1technophile** [comment]
Should be good with the new versions
