### ISSUE TITLE
Cannot configure gateway by WiFi

### ISSUE THREAD

**Issue by xfishernet** [1technophile/OpenMQTTGateway#1217]
<img width="302" alt="Screenshot 2022-05-19 at 09 53 38" src="https://user-images.githubusercontent.com/5359718/169229295-6a9af59d-f7ed-4b28-91a2-bdc3fac9d562.png">

nodemcuv2-ble-firmware.bin

![tempImagej2ExHF](https://user-images.githubusercontent.com/5359718/169229514-0fcf05da-abd5-44b2-91eb-d204ccdf4221.gif)

192.168.4.1 not available :-(

**Comment by 1technophile** [comment]
Sorry for the late reply, missed your issue.
With BLE I advise to use an ESP32, we do not support ESP8266 + HM10 anymore
