### ISSUE TITLE
BLE Mesh support

### ISSUE THREAD

**Issue by l1bbcsg** [1technophile/OpenMQTTGateway#1219]
As far as I understand OpenMQTTGateway does not BLE Mesh currently?

Are there any plans to support it?

BLE mesh is a protocol distinct from BLE. In a nutshell, it's a mesh network competing with Zigbee.
Hardware support is universal though, both popular chips and SDKs from Espressif and Nordic support Mesh out of the box.

Running as BLE Mesh Proxy node would a perfect use case scenario for a MQTT broker. Currently there are no easy ways to integrate BLE Mesh into home automation systems.

**Comment by h2zero** [comment]
While this would be a nice addition it would be a lot of work and probably not worth it as there are very few devices (that I know of) with mesh capability.

What devices do you have that you'd like to communicate with?

**Comment by 1technophile** [comment]
Feel free to answer and reopen if needed

**Comment by 1technophile** [comment]
Feel free to answer and reopen if needed

**Comment by mariustt** [comment]
Hi,
I would like to ask if there are any plans to resume support for BLE Mesh? Currently, BLE SIG Mesh is becoming increasingly popular among Tuya devices.
