### ISSUE TITLE
MCU swipes firmware successfully for the first time, but cannot connect after restart

### ISSUE THREAD

**Issue by mildrabbit** [1technophile/OpenMQTTGateway#1232]
I used MCU and esp8266-12s to burn "nodemcuv2 IR firmware.bin (v0.9.13)"  can only be used once. After restarting the module, you cannot connect to the mqtt broker integrated by homeassistant, but the IP address connection is normal. Please tell me how I should deal with this problem.

**Comment by 1technophile** [comment]
Could you share an extract of your serial monitor ?

**Comment by mildrabbit** [comment]
The problem has been found. For the same firmware, there will be problems when using tasmoter program to burn, and there will be no problems when using esphone flasher to burn.
