### ISSUE TITLE
Prebuilt binary issues with nodemcuv2-rf-cc1101

### ISSUE THREAD

**Issue by awdark** [1technophile/OpenMQTTGateway#1257]
When using the prebuilt binaries the AP generation fails 
*wm:[0] [ERROR] There was a problem starting the AP openmqttgateway

Workaround - Install nodemcuv2-rf so the SSID will be OpenMQTTGateway_ESP8266_RF then configure the device.  Afterwards I upload the desired version nodemcuv2-rf-cc1101 without the "erase flash" option so it would retain the wireless settings.  

I suspect the automatically generated SSID - OpenMQTTGateway_ESP8266_CC1101 may be exceeding the maximum SSID length. 

Reproduce
Install nodemcuv2-rf-cc1101 onto a NodeMCU with the "erase flash" option enabled.
Monitor status over flash, note line *wm:[0] [ERROR] There was a problem starting the AP openmqttgateway
Scanning with phone shows an ESP-(last 6 of the MAC)

Expected behavior
SSID shows up, connect, configure.

Environment
NodeMCU with nothing connected.
Version - newest available with nodemcuv2-rf-cc1101 selected 
https://docs.openmqttgateway.com/upload/web-install.html

Sub-Issue
CC1101 pin-out https://docs.openmqttgateway.com/setitup/rf.html#pinout refers to D2, D3, etc but this varies depending on the board.  Wemos vs NodeMCU vs bare ESP12.  Specifying the numbers are for the NodeMCU or GPIO would work.

The CC1101 in the documentation connects to D3.  The D3 pin corresponds to GPIO0 so it actually would not boot with the CC1101 connected.  

Using the workarounds 
Configure wifi with different firmware
Boot with D3 (GPIO0) disconnected then connect shows the CC1101 functioning without issue so it may need to be mapped by default to a different pin.

**Comment by 1technophile** [comment]
Fixed on development
