### ISSUE TITLE
BLE and RTL_433_ESP unable to compile

### ISSUE THREAD

**Issue by murfy76** [1technophile/OpenMQTTGateway#1258]
Hello,

I was unable to compile BLE and RTL_433_ESP features together no matter what. Is there some limitation, which breaks compilation of these two feature together or I'm missing something? Thank you for your great work on this project.

Regards
Peter

**Comment by NorthernMan54** [comment]
Both modules are very memory intensive, so when combined there isn’t enough available for the two modules to run.
