### ISSUE TITLE
Uploading firmware to ESP8266

### ISSUE THREAD

**Issue by FerronN** [1technophile/OpenMQTTGateway#1272]
**Describe the bug**
I'm trying to flash the nodemcuv2-ir onto the ESP8266, but it stop after initializing. The LED flashes (erase flash), but after that nothing happens.

**To Reproduce**
![image](https://user-images.githubusercontent.com/16306688/190717034-e3a07d7d-0f01-40a1-b23a-974b0d9844ac.png)

The COM port driver is installed. I uploaded some code with the Arduino IDE to the ESP8266 and that works without any problem.
So I think it's not the device or some driver.

**Expected behavior**
Upload firmware

**Comment by 1technophile** [comment]
Do you reproduce on several ESP8266 ?

**Comment by FerronN** [comment]
No, because I only have one. I now managed to do it with `NodeMCU-PyFlasher`. But I had to change the flash mode to `DOUT`. On the website you can't choose the flash mode, so maybe the site uses `DIO`? I couldn't find the scirpt that's running.

**Comment by 1technophile** [comment]
Here is the script https://github.com/1technophile/OpenMQTTGateway/blob/development/scripts/gen_wu.py
Not sure we detail the flash mode

**Comment by 1technophile** [comment]
Closing, feel free if there are other questions
