### ISSUE TITLE
OMG on ESP32 stops updating BTtoMQTT

### ISSUE THREAD

**Issue by ssalonen** [1technophile/OpenMQTTGateway#1278]
**Describe the bug**

Data stops being published to BTtoMQTT thread, after some week(s) of running smoothly.

I am running OMG on ESP32 with continuous BT scanning, config below.

Other topics such as SYStoMQTT and LWT are still getting updated.

After issuing restart command via MQTT, data starts to flow in BTtoMQTT

**To Reproduce**

```

[env:esp32dev-ble-cont-openhab_id1]
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
platform = ${com.esp32_platform}
board = esp32dev
board_build.partitions = min_spiffs.csv
lib_deps =
  ${com-esp.lib_deps}
  ${libraries.wifimanager32}
  ${libraries.ble}
  ${libraries.decoder}
build_flags =
  ${com-esp.build_flags}
  '-DZgatewayBT="BT"'
  '-DLED_SEND_RECEIVE=2'
  '-DLED_SEND_RECEIVE_ON=0'
  '-DTimeBtwRead=0'
  '-DScan_duration=1000'
  '-DAttemptBLECOnnect=false'
  '-DOpenHABDiscovery=true'
  '-DGateway_Name="OpenMQTTGateway_1"'
  '-DMQTT_SERVER="${secrets.mqtt_ip}"'
  '-DMQTT_PORT="${secrets.mqtt_port}"'
  '-DMQTT_USER="${secrets.mqtt_user}"'
  '-DMQTT_PASS="${secrets.mqtt_pass}"'
  '-Dwifi_ssid="${secrets.wifi_ssid}"'
  '-Dwifi_password="${secrets.wifi_pass}"'  
  '-DESPWifiManualSetup=true'
``` 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by ssalonen** [comment]
I am planning to enable trace logging via mqtt when reflashing the gateways

EDIT: Uhh.. logging via MQTT is no longer possible? I was looking at this old PR: https://github.com/1technophile/OpenMQTTGateway/commit/45a6bc8549bb3c786e2fb77dfc4180322f790336

**Comment by 1technophile** [comment]
It could be interesting to check the values of `freemem, freestack,uptime` do you have the history of those before the issue?

**Comment by ssalonen** [comment]
Unfortunately no… next time it happens I can record the values

**Comment by ssalonen** [comment]
I think I have this issue now. Have not restarted yet

Anything off here?

`
{"uptime":229578,"version":"version_tag","freemem":144592,"mqttport":"1883","mqttsecure":false,"freestack":3228,"rssi":-67,"SSID":"REDACTED","BSSID":"REDACTED","ip":"REDACTED","mac":"REDACTED","lowpowermode":0,"btqblck":0,"btqsum":5894,"btqsnd":5893,"btqavg":1.00017,"interval":0,"scanbcnct":10,"scnct":7409,"modules":["BT"]}
`

My version is a bit behind: https://github.com/ssalonen/OpenMQTTGateway/compare/lerbacka...1technophile:OpenMQTTGateway:development

For example this fix is missing https://github.com/ssalonen/OpenMQTTGateway/commit/8714141630a96361fdcb7f80435f940bd49e2d04

**Comment by 1technophile** [comment]
Seems good in term of values, could you update your version to 1.3.0 indeed

**Comment by ssalonen** [comment]
Thanks for the fast response. Will do and report back if this reoccurs

For the record, restart fixed the issue as expected. Values before restart

`{"uptime":269182,"version":"version_tag","freemem":144528,"mqttport":"1883","mqttsecure":false,"freestack":3228,"rssi":-67,"SSID":"xx","BSSID":"xx","ip":"xx","mac":"xx","lowpowermode":0,"btqblck":0,"btqsum":5894,"btqsnd":5893,"btqavg":1.00017,"interval":0,"scanbcnct":10,"scnct":7409,"modules":["BT"]}`

After restart

`{"uptime":6,"version":"version_tag","freemem":136868,"mqttport":"1883","mqttsecure":false,"freestack":4556,"rssi":-68,"SSID":"xx","BSSID":"xx","ip":"xx","mac":"xx","lowpowermode":0,"btqblck":0,"btqsum":0,"btqsnd":0,"btqavg":0,"interval":0,"scanbcnct":10,"scnct":0,"modules":["BT"]}`

**Comment by ssalonen** [comment]
OK updated now, now version is on top of https://github.com/1technophile/OpenMQTTGateway/commit/bd9dcf1ec858c8ad504cd7a154f689373f2cf4a9. Let's see if the issue reoccurs.

**Comment by 1technophile** [comment]
@h2zero do you have other ideas on this one?

**Comment by h2zero** [comment]
Not much to add, it's possible the BLE stack has gotten stuck and stops reporting the scanned devices, need logs to confirm that though.

**Comment by 1technophile** [comment]
@ssalonen please try the latest development branch. We added a watchdog to BLE.
Feel free to reopen if needed
