### ISSUE TITLE
Upload Page (Documentation) does not work initially

### ISSUE THREAD

**Issue by Lerosen** [1technophile/OpenMQTTGateway#1285]
**Describe the bug**

**To Reproduce**
1. Select a Firmware (ttgo-lora32-v1-868)
2. Click on Install
3. Select a Serial Port in the Dialog
4. Nothing happens

**Expected behavior**
I expect to see some progress screen or confirmation after selecting the serial port. I tried it a couple of times and only after waiting a couple of minutes and trying it again it worked. At least there should be a note on this behaviour.

**Screenshots**
![c1d0fd371f167e9c9b540b34b0d2e153](https://user-images.githubusercontent.com/20213986/195817634-8807f602-0fb5-49a4-af33-656117ff76ab.gif)

**Environment (please complete the following information):**
The page says `Last Updated: 8/13/2022, 2:32:22 PM` in the bottom.

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by 1technophile** [comment]
When selecting the serial port and clicking Connect, could you try to press the boot button or reset of your esp32 ?

**Comment by Lerosen** [comment]
Yes, I did. Were you able to reproduce it when not pressing the button?

As described the flashing did work after waiting some time without manually entering flash mode using the button.

**Comment by 1technophile** [comment]
Not sure if there is a particular behavior with this board, usually, you upload either by pushing or without, but this one seems to work sometime without pressing the PRG button.
