### ISSUE TITLE
How to push data to BLE device?

### ISSUE THREAD

**Issue by Leadrive** [1technophile/OpenMQTTGateway#1294]
Hi, the BLE device can send BTtoMQTT to MQTT.

Now, I want to push data to BLE device from MQTT, how to do?
thank you.

**Comment by 1technophile** [comment]
Hello,

You have more information below:
https://docs.openmqttgateway.com/use/ble.html#read-write-ble-characteristics-over-mqtt-esp32-only

**Comment by Leadrive** [comment]
@1technophile 
Thanks your reply.
Yes, I test the esp32, it can get MQTTtoBT command.

"ble_write_value":"TEST",

I want to know the esp32 how to tranfer the data TEST to BLE device?

**Comment by Leadrive** [comment]
I use the BLE device PHY6252 PB-03 module, it have a USART connector to send or receive command.
I want the BLE device can send and receive the MQTT message(user define data) throught Gateway.

**Comment by 1technophile** [comment]
I don't know this BLE module, but it seems that you will need to identify the service and characteristics you want to write in (if they exist). Either program the module with your firmware and define the services and characteristics.

**Comment by 1technophile** [comment]
Closing this, if you have other questions feel free to jump in the [forum](https://community.openmqttgateway.com/)
