### ISSUE TITLE
ZgatewayRF and ZgatewayRF2 doesn't work together for receiving

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#130]
With the following setup:
Only RF gateways
NODEMCU V1.0
Arduino 1.8.3
Boards ESP8266 2.3.0
OpenMQTTGateway V0.4
Default pinout

ZgatewayRF receives 433Mhz if ZgatewayRF2  is commented
ZgatewayRF2  receives 433Mhz if ZgatewayRF is commented

**Comment by 1technophile** [comment]
@larsenglund are you using both gateways for receiving?

**Comment by larsenglund** [comment]
Nope, I think you would have to implement support for that yourself (simultaneous receiving of both protocols).

**Comment by 1technophile** [comment]
Thanks for the clarification!

**Comment by NDR008** [comment]
Can to RX units be installed in such a way to keep RF2 and RF functionality or...?

**Comment by 1technophile** [comment]
See #329 
I would prefer to add CC1101 support rather than trying merging both libraries.

There is also a chance that Zgatewaypilight answer now to your need
