### ISSUE TITLE
Unable to make SRX882S ( v2.0 ) to work with ESP8266 or ESP32

### ISSUE THREAD

**Issue by Vendo232** [1technophile/OpenMQTTGateway#1312]
**Describe the bug**
Setting up SRX882S to receive RF with ESP8266 or ESP32, changed pins in Arduino per recommendation and device works I can see it online and connected but no RF reception. 

![image](https://user-images.githubusercontent.com/44098230/200097356-b1d3b73a-c66e-4a39-9c69-e479d2d24af6.png)

![image](https://user-images.githubusercontent.com/44098230/200096765-68241665-cd54-47b9-a3d5-a63abd60f6e5.png)
No RTL_433toMQTT topics when 433MHz device triggered in close proximity. The RF device is functional and verified with orther working instance using CC1101 ( which works OK ) 

I expect to receive topics for door/motion sensors as in this pictures. ( using ESP32 and CC1101 ) but for SRX882S nothing is recieved.
![image](https://user-images.githubusercontent.com/44098230/200097056-0e3ead45-45da-4697-9908-49e567bd1825.png)

Setup of Arduino showing what pins I selected. ( also tried 13 for receiver ) 
![image](https://user-images.githubusercontent.com/44098230/200096856-cc6bc6b2-0dd5-41df-9a40-d38abe04776e.png)

Wiring 
![image](https://user-images.githubusercontent.com/44098230/200096878-ca9e5f3e-f698-441f-87e0-e7d5d0ff0810.png)

![image](https://user-images.githubusercontent.com/44098230/200096903-1dfc8676-bba7-4314-a376-4c2e1f648695.png)

used OpenMQTTGateway ver: 1.0 , 0.9.15 , 0.9.16 no difference

This is second set of SRX882 , after first was not working, ordered second set from different vendor and it is not working.

**Comment by 1technophile** [comment]
Hello

> No RTL_433toMQTT topics when 433MHz device triggered in close proximity. 

RTL_433 decoding will work only [with CC1101 and SX127X modules](https://docs.openmqttgateway.com/use/rf.html#rtl-433-device-decoders) and ESP32, with SRX882S you can use RF, RF2 or Pilight gateways.

Also, you would need devices that are compatible with those gateways. Your best guess is to try first RF.

**Comment by Vendo232** [comment]
> Your best guess is to try first RF

thank you Sir for comming back to me. I forgot to mention above that the the FW I`m using is the RF for ESP8266

![image](https://user-images.githubusercontent.com/44098230/200125649-52f828c2-c89c-4d97-a214-72d56b1d3fb1.png)

I have tried 3 other ESP boards, all work OK, I can setup WIFI , MQTT etc.. but there is something between the board and SRX882S that does not work correctly, I`m not getting anything. As mentioned above also ordered from different vendor second set and nothing.

I was hoping that one could tell me I`m doing something fundamentally wrong in my setup for RF and SRX882C.

( I have second instance ESP32 + CC1101 + RTL433 and that is working fine )

**Comment by Vendo232** [comment]
I guess my question would be how would the MQTT topics show up in MQTT Explorer if I use RF FW and SRX882C?

**Comment by DigiH** [comment]
Hi @Vendo232 , is it just me, or is the VCC not also connected to the data pin of the SRX882S on the second picture above?

**Comment by Vendo232** [comment]
hello @DigiH I do not have VCC connected to the Data pin I`m using this schematics

the pins on the receiver are from left: GND, DATA, CS, VCC

GND: GND
Data: not connected
CS: D1 ( GPIO5 )
VCC: VIN or 3V

but interestingly I measured V on VIN pin and on the ESP the VIN is only 1.6V. So I switch the VCC to 3V3 on ESP. Now the question is if 3.3V is enough for SRX882S
![image](https://user-images.githubusercontent.com/44098230/200127727-a0a3b213-b514-4e4d-959c-bc668b468d21.png)

**Comment by DigiH** [comment]
Sorry, yeah I meant the CS pin, just looks like it on the picture, that both blue (VCC and D1) wires are both going into the same CS. Could very well just be the angle of the photo.

I'm using the same setup, admittedly though with an SRX882 and not SRX882S.

**Comment by DigiH** [comment]
Could you change the power connections from the VIN (which is mainly used for input, also usually but not always giving a nice regulated output) of the ESP8266 to the actual V3 output?

**Comment by Vendo232** [comment]
@DigiH  I have tried that, measured 3.3V on the receiver directly, also tried to supply 4.8V from other source again measured directly on the receiver. 

the SC is connected to the D1 pin and nothing. 

When I trigger 433Mhz door sensor right next to it I get readings on my ( ESP32 + C1101 + RTL433 ) upstairs but no readings in MQTT Explorer under this device.

**Comment by DigiH** [comment]
> When I trigger 433Mhz door sensor right next to it I get readings on my ( ESP32 + C1101 + RTL433 ) upstairs but no readings in MQTT Explorer under this device.

If your door sensor is being picked up by RTL433 and therefore recognised and decoded by RTL433 it won't show up on an RF gateway with SRX882S using RF, RF2 or Pilight. 

So the door sensor cannot be used as a test device to see if your RF gateway is working. Do you have any other 433 RF devices, which are not being picked up by RTL433?

**Comment by Vendo232** [comment]
@DigiH thank you for confirming that the SRX882 is working for you. Perhaps there is something esle in the "S" version different

![image](https://user-images.githubusercontent.com/44098230/200128821-2de45811-8ab1-4354-a0e5-064bc017d384.png)

**Comment by Vendo232** [comment]
> 
> If your door sensor is being picked up by RTL433 and therefore recognised and decoded by RTL433 it won't show up on an RF gateway with SRX882S using RF, RF2 or Pilight.


Should I disconnect the RTL433/ESP32 device? 

I also have Docker RTL_433 instance and Sonoff RF Gate with Tasmota and I get readings from the door sensor independently in the MQTT .

So I think unless it is a different mqtt topic which it is in my case the reading should come up. 

![image](https://user-images.githubusercontent.com/44098230/200129105-965d5cc9-e93c-48bf-b64c-4b5b46c712c6.png)

**Comment by DigiH** [comment]
> Should I disconnect the RTL433/ESP32 device?

That won't change anything, what I meant was that if a device is recognised by the RTL433 library it will not be picked up by any of the other RF libraries, i.e. RF, RF2 or Pilight.

So your door sensor will only ever be recognised and picked up by an OMG RTL433 gateway, or any other RTL433 gateways, with such an OMG gateway only working with a CC1101 or SX127X module.

So your RF gateway with the SRX882S might be working perfectly. You just don't seem to have any device (yet) which it could pick up to report via MQTT.

**Comment by Vendo232** [comment]
> So your door sensor will only ever be recognised and picked up by an OMG RTL433 gateway, with such a gateway n ly working with a CC1101 or SX127X module

@DigiH thank you, I did not know it. the RTL433 with ESP32 picks up all my devices just fine except my neighborhood weather stations ( probably due to weak antenna )

I will place the ESP8266 + RF + SRX882S somewhere higher in my house and see if it picks up something else.

With my Linux + Docker + RTL433 + DVB dongle I get some TPMS readings plus few weather stations, was hoping the ESP8266 would give me better readings.

**Comment by DigiH** [comment]
With the recent changes to OMG including the new radiolib and also supporting SX127X modules, it might be worth trying such a module, as many tests seem to indicate better RTL433 reception than with a CC1101, so you might be able to pick up your neighbourhood RTL433 weather stations like that.

Testing and trying different external antennas for a CC1101 or SX127X, and also positioning them upright could help with RTL433 ESP32 reception.

Admittedly though, a DVB dongle running RTL433 on linux will probably most of the time have the widest reception. 

All the best

**Comment by Vendo232** [comment]
@DigiH  thank you for your time! would you be able to share an Aliexpress linkn for recommended SX127X module?

**Comment by DigiH** [comment]
> @DigiH thank you for your time! would you be able to share an Aliexpress linkn for recommended SX127X module?

Most tests have been done by @NorthernMan54 - the maintainer of the rtl_433_ESP library -  and OMG's @1technophile with dedicated **ESP32 HELTEC LORA32 v2** which is an all in one ESP32 with in built SX127X and a screen.

https://de.aliexpress.com/item/1000006969786.html

This might be an option for you as well. 

I opted for a separate SX127X module to hook up to an ESP32

https://de.aliexpress.com/item/1005004532397555.html

but it only arrived yesterday and I haven't hooked it up and tested it yet ;)

**Comment by DigiH** [comment]
@Vendo232 , one last question, before you go off an order some of the above SX127X devices.

What are these weather stations recognised as with your DVB dongle running RTL433?

They might be using FSK modulation, which is currently not supported in the rtl_433_ESP yet, compared to the full rtl_433.

https://github.com/NorthernMan54/rtl_433_ESP#enabled-rtl_433-demodulation-modules

**Comment by Vendo232** [comment]
I have not tried Transmition via 433 before, it was always just to receive signal in my case. I have tried to send msg via MQTT and I got the "433toMQTT" topic for SRX882S. Not sure though if it is just internal signal or real RF received.

Interestingly the ESP32+RTL433+C1101 picked up the signal and it is very interesting how it is decoding the signal.

![image](https://user-images.githubusercontent.com/44098230/200132248-30c025d2-e25f-4dd5-980c-ebcf859d279a.png)

**Comment by Vendo232** [comment]
> What are these weather stations recognised as with your DVB dongle running RTL433?

@DigiH I do not have the instance running now, but will try to get readings from one station and get back to you.

**Comment by Vendo232** [comment]
if I send via RF RXS882S msg {"value":1315160}

this is how ESP32+RTL433+C1101 receives it
![image](https://user-images.githubusercontent.com/44098230/200132668-46fc94f9-9728-4bbd-96ac-a3f028f04333.png)

the ESP8266+RSX882S will just get 
![image](https://user-images.githubusercontent.com/44098230/200132706-37d3be92-befe-4b3e-be5e-2785f9caa6da.png)

this is how my Linux+DVB+RTL433 sees it
![image](https://user-images.githubusercontent.com/44098230/200132975-8ffade42-30df-4e74-85d2-7f9f81579488.png)

and the Sonoff RF Gate with Tasmota
![image](https://user-images.githubusercontent.com/44098230/200133232-3f7f924c-6931-414c-9289-9ba337f8f2ab.png)

**Comment by DigiH** [comment]
> this is how ESP32+RTL433+C1101 receives it ![image](https://user-images.githubusercontent.com/44098230/200132668-46fc94f9-9728-4bbd-96ac-a3f028f04333.png)
> 
> the ESP8266+RSX882S will just get ![image](https://user-images.githubusercontent.com/44098230/200132706-37d3be92-befe-4b3e-be5e-2785f9caa6da.png)

Yes, false positives are not that uncommon with rtl_433. They can be safely ignored, unless of course you have some of these devices and rely on only proper readings for them. To completely remove them from being recognised at all **rtl_433_esp** has the option to define and only _allow_ MY_DEVICES.

**Comment by hallard** [comment]
Sorry to hijack this thread but I spent time to investigate why my SRX882S was not working, with ESP32 and official wiring such as:

- VCC : 3.3V
- GND : GND
- DATA : GPIO27

When I measured CS it was 0V so my guess was that my SRX882S CS pin has pulldown while SRX882 has pull up

Confirmed by this post (just saw it after my own investigation)
![image](https://user-images.githubusercontent.com/2471931/204168292-df283e0f-fd1e-461b-91e3-79a3e4a7a7ed.png)

So to get to working I connected CS to 3.3V and now it's working fine and you can apply this also to SRX882 V1 it does not hurts and make documentation consistent for all SRX882 version.

- VCC : 3.3V
- CS : 3.3V
- GND : GND
- DATA : GPIO27

Worth having a note on documentation :-)

**Comment by Vendo232** [comment]
> Sorry to hijack this thread but I spent time to investigate why my SRX882S was not working, with ESP32 and official wiring such as:
> 
> * VCC : 3.3V
> * GND : GND
> * DATA : GPIO27
> 
> When I measured CS it was 0V so my guess was that my SRX882S CS pin has pulldown while SRX882 has pull up
> 
> Confirmed by this post (just saw it after my own investigation) ![image](https://user-images.githubusercontent.com/2471931/204168292-df283e0f-fd1e-461b-91e3-79a3e4a7a7ed.png)
> 
> So to get to working I connected CS to 3.3V and now it's working fine and you can apply this also to SRX882 V1 it does not hurts and make documentation consistent for all SRX882 version.
> 
> * VCC : 3.3V
> * CS : 3.3V
> * GND : GND
> * DATA : GPIO27
> 
> Worth having a note on documentation :-)

It worked sir! Should be noted in wiki this detail!

**Comment by 1technophile** [comment]
Docs updated
