### ISSUE TITLE
New protocol help

### ISSUE THREAD

**Issue by bkenobi** [1technophile/OpenMQTTGateway#132]
I have protocols defined for 3 devices that I would like to provide with the hopes it could be included. I'm not sure how to add these to rcswitch or else I'd add them myself and provide the code.  The devices are sensors that transmit to a base station on 433MHz, so inclusion should be ease.  The devices are an Acurite weatherstation, an Acurite temperature sensor, and a Blueline power monitor.  The protocol and decode procedures are already coded and working in arduino project, just not one based on rcswitch.

**Comment by 1technophile** [comment]
You could publish your codes so as to enable me to take a look and see if it could be integrated

**Comment by 1technophile** [comment]
@bkenobi some news about that

**Comment by Landrash** [comment]
@1technophile From @bkenobi 's github https://github.com/bkenobi/ookDecoder

**Comment by 1technophile** [comment]
thx

**Comment by 1technophile** [comment]
@bkenobi could you try the last release with ZgatewayPilight uncommented, it supports many more protocols compared to rcswitch?

**Comment by 1technophile** [comment]
Im' closing this issue, if you have feedback don't hesitate to put it here
