### ISSUE TITLE
Readings from RTL_433 are always converted to metric even when unwanted

### ISSUE THREAD

**Issue by melyux** [1technophile/OpenMQTTGateway#1346]
**Describe the bug**
Right now, the `rtl_433` module's library (https://github.com/NorthernMan54/rtl_433_ESP) by @NorthernMan54 converts all readings to metric by default (because the `conversion_mode` configuration is set to `CONVERT_SI` by default in that library).

https://github.com/NorthernMan54/rtl_433_ESP/blob/master/src/decoder.cpp#L50

This is okay, I guess, but my sensors report temperature in Fahrenheit by default and I'd like to read it that way too without having to de-convert it from Celsius. Actually, I'd just like all my device readings to be shown in whatever unit the device provides, `CONVERT_NATIVE`, or convert all to imperial units instead of metric, `CONVERT_CUSTOMARY`.

Unfortunately, looking through the code for a while, I couldn't figure out how or if OMG interfaces with `rtl_433_ESP`'s configuration options to set this `conversion_mode`. I'd be up to do a PR to add the option to OMG if I could see a pathway. Some help @NorthernMan54, @1technophile?

**Comment by NorthernMan54** [comment]
The conversion setting in rtl_433_ESP is here

https://github.com/NorthernMan54/rtl_433_ESP/blob/77b4c8ac86fefca514c41a34fb6e25de6c409190/src/decoder.cpp#L50

**Comment by NorthernMan54** [comment]
Am thinking a compiler directive for RTL_433_ESP is likely the easiest approach to achieve what you’re looking for.  The rtl_433 cfg object is not something I have tried changing settings post initialization yet.  But if you wanted to, it would need a method exposed from rtl_433_ESP, then a change to openmqttgateway/ZgatewayRTL_433.ino to control the method.

**Comment by melyux** [comment]
Thanks @NorthernMan54, that's what I thought

**Comment by melyux** [comment]
?

**Comment by melyux** [comment]
Haven't checked recent versions yet

**Comment by micander** [comment]
Ugh, stale issue bots are incredibly toxic. This still needs to be fixed. The problem code has been relocated here: https://github.com/NorthernMan54/rtl_433_ESP/blob/276bc2cc6cef73037aaf3325b69be99ccd139742/src/signalDecoder.cpp#L68

**Comment by micander** [comment]
Since the bot isn't reopening it, I'm making a new issue. Please consider removing auto-closing of stale issues.

See: https://www.youtube.com/watch?v=1lYgB_NHFYk
