### ISSUE TITLE
Add repeat for IR_PANASONIC

### ISSUE THREAD

**Issue by glasruit** [1technophile/OpenMQTTGateway#136]
My Panasonic TV needs 3 IR repeats to switch on. I managed to do so by altering some lines of your code.

In `config_IR.h` line 43 add:
`#define PanasonicBits         48U        // Panasonic nr of bits (Pre data)`

In `ZgatewayIR.ino` change line 250 from
`irsend.sendPanasonic(PanasonicAddress, data);`
into
`irsend.sendPanasonic(PanasonicAddress, data, PanasonicBits, valueRPT);`

MQTT command to switch on the tv is:
`mosquitto_pub -t  home/commands/IR_PANASONIC/RPT_3 16825533`

**Comment by glasruit** [comment]
My Panasonic tv needs 3 IR repeats to switch on. I managed to do so by altering a few lines of your code.

In config_IR.h line 43 add:
`#define PanasonicBits         48U        // Panasonic nr of bits (Pre data)`

In ZgatewayIR.ino line 250 change
`irsend.sendPanasonic(PanasonicAddress, data);`
into
`irsend.sendPanasonic(PanasonicAddress, data, PanasonicBits, valueRPT);`

TV on with:
`mosquitto_pub -t home/commands/IR_PANASONIC/RPT_3 16825533`

**Comment by 1technophile** [comment]
Ok i will add it

**Comment by glasruit** [comment]
Sorry for not being clear at the first instance. Only TV-on needs 3 IR repeats. All other IR commands are single IR actions. Please delete line 251 in  `ZgatewayIR.ino`
`if (valueRPT == 0) valueRPT = 2;`

By the way, thank you for al your code.
