### ISSUE TITLE
1.2.0 does not read the data from MHO-C401

### ISSUE THREAD

**Issue by nonflammable** [1technophile/OpenMQTTGateway#1393]
1.2.0
{"id":"A4:C1:38:52:8F:62","mac_type":0,"name":"MHO_SAL","rssi":-92,"servicedata":"628f5238c1a48307e4128f0b64b40f","servicedatauuid":"0x181a"}

1.1.1
{"id":"A4:C1:38:52:8F:62","mac_type":0,"name":"MHO_SAL","rssi":-89,"brand":"Xiaomi","model":"LYWSD03MMC","model_id":"LYWSD03MMC_PVVX","tempc":19.58,"tempf":67.244,"hum":47.84,"batt":100,"volt":2.961}

Firmware: PVVX - MHO_C401_v39.bin

https://github.com/1technophile/OpenMQTTGateway/issues/1160

**Comment by DigiH** [comment]
Hi @nonflammable,

Do you use OpenMQTTGateway with prebuilt binaries or do you create your own builds in Platformio?

Just so we know how we can best supply a test version to you which has a fix.

**Comment by nonflammable** [comment]
Hi @DigiH 
I can test prebuilt bin (esp32dev-ble-firmware.bin)

**Comment by DigiH** [comment]
Hi @nonflammable 

you can also use the **test** web install at
https://docs.openmqttgateway.com/dev/upload/web-install.html

or the binary from
~~https://github.com/1technophile/OpenMQTTGateway/blob/gh-pages/dev/firmware_build/esp32dev-ble-firmware.bin~~
https://github.com/1technophile/OpenMQTTGateway/raw/gh-pages/dev/firmware_build/esp32dev-ble-firmware.bin

**Comment by nonflammable** [comment]
I can't upgrade via mqtt
`mosquitto_pub -t "home/OpenMQTTGateway_ESP32_BLE/commands/firmware_update" -m '{
  "version": "test",
  "password": "OTAPASSWORD",
  "url": "https://github.com/1technophile/OpenMQTTGateway/blob/gh-pages/dev/firmware_build/esp32dev-ble-firmware.bin"}'`

I will try flash with FDT tomorrow

**Comment by DigiH** [comment]
Hi @nonflammable, appologies, the link should have been

https://github.com/1technophile/OpenMQTTGateway/raw/gh-pages/dev/firmware_build/esp32dev-ble-firmware.bin

which should work with the MQTT update as well.

**Comment by nonflammable** [comment]
test version works fine

**Comment by DigiH** [comment]
Thanks for the feedback

**Comment by Noki** [comment]
I have the same issue on an M5Stack Atom Lite. The service data is not decoded anymore. I did a fresh install via the web uploader with an erase, the result remains the same.

**Comment by DigiH** [comment]
Hi @Noki , the test build mentioned above would have been overwritten by newer and nightly builds, so what you installed through the web uploader didn't have the fix in it.

Please hold on while a new test build run is running …

**Comment by DigiH** [comment]
@Noki 

Please try
https://docs.openmqttgateway.com/dev/upload/web-install.html
and let us know if it's fine for you.

**Comment by Noki** [comment]
@DigiH Thanks a lot! My problem is solved and all sensors show correct values again.

**Comment by DigiH** [comment]
Closing as the fix is included with the release of OpenMQTTGateway 1.3.0
