### ISSUE TITLE
V1.2.0 doesnt work on M5Stack atom lite

### ISSUE THREAD

**Issue by aschr** [1technophile/OpenMQTTGateway#1400]
II tried to install version 1.2.0 via "Upload from the web" on a M5Stack atom lite. After entering the WiFi credentials and MQTT configuration, the board restarts. The credentials are ignored and the AP starts instead. None of the settings seem to be saved.

The same procedure with version 1.1.1 ran without problems. What am I doing wrong? Was anyone already successful with V 1.2.0 on an atom lite?

Thanks in advance for helpful tips!

**Comment by 1technophile** [comment]
Just flashed my atom-lite with `esp32-m5atom-lite` from the web upload v1.2.0 (erased the flash also) and got it connected to the HA-provided broker:
![image](https://user-images.githubusercontent.com/12672732/212983511-a8f8bbd0-757a-4cca-a809-242e613f3c67.png)

Any specific with your network and broker ?

**Comment by aschr** [comment]
Hello @1technophile thanks for the quick reply. 

I tried it first with another atom lite and had the same problems. 
A reboot of my ap/router now seems to have fixed that.
A strange behavior, but what the heck, now it works.
