### ISSUE TITLE
Support for RGB LED

### ISSUE THREAD

**Issue by Landrash** [1technophile/OpenMQTTGateway#141]
Suggest support for RGB LED by the use of the http://fastled.io/ library.

Suggest integration with #40 for use as a status led.

**Comment by posicat** [comment]
I've got a couple spools of these LEDs laying around.  One of my projects upcoming is to put a bunch of them under my kitchen cabinets.  I had intended to use an ATTiny and Raspberry Pi, but I don't see why this couldn't be built in as a feature to OpenMQTTGateway.  I've used the Adafruit libraries before, and one from Josh.com that's super-memory efficient.  On a project like this, it might be useful to have the small library available for a status LED, and the fastled library available for controlling whole strands.

**Comment by posicat** [comment]
This is the other library I would investigate, if the fastled doesn't use too much memory, that sounds like a good candidate, this one however I run on ATTiny85's without memory problems, so it's nice and tiny.

https://wp.josh.com/2014/05/13/ws2812-neopixels-are-not-so-finicky-once-you-get-to-know-them/#more-1681

**Comment by joen** [comment]
I would like to add fastled support. Is anybody working on this already?

**Comment by posicat** [comment]
I had idly considered it, but I have plenty of work with the PCB project, and my own-home code that this all hooks into to get to adding LED support at this time.  I haven't seen anyone else mention taking this on, and my post revived a topic that had been idle 2 months, so it's probably safe.  Feel free to poke at me for any testing/help.  I've got plenty of WS2812's at home to try it with.

**Comment by 1technophile** [comment]
@joen I don't think so, in my point of view you can go

**Comment by joen** [comment]
[first tests](https://github.com/joen/OpenMQTTGateway) with just one LED

**Comment by 1technophile** [comment]
thanks @joen could you rename to ZactuatorFASTLED (to follow the naming convention as we are acting on a device) and submit a pull request?

**Comment by joen** [comment]
> could you rename to ZactuatorFASTLED
I am a little short on time, but will do it in the next days

**Comment by QuagmireMan** [comment]
Very excited to see this feature!

**Comment by insane2subro** [comment]
Very excited to see this work on LED Strips, FastLed is really amazing.

**Comment by 1technophile** [comment]
@joen do you think you could submit a pull request with your work?

**Comment by joen** [comment]
submitted just now. #266 

This is all a litte dirty, but working.
You could theoretically use all RGB-LEDs, that are supported by fastled. Just change the configuration according to config_FASTLED.h

I am not quite happy with the effects, which could be done in a more intelligent manner.
The overall idea is to have a color value send to a topic that is used as the color the effect is "played" in and as the color that is set, when the effect is finished.

This was tested with just one WS2812 led (neopixel) on a ESP8266 (nodeMCU)
