### ISSUE TITLE
HA MQTT password length

### ISSUE THREAD

**Issue by perseids29** [1technophile/OpenMQTTGateway#1410]
The password for my Mosguitto server in HA is 64 characters long by default and the WiFiManager only accepts 60 characters. Admittedly I am not very knowledgeable on this device(HiLetgo ESP32 LoRa SX1278 0.96 inch OLED Display Development Board WiFi Bluetooth Dual Core 240MHz CP2102 and 433/470MHz Antenna for Arduino Smart WiFi LoRa 32) and/or the protocol, programming, etc.
I was hoping to be able to capture commands to some LEDs I have and then be able to issue commands via Home Assistant.

**Comment by 1technophile** [comment]
Why not creating a shorter password, 60 gives already room?

**Comment by perseids29** [comment]
I would have to change it in all my other devices, which would be a pain

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1technophile** [comment]
You could create a new one instead. The other solution could be to change the size of the password length below:
https://github.com/1technophile/OpenMQTTGateway/blob/a3603c6a788609281743eeb72aaa44ff58a2db4f/main/User_config.h#L147

And build the firmware:
https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio

**Comment by 1technophile** [comment]
Closing, let me know if any other question
