### ISSUE TITLE
Add IR raw signal forward

### ISSUE THREAD

**Issue by PetricaM** [1technophile/OpenMQTTGateway#142]
Hi,

Could you add the option to forward the exact IR raw payload?

For IR devices using protocols with very large protocol length (ie. 112 bits) the payload is incompletely read (412 char although the total full raw message is 942 char).

Thanks

**Comment by 1technophile** [comment]
Hi, Could you test it from the master please (you need to put RawDirectForward true in config_IR.h)

**Comment by PetricaM** [comment]
Hi Florian,

I've tried it and the IR payload is still 412 long. I think this is due to the buffer size on the NodeMCU for receiving as for both serial and MQTT connection the message has the same size, so it's not due to length of MQTT payload. Only receiving is affected as sending raw IR works with the full message length.

Thanks

**Comment by 1technophile** [comment]
Could you try to increase RAWBUF in irrecv.h ?

**Comment by PetricaM** [comment]
Yes, that worked (I've set it to 300U).

Thanks

**Comment by 1technophile** [comment]
In this is case, is direct raw signal forward usefull or it can works also by mqtt signal forward (repeatIRwMQTT )

**Comment by PetricaM** [comment]
The initial problem was the message length. 

It's perfectly fine to use MQTT payload to forward it to another device in HA.

**Comment by 1technophile** [comment]
Ok i will let the direct raw forwarding if someone need it
