### ISSUE TITLE
Upload from the web broken

### ISSUE THREAD

**Issue by remcom** [1technophile/OpenMQTTGateway#1431]
the web uploader on https://docs.openmqttgateway.com/upload/web-install.html is broken.

The dropdown has 2 greyed out options that i cant select (esp32 and esp8266). if i click on install no i get no manifest selected error.

browser consoles state: /manifest.json:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by 1technophile** [comment]
Thanks for pointing it, I have relaunched the workflow and now you should be able to upload again
