### ISSUE TITLE
Support: OLIMEX ESP32 EVB gateway board w. LORA (SX1776)

### ISSUE THREAD

**Issue by g6094199** [1technophile/OpenMQTTGateway#1439]
Since the OLIMEX ESP32 gateway is already supported this one, the [OLIMEX ESP32 EVB ](https://www.olimex.com/Products/IoT/ESP32/ESP32-EVB/open-source-hardware) would be a very nice addition.
Many of the OLIMEX boards (also the EVB) come with a connector called UEXT and olimex offes a bunch of UEXT compatible hats for it. One very interesting is the [MOD-LoRa868](https://www.olimex.com/Products/IoT/LoRa/LoRa868/open-source-hardware) which is just plug n play to upgrade the ethernet gateway (EVB) to a lora ethernet gateway! No soldering needed. also a fitting case is offered. 

this would be a hassle free option for a ethernet LORA gateway!

is there an interest in supporting it? then i would order it.

**Comment by 1technophile** [comment]
I may have one let me check

**Comment by g6094199** [comment]
ordered one anyway.... this is the best ready to go option on the marked i can find.

**Comment by 1technophile** [comment]
I confirm that I have one, if you want to share an environment proposal I can test it

**Comment by g6094199** [comment]
>if you want to share an environment proposal I can test it

and with "environment proposal" you mean....?

**Comment by 1technophile** [comment]
Something like this:
https://github.com/1technophile/OpenMQTTGateway/blob/d09f13bf86524cc055b26aa34bd6097eedab12e2/environments.ini#L353
