### ISSUE TITLE
NodeMCU/ESP8266 DHT Sensor Documentation Issue

### ISSUE THREAD

**Issue by jeremyowens** [1technophile/OpenMQTTGateway#146]
The documentation (wiki) for the NodeMCU/ESP8266 DHT Sensor has conflicting information.  The documentation originally said to connect the DHT sensor to pin D5, however the code in config_dht.h is defined as pin D1.

Either the config_dht.h file needs to be updated to reference pin D5, or the picture in the wiki needs to be replaced with a picture that shows the wiring diagram connecting to pin D1.

I've updated the text documentation in the wiki to reference pin D1 for now, but have no way to update the picture.

_config_dht.h - https://github.com/1technophile/OpenMQTTGateway/blob/master/config_DHT.h
DHT Wiki - https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-DHT-Modules_

**Comment by 1technophile** [comment]
thanks for pointing this. It is corrected.

Please note that the orginal fritzing files are on the img folder
