### ISSUE TITLE
868Mhz rolling code 

### ISSUE THREAD

**Issue by geromey** [1technophile/OpenMQTTGateway#1461]
Hello, I am trying to controls 868Mhz shutters with rolling code, do you think that OpenMQTTGateway could help me ?

PS: I'm using a ESP32 and I'll soon receive an antenna CC1101

Thank you !

**Comment by 1technophile** [comment]
Hello,

rolling codes are not supported and I don't think you will find a way to support it.
Your best chances are wires in this case.

**Comment by Dattel** [comment]
i'm using Homeassistant with Node-Red and filtering all 4-rolling codes to one dedicated action... it looks a bit ugly, but it works 

have a look

![image](https://user-images.githubusercontent.com/17568075/232326913-6dda8d42-cd92-4b03-9a11-917d21c8b692.png)

same way arround... if i trigger an action in homeassistant, i send a single code through openmqtt and it works fine - even if you always send the same code.
But with omg1.5.1 it's broken due too some changes :-(

**Comment by NorthernMan54** [comment]
What build/RF Module are you using for this ?

**Comment by Dattel** [comment]
1.3.dev (latest version seems to be broken - see my latest issue), CC1101 - but with 433mhz Rollingcodes

**Comment by NorthernMan54** [comment]
RF/RCSwitch or PiLight or RTL_433_ESP ?

**Comment by Dattel** [comment]
i have two different setups, 
but don't wanna spam these topic with another issue -> so go on here https://github.com/1technophile/OpenMQTTGateway/issues/1609
