### ISSUE TITLE
Add compelling webinterface to BLE Gateway Binaries

### ISSUE THREAD

**Issue by rubenkr** [1technophile/OpenMQTTGateway#1480]
**Is your feature request related to a problem? Please describe.**
- Currently BLE Gateway binary esp32dev-ble comes without http webinterface
- MQTT works but results are overwhly crowded, hard to read and presence detection requires additional measures

**Describe the solution you'd like**
- Add webinterface of [BLE Scanner](https://github.com/gromeck/BLE-Scanner) existing reposity as awesome work of [@gromeck](https://github.com/gromeck)

Exemplary view (work of [@gromeck](https://github.com/gromeck))
![image](https://user-images.githubusercontent.com/1043739/220608807-5922bd58-708b-4a1e-b489-643fd4e77bb6.png)

**Comment by ilgrank** [comment]
+1

**Comment by 1technophile** [comment]
> and presence detection requires additional measures

Could you detail this please ?

Also, what would be the goal of this web interface as you have access to the information in the controller, or you can filter with MQTT clients like MQTT explorer ?

**Comment by rubenkr** [comment]
thanks for considering this feature. all data is available by the controller. this feature is solely focussing on the frontend to show the data in a instant way. As MQTT explorer are external and hard to read. This simple feature would work out of the box without a need of a MQTT explorer.

**Comment by ilgrank** [comment]
I would also add that not everyone is using a controller :)

**Comment by 1technophile** [comment]
Web interface (not BLE scanner) added to the current development branch. See the progress here:
https://community.openmqttgateway.com/t/webui-proof-on-concept-for-esp32-modules/2322/13

Feel free to share your feedback there
