### ISSUE TITLE
BT and RLT_433 Gateways both use `static NO_DEVICE_FOUND`, prevents both from being enabled. With pull-request.

### ISSUE THREAD

**Issue by SmittyHalibut** [1technophile/OpenMQTTGateway#1490]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
Enabling both `ZgatewayBT` and `ZgatewayRTL_433` results in a compile error because both gateways use the same static variable name, but of different types: `NO_DEVICE_FOUND`.

**To Reproduce**

I'm using PlatformIO

1. Add both `-DZgatewayBT="BT"` and `-DZgatewayRTL_433="rtl_433"` to `prod_env.ini`
2. Build.
3. See error.

**Expected behavior**
Build succeeds.

**Proposed solution**
Rename `NO_DEVICE_FOUND` to `NO_BT_DEVICE_FOUND` in `ZgatewayBT.ino`, and `NO_RTL_433_DEVICE_FOUND` in `ZgatewayRTL_433.ino`.

Pull request incoming. :-)

**Comment by GreenEyedAndy** [comment]
Hi @SmittyHalibut,
I tried to compile the Lilygo-rtl_433 with both `-DZgatewayBT="BT"` and `-DZgatewayRTL_433="rtl_433"` and add the   `${libraries.ble}` in the lib_deps section of in the environments.ini of the latest github version.
Then I build but still get the `NO_DEVICE_FOUND` error and something with `TheengsDecoder::BLE_ID_NUM::UNKNOWN_MODEL`.  
Can you help?

**Comment by SmittyHalibut** [comment]
Resolving. THe PR was merged.

**Comment by SmittyHalibut** [comment]
I don't see this post on the ticket anymore.  Did you delete it?

-Mark

**Comment by GreenEyedAndy** [comment]
Oh, sorry.
Yes I delete it after checking out the development-branch and try it again.
Then there were no errors but it is still not working.
Sorry for the confusion.

**Comment by SmittyHalibut** [comment]
Heh.  No problem. Just making sure I was looking in the right place.  Glad I could help!

Narrator: He did nothing to help.
