### ISSUE TITLE
Add the ability to set the parameters on a web page instead of the code

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#15]

**Comment by 1technophile** [comment]
some ideas for uno + W5100:
http://forum.arduino.cc/index.php?topic=55044.15

**Comment by ctripodi** [comment]
Hi, I agree, could be great to have this option enabled. 
Another example to be considered https://github.com/tzapu/WiFiManager

**Comment by DenDeze** [comment]
Check out esp-link for esp devices.

The nodemcu Lua firmware can be flashed with a webpage to set settings.

Must be an option on arduino ide

**Comment by animavitis** [comment]
https://github.com/marvinroger/homie-esp8266 have nice GUI to setup wifi/mqtt or custom paramters. Maybe migrate to homie-esp8266?

**Comment by 1technophile** [comment]
Indeed but i never checked the arduino compatibility do you have some infos about it  ?

**Comment by animavitis** [comment]
nope, but i will try to check it

**Comment by 1technophile** [comment]
duplicate of #83
