### ISSUE TITLE
Error: 'GAEN' is not a member of 'TheengsDecoder::BLE_ID_NUM'

### ISSUE THREAD

**Issue by ivankravets** [1technophile/OpenMQTTGateway#1513]
Hi there,

Firstly, Thanks for using PlatformIO for this fantastic project! We use OpenMQTTGateway to test PlatformIO Core itself.

Could you check the recently failed build?

- https://github.com/platformio/platformio-core/actions/runs/4367277337/jobs/7641624902

We really appreciate any help you can provide.

**Comment by DigiH** [comment]
Hi @ivankravets 

Just a temporary WIP with OpenMQTTGateway and Theengs Decoder.

Should be sorted out soon.

**Comment by 1technophile** [comment]
Hi,

Should be fixed now

**Comment by ivankravets** [comment]
Thanks for the quick fix!
