### ISSUE TITLE
Support for new Heltec WiFi LoRa 32 v3 (HTIT-WB32LAF)

### ISSUE THREAD

**Issue by ryanm101** [1technophile/OpenMQTTGateway#1517]
Ecowitt Weather stations transmit on 868Mhz and can be decoded by rtl_433 so would be nice to have this board supported. Would also be a LoRa to MQTT bridge. 

https://heltec.org/project/wifi-lora-32-v3/

https://github.com/1technophile/OpenMQTTGateway/issues/1436 was closed but not sure why as mentioned above 868Mhz and BLE would be possible with this board

**Comment by NorthernMan54** [comment]
The chipset within this board can not by used as receiver for rtl_433, as it does not support direct mode used by the codebase.

**Comment by ryanm101** [comment]
ahh ok thanks for the explanation
