### ISSUE TITLE
Disable Display/OLED

### ISSUE THREAD

**Issue by foorschtbar** [1technophile/OpenMQTTGateway#1520]
It is possible to disable the OLED Display on my ttgo-lora32-v21 with a single command? I dont want to modify te sourcecode for that :)

**Comment by 1technophile** [comment]
Will be available in the next version

**Comment by DigiH** [comment]
@foorschtbar this is integrated in the latest 1.5.0 release

https://docs.openmqttgateway.com/use/displays.html

**Comment by foorschtbar** [comment]
THX!
