### ISSUE TITLE
Schedule for new release?

### ISSUE THREAD

**Issue by toomyem** [1technophile/OpenMQTTGateway#1543]
Hi.

What is a chance of having new release of OMG with latest TheengsDecoder? I've added new protocols for CDGK2 sensor and it would be great to have it in OMG.

**Comment by 1technophile** [comment]
Hello,
I'm planning a new release by next week for info. We have already started testing, so if you want to add a new protocol, it should be added soon.

**Comment by 1technophile** [comment]
Just seen your PR :-) thanks
