### ISSUE TITLE
lilygo-rtl_433 does not try to connect to broker (but dev version does)

### ISSUE THREAD

**Issue by rodpayne** [1technophile/OpenMQTTGateway#1564]
**Describe the bug**
`lilygo-rtl_433` does not try to connect to MQTT broker on a brand new `LILYGO T3 v1.6.1 20210104`.  After configuring using the Wifi Manager portal, the last thing that the display says is "Wifi connected", including after resets.

I tried uploading a couple of times (Option 1), with Erase Flash checked, without luck.

**Uploaded from Dev https://docs.openmqttgateway.com/dev/upload/web-install.html (version 85d649) and the device began operating.  (And it is wonderful.)**

To verify that Dev helped, I uploaded v1.4.0 again and the device stopped again.  Uploaded the Dev version again and it is working.

**To Reproduce**
1. Upload lilygo-rtl_433 using Option 1.
2. Use Wifi Manager portal to set Wifi and MQTT parameters.
3. Verify that it stops with last message = "Wifi connected".

**Expected behavior**
"Wifi connected" should be followed by "MQTT connected".

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (v1.4.0, and 85d649 development)
* Library version related to the problem you have (lilygo-rtl_433)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

**Comment by rodpayne** [comment]
I connected to the display port and with Dev 4817f1 the following message repeats over and over with normal messages mixed in:
```
12:03:14.190 -> E (3591493) gpio: gpio_set_level(226): GPIO output gpio_num error
12:03:14.380 -> E (3591650) gpio: gpio_set_level(226): GPIO output gpio_num error
12:03:14.472 -> E (3591751) gpio: gpio_set_level(226): GPIO output gpio_num error
```
I switched back to v1.4.0 and it connected to the MQTT broker, but nothing is being reported from the radio.

```
12:34:36.791 -> rtl_433_ESP(7): Average RSSI Signal -100 dbm, adjusted RSSI Threshold -91, samples 50000
12:35:26.963 -> rtl_433_ESP(7): Average RSSI Signal -101 dbm, adjusted RSSI Threshold -92, samples 50000
12:35:55.448 -> N: Send on /SYStoMQTT msg {"uptime":1090,"version":"v1.4.0","freemem":162992,"mqttport":"1883","mqttsecure":false,"tempc":53.33333,"freestack":4696,"rssi":-46,"SSID":"Skynet2375","BSSID":"B0:39:56:DD:19:8F","ip":"172.19.54.73","mac":"D4:D4:DA:82:D7:5C","actRec":3,"mhz":433.92,"RTLRssiThresh":-92,"RTLRssi":-100,"RTLAVGRssi":-101,"RTLCnt":19,"RTLOOKThresh":90,"modules":["LilyGo_SSD1306","rtl_433"]}
12:36:17.114 -> rtl_433_ESP(7): Average RSSI Signal -101 dbm, adjusted RSSI Threshold -92, samples 50000
12:37:07.281 -> rtl_433_ESP(7): Average RSSI Signal -101 dbm, adjusted RSSI Threshold -92, samples 50000
12:37:55.460 -> N: Send on /SYStoMQTT msg {"uptime":1210,"version":"v1.4.0","freemem":162992,"mqttport":"1883","mqttsecure":false,"tempc":53.33333,"freestack":4696,"rssi":-47,"SSID":"Skynet2375","BSSID":"B0:39:56:DD:19:8F","ip":"172.19.54.73","mac":"D4:D4:DA:82:D7:5C","actRec":3,"mhz":433.92,"RTLRssiThresh":-92,"RTLRssi":-99,"RTLAVGRssi":-101,"RTLCnt":21,"RTLOOKThresh":90,"modules":["LilyGo_SSD1306","rtl_433"]}
12:37:57.471 -> rtl_433_ESP(7): Average RSSI Signal -100 dbm, adjusted RSSI Threshold -91, samples 50000

```
(I will keep poking at this.  Hopefully this is not happening because I am new at this.  Let me know if these reports are at all helpfull or if I should post somewhere else.)

**Comment by 1technophile** [comment]
Hello,

You may wait for tomorrow and the dev version will not have anymore this error:
`E (3591493) gpio: gpio_set_level(226): GPIO output gpio_num error`

Also we should release soon

**Comment by rodpayne** [comment]
Yes, the `GPIO output gpio_num error` message is gone in `d1e9e8`.

**Comment by rodpayne** [comment]
Version v1.5.0 is connecting fine.
