### ISSUE TITLE
SONOFF RF Bridge as a receiver is not sending the same values compared to ESP/arduino

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#157]
from test of @macscr on gitter

**Comment by 1technophile** [comment]
reproduced with Tasmota:
https://github.com/arendst/Sonoff-Tasmota/issues/1095

**Comment by MACscr** [comment]
Has this been resolved? I havent tried the newest edition.

**Comment by 1technophile** [comment]
Not yet
