### ISSUE TITLE
Topics are published above the mqtt base topic. 

### ISSUE THREAD

**Issue by MikeJaras** [1technophile/OpenMQTTGateway#1581]
I configure the gateway to have OpenMGTT as base topic. When looking in MQTT Explorer I get messages in topics above the base. Plenty of messages in homeassistant and $SYS. Since the free mqtt broker Adafruit IO doesn't accept this it rejects the messages and blocks incoming feed.
Expected is that all messages are published in the base topic. $SYS and homeassistant should be placed in base or configurable from the initial web gui.
In the picture my base is set to OpenMQTT.
![clip1](https://user-images.githubusercontent.com/33084283/228156391-5b3915b2-4c45-4a26-ad67-334195c0013d.jpg)

**Comment by DigiH** [comment]
Hi @MikeJaras,

The **$SYS** topic is from your MQTT broker, showing broker statistics, and really nothing OpenMQTTGateway can do about. You would need to have a look in your broker's documentation if and how this could be changed there.

The **homeassistant** discovery topic is the default discovery topic for Home Assistant. What topic have you set your Home Assistant instance to for these discovery messages, and are you using Home Assistance at all with discovery? The topic can currently only be changed by a build_flag during a custom build. This option is also newly available via web build at

https://docs.openmqttgateway.com/upload/gitpod.html

All other MQTT messages from your OpenMQTTGateway, and their sub topics, look correct under the changed OpenMQTT topic in your MQTT Explorer screenshot above, and they contain all rtl_433 device and gateway specific messages needed for further processing.

I hope this explains the topics you are seeing a bit better.

**Comment by MikeJaras** [comment]
Looks like I missed some of the basic features and I will look in to the custom build option you mention. I used the upload from web so far and I'm not using the homeassistant. Thx for you reply and I think this issue can be closed then.

**Comment by DigiH** [comment]
@MikeJaras 

You can also disable the homeassistant discovery messages with

https://docs.openmqttgateway.com/use/gateway.html#deactivate

at runtime. After that you can just select the homeassistant topic and delete it along with al its previous messages in MQTT Explorer.

**Comment by MikeJaras** [comment]
@DigiH 
When using Adafruit as broker it will block the gateway since it is publishing in a non accepted topic. So then I don't see how I can send the deactivate message that you suggest. 
When using my own mosquito server it's all fine and no problem receiving the homeassistant messages.
Any ideas?

**Comment by DigiH** [comment]
@MikeJaras 

You can send it with MQTT Explorer. In the **Publish** section enter

`OpenMQTT/OpenMQTT_433_MJ/commands/MQTTtoSYS/config`

as the topic, and in the payload field below select **json** and enter

`{"discovery":false}`

and hit **Publish.**

After that select the homeassistant topic and delete it with the trash icon at the top right section. This should delete all already present homeassistant topics, and with the above turning off the discovery messages there won't be any new discovery messages published.

This should allow you to use the Adafruit broker.

**Comment by MikeJaras** [comment]
So I figured it out how to send the _discovery:false_ message. Unfortunate it didn't help since the Adafruit IO got limited acceptance of how topics can be named. The topics can only have one level so the `OpenMQTT/OpenMQTT_433_MJ/commands/MQTTtoSYS/config` is not available. When messages are sent it doesn't show up and no sub-topics are created. 

Also the MQTT Explorer got limited support at the site and no messages are showing up. 

Good news is my own mosquito setup is working :-) and there is no issue with the OpenMQTT gateway.

**Comment by DigiH** [comment]
Good to hear you got everything running nicely on your local Mosquitto MQTT broker :)

Not having any experience with Adafruit IO, it is best to contact them for any issues, and how best possibly integrate.

**Comment by NorthernMan54** [comment]
@MikeJaras There is an undocumented compiler directive ` '-Ddiscovery_Topic="testAssistant"'` that you can use to change the root of the homeassistant discovery topic.  I use this to stop my OMG devices from polluting my production environment with test devices.

**Comment by MikeJaras** [comment]
@NorthernMan54 That's great, I'll try it out. Right now I turned it off with the command @DigiH mentioned. I'm surprised that I don't se more than two Fineoffset thermometers. I got plenty around me. Maybe that's a discussion for an other Issue.
