### ISSUE TITLE
lilygo-rtl_433 - Add build with PUBLISH_UNPARSED to the web-install page

### ISSUE THREAD

**Issue by marius-cornescu** [1technophile/OpenMQTTGateway#1589]
I would like to use the power of RTL-433 but in case the data is not recognized, I'd still like to see the raw messages, in case I can create some sort of parsing rule in node-red.
For this, I would need to build the lilygo-rtl_433 binary with the PUBLISH_UNPARSED flag ... but reading the documentation, multiple things are needed for the setup, and then I'd be the only one with the binary ... each new person with this need would have to build their own.

Since I see that there is a build process for the binaries on the web-install page, the lilygo-rtl_433 binary with the PUBLISH_UNPARSED flag should be available for everyone.

**Comment by 1technophile** [comment]
Good catch. I think we should enable this as a runtime setting
