### ISSUE TITLE
ZgatewayBT:78: error: 'class BLEAdvertisedDevice' has no member named 'haveServiceData'

### ISSUE THREAD

**Issue by rolfberkenbosch** [1technophile/OpenMQTTGateway#159]
I get an errror with by ESP32 with BLE support when i verify the code in arduino. How can I fix this ?

Documents\Arduino\OpenMQTTGateway\ZgatewayBT.ino: In member function 'virtual void MyAdvertisedDeviceCallbacks::onResult(BLEAdvertisedDevice)':

ZgatewayBT:78: error: 'class BLEAdvertisedDevice' has no member named 'haveServiceData'

             if (advertisedDevice.haveServiceData()){

                                  ^

ZgatewayBT:80: error: 'class BLEAdvertisedDevice' has no member named 'getServiceData'

                 std::string serviceData = advertisedDevice.getServiceData();

                                                            ^

ZgatewayBT:94: error: 'class BLEAdvertisedDevice' has no member named 'getServiceDataUUID'

                 BLEUUID serviceDataUUID = advertisedDevice.getServiceDataUUID();

                                                            ^

**Comment by 1technophile** [comment]
I close the issue, reopen it if you need

**Comment by delta010** [comment]
I am using esp32 I have the same error,  what should I do

**Comment by 1technophile** [comment]
This is surely linked to a bad library version, you should use the versions linked here:
https://github.com/1technophile/OpenMQTTGateway/blob/e4de45f2194fa1fe30b2f4e51d6acdc1925802be/platformio.ini#L54
