### ISSUE TITLE
Heltec ESP32 LoRa SX1278 V3 supported, too?

### ISSUE THREAD

**Issue by sheilbronn** [1technophile/OpenMQTTGateway#1619]
After reading about the success OpenMQTTGateway on the Heltec ESP32 LoRa SX1278 *V2* I decided to get one, but accidentally bought a Heltec ESP32 LoRa ~~SX1278~~ SX1262 *V3* (offered as: ["SX1278 ESP32 LoRa IoT Internet of WIFI Bluetooth-compatible Development Board 433mhz for Arduino 0.96 Inch OLED Digital Display"](https://www.aliexpress.com/item/1005004645530908.html)). Now, I'm wondering whether this version is supported, too?!

According to the picture on AliExpress the PIN layout is a little different as can be seen on the 6th picture of the website

Did anybody get OpenMQTTGateway top run on this board? If yes, are there docs for this? Thanks?

**Comment by NorthernMan54** [comment]
As long as the lora chipset is SX1278 you should be fine.  Looking at the pictures it appears to be a clone of the V2 board.

**Comment by sheilbronn** [comment]
The pictures showing the PIN layouts show differences in the layout of V2 and V3 - wouldn't that make a difference?

- V2: https://community.hiveeyes.org/t/heltec-wifi-lora-32/3125
![eda042713108809e3511e822a1aa4e582ee70ebc](https://user-images.githubusercontent.com/36453088/235234010-4b5bd1f3-f843-4300-9154-7f3c3a575d47.png)


- V3: (attached)
![WB32LA(F)_V3](https://user-images.githubusercontent.com/36453088/235233799-7fe6544b-dfb1-488e-bc08-7a8dd7352aff.png)


(Both V2 and V3 seem to be available for 433 Mhz and 868 MHz. Frequency doesn't seem to matter for the PIN layout.)

BTW: There is also issue https://github.com/1technophile/OpenMQTTGateway/issues/1436

**Comment by sheilbronn** [comment]
According to https://github.com/NorthernMan54/rtl_433_ESP/issues/82 and https://heltec.org/project/wifi-lora-32-v3/
 there are be more differences such as ESP32-D0 vs ESP32-S3 and SX1276 vs. SX1262:
 
![diff_V2_V3](https://user-images.githubusercontent.com/36453088/235242869-5ed10d3d-08b0-4585-94fe-35d54e699bc9.png)

**Comment by ryan-makes-it** [comment]
I also ended up with a 915mhz WiFi LoRa 32 v3 with the sx1262 chip. I was hoping to use it to listen to Ecowhitt soil moisture sensors (https://www.ecowitt.com/shop/goodsDetail/19), as using a RTL usb radio set up as a mqtt bridge with home assistant works well with them. 

I'm happy to test any code updates on my v3 if that would assist in development, or help source one for the project developers?

**Comment by luis-n4489** [comment]
Is there any effort into this? I bought a couple of these thinking its compatible and now.. well i can't return them lol

**Comment by NorthernMan54** [comment]
If the chipset on the board is sx127x, it is supported

If the board does not have this chipset, it can still be used as a BLE receiver.

pls note that the sx126x chipset will never be supported, as it does not support direct mode.

**Comment by victorserbu2709** [comment]
Heltec v4 works with https://github.com/1technophile/OpenMQTTGateway/pull/2339
