### ISSUE TITLE
MQTT blasted with  {"id": "78:D8:84:8B:8D:87", "rssi": -96, "brand": "Apple", "model": "Apple Continuity", "model_id": "APPLE_CONT", "device": "Apple device", "mfr": "Apple, Inc."}

### ISSUE THREAD

**Issue by sainio** [1technophile/OpenMQTTGateway#1628]
After some update my MQTT is filled with Apple Continuity topics, but I have no Apple devices.  How to stop?

**Comment by DigiH** [comment]
Hi @sainio,

these Apple Continuity broadcasts are recognised to be filtered out by default. Can you make sure you have

`"randommacs":false`

in your BTtoMQTT setting?

Are you actually using OpenMQTTGateway or possibly [Theengs Gateway](https://github.com/theengs/gateway)?

With Theengs Gateway you need to make sure that you are using the latest version v1.0.0, which included

[Add APPLE_CONT and APPLE_CONTAT to default discovery filter](https://github.com/theengs/gateway/pull/123)
and
[[RMAC] Filter random mac devices](https://github.com/theengs/gateway/pull/128)

**Comment by sainio** [comment]
And where would that setting be?

**Comment by DigiH** [comment]
As tated above, you don't seem to be running OpemMQTTGateway at all, for which this setting would be applicable, but Theengs Gateway, as your quoted MQTT JSON in the title includes `"mfr": "Apple, Inc."`, which is unique to Theengs Gateway.

Are you possibly using the Theengs Gateway add-on for Home Assistant?

If so, the above suggestion to update to the latest version 1.0.0. should remedy the issue you are experiencing.

If not, you should log an issue against [Theengs Gateway.](https://github.com/theengs/gateway)
