### ISSUE TITLE
More recommended brokers

### ISSUE THREAD

**Issue by tigercl** [1technophile/OpenMQTTGateway#1633]
Hi, I saw that you listed some recommended brokers in `docs/prerequisites/broker.md`, such as Mosquitto and HiveMQ.

I hope we can add [EMQX](https://github.com/emqx/emqx) to this list. EMQX is also a very popular open source MQTT Broker. It provides full MQTT 3.1.1 and MQTT 5.0 support, and has excellent performance and stability. I think this can help many users.

Looking forward to your reply.😄

**Comment by 1technophile** [comment]
Hello,

For sure, feel free to share the logo or submit a PR :-)

**Comment by 1technophile** [comment]
Done
