### ISSUE TITLE
String handling improvment

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#164]
Following this discussion improve string handling on the projects
https://github.com/1technophile/OpenMQTTGateway/pull/154

And multiply trc functions with different signature to avoid use of string into trc argument

**Comment by broekema** [comment]
Thinking about this, we could probably generalize the publishing of messages into a global function or method used by all other code. In this function we can then differentiate between Uno and ESP targets, but only once and at a well defined central location.

**Comment by 1technophile** [comment]
Great idea !

**Comment by posicat** [comment]
This is where a JSON library could come in handy, might want to evaluate that and this topic together as one change.

**Comment by 1technophile** [comment]
Good point @posicat, we might first try to include json publishing before or in the same time of  that

**Comment by broekema** [comment]
I've create pull request #168 for discussion. This is a class based sensor refactor, that centralizes publishing of messages.

**Comment by 1technophile** [comment]
Implemented arduinolog for traces, and centralized pub functions
