### ISSUE TITLE
Experience with Mi Band 7?

### ISSUE THREAD

**Issue by tomcat-xx** [1technophile/OpenMQTTGateway#1642]
Not really a bug ...

Anyone having experience with Mi Band 7? Advertisement is received and published via MQTT, but "steps" are missing. I used different band in the past and all worked.

**Comment by DigiH** [comment]
Hi @tomcat-xx,

Could you post the advertisements received by MQTT, and have you also made sure that the following two options are enabled in the Zepp Life app? 

Discoverable - for steps sharing
Acticity heart rate sharing - well … ;)

![image](https://github.com/1technophile/OpenMQTTGateway/assets/17110652/b19691dc-2fbf-4660-a553-37a93e2f1075)

and could you also share your BTtoMQTT output? Especially the setting for **"intervalacts"**, as the servicedata, which contains the encoded data for the steps, is only available when the Mi Band is actively scanned, so the steps might only show up every intervalacts ms.

**Comment by tomcat-xx** [comment]
Hi @DigiH,

Thanks for pointing out different settings. The one about heart rate I did not know before. Not sure if it was in the old app (before ZEPP) when I setup my Band 4. I'm only using original app for first setup. Same in this case for the Band 7 and then only activated "Discoverable". That is also only thing that is activated for the Band 4 (still in use). I think without that setting, I would not get any data (brand, model, name, ... is received from Band 7).  

intervalacts is set to 55555, but that is not related to device. So when getting steps for the Band 4 I should also get for Band 7.

Rest I have to add later, when Band 7 "is back from vacation" ;-)

Thomas

**Comment by DigiH** [comment]
> Rest I have to add later, when Band 7 "is back from vacation" ;-)

When back from vacation you should also turn on [showing advertisement and advanced data](https://docs.openmqttgateway.com/use/ble.html#advanced-advertisement-and-advanced-data-default-false) on your gateway so we can see what data the Mi Band 7 transmits and why it is not being decoded and how to add it to the decoder.

Thanks

**Comment by DigiH** [comment]
Hi @tomcat-xx,

Just wondered if you had any more chance to test with the Mi Band 7?

Thanks

**Comment by tomcat-xx** [comment]
Sorry for late reply. Mi Band 7 (my daughter ;-) ) was back over weekend, but then I was on vacation. I did some tests but did not post it here so far.

Unfortunately it does not look good for me. 

Without changes (just "Discoverable" on) I got:

{
  "id": "11:22:33:44:55:66", 
  "name": "Xiaomi Smart Band 7 5566",
  "rssi": -90,
  "brand": "Xiaomi/Amazfit",
  "model": "Mi Band/Smart Watch",
  "model_id": "MB/SW"
}

With heart rate on then: 
{
  "id": "11:22:33:44:55:66",
  "name": "Xiaomi Smart Band 7 5566",
  "rssi": -75,
  "brand": "Xiaomi/Amazfit",
  "model": "Mi Band/Smart Watch",
  "model_id": "MB/SW",
  "act_bpm": 73
}

And with "showing advertisement and advanced data" then: 
{
  "id": "11:22:33:44:55:66",
  "mac_type": 1,
  "adv_type": 0,
  "name": "Xiaomi Smart Band 7 5566",
  "manufacturerdata": "570102ffffffffffffffffffffffffffffffff03112233445566",
  "rssi": -63,
  "brand": "Xiaomi/Amazfit",
  "model": "Mi Band/Smart Watch",
  "model_id": "MB/SW",
  "type": "BODY",
  "acts": true
}

Plus heart rate
{
  "id": "11:22:33:44:55:66",
  "mac_type": 1,
  "adv_type": 0,
  "manufacturerdata": "570102020149ffffffffffffffffffffffffff02112233445566",
  "rssi": -84,
  "brand": "Xiaomi/Amazfit",
  "model": "Mi Band/Smart Watch",
  "model_id": "MB/SW",
  "type": "BODY",
  "acts": true,
  "act_bpm": 73
}

It looks as if heart rate is visible in manufacturerdata, but for different step counts I could not see changes there.

All looks very similar to my Band 4, juts there is additional "steps".

**Comment by DigiH** [comment]
Thanks @tomcat-xx,

Everything does indeed look identical to previous Mi Band 4-6. For the steps, which are encoded in the servicedata, not manufacturerdata like the activity-heart rate, active scanning is required.

Can you have a look at your **intervalacts** setting in the **BTtoMQTT** message. With that active scan interval (ms) you should also get the servicedata and the encoded steps information of your Mi Band 7. If you could catch a message with this servicedata and "showing advertisement and advanced data" set to true.

**Comment by tomcat-xx** [comment]
The band is not here at the moment, but my own one ordered now.

What I'm wondering: After your reply I looked into logs I recorded. For the Band 4 there is indeed "servicedata" (and also "servicedatauuid"). Did not realize that before. So it should be also there for the Band 7 because for both logs were recorded at same time. But let's see when a Band 7 will be always here ;-) and I have more time to check.

(Intervalacts is set to 55555 as written above.)

By the way, getting step is just a funny option. More important is using the Bands for presence detection in home automation. So even without steps it is very useful.

**Comment by tomcat-xx** [comment]
Now I have it. But even after one hour no difference. Same as stated above: For the Band 4 (and other devices) I'm getting "servicedata" and "servicedatauuid" (after a minute or so), but nothing for the Band 7.

**Comment by DigiH** [comment]
Could it be that there is a slightly different setting to **Discoverable ON** for the Mi Band 7 in its settings of the Zepp Life app? 

For all the Mi Bands 4-6 this is the setting which makes them _visible to nearby devices_ and broadcasts the "servicedata" and "servicedatauuid" with the steps information. 

I'm wondering if this has been changed for the Mi Band  7 and if there might be an additional steps sharing option.

If you turn the **Discoverable** option OFF and ON again you should get a message about agreeing to then share the bluetooth address and steps of your Mi Band.

**Comment by tomcat-xx** [comment]
Settings page in Zepp Life app looks the same. There is also message about bluetooth address AND steps, when turning discoverable on. Band is also not visible (to OMG and BLE monitor app) with "off". With "on" all is published what I posted above, but no servicedata/servicedatauuid.

**Comment by DigiH** [comment]
Hmm, very strange, as there really is not really enough bytes left to have the steps encoded there, as you have nicely shown with your masked MAC address, which is also contained in the manufacturerdata.

If the servicedata would have a different length for Mi Band 7 it would not be recognised by the current decoder, but as you say, there is no servicedata and servicedatauuid at all :(

Could you scan your Mi Band 7 for a while with the nRF Connect app on your phone, just to see if any servicedata does show up there, which for whatever peculiar reason we might not pick up?

Other than that I really don't know what could be the issue, as everything you have tried and done so far points to an expected similar behaviour as Mi band 4-6. 

With the now new Mi Band 8 I am wondering what will be the next issue ;)

**Comment by tomcat-xx** [comment]
nRF Connect also does not show service data. But shows, both bands are advertising 55 byte. 7 of it are used for service data (type 0x16) on Band4. On Band 7 all 55 are used for other types.

**Comment by elchitico** [comment]
Good morning, I just bought my band 7 and I'm having the problems described here. I have activated the options in zeeplife for bpm and steps, but only the bpm data is displayed.
openmqttgateway version 1.6

**Comment by DigiH** [comment]
Hi @elchitico 

This seems to be the issue with the Mi Band 7, that the steps are not freely transmitted in the **servicedata** any longer, whereas the activity bpm are still in the **manufacturerdata** when an activity is ongoing.

If you want to test and verify this further, could you also activate [showing advertisement and advanced data](https://docs.openmqttgateway.com/use/ble.html#advanced-advertisement-and-advanced-data-default-false), to see if you do catch any servicedata, or possibly different manufacturerdata, at all.

The best application to monitor the broadcasts over a period of time is [MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5) with its history.

Could you also check in the Zepp Life app if there might be a firmware update available for the Mi Band 7?

**Comment by elchitico** [comment]
> Hi @elchitico
> 
> This seems to be the issue with the Mi Band 7, that the steps are not freely transmitted in the **servicedata** any longer, whereas the activity bpm are still in the **manufacturerdata** when an activity is ongoing.
> 
> If you want to test and verify this further, could you also activate [showing advertisement and advanced data](https://docs.openmqttgateway.com/use/ble.html#advanced-advertisement-and-advanced-data-default-false), to see if you do catch any servicedata, or possibly different manufacturerdata, at all.
> 
> The best application to monitor the broadcasts over a period of time is [MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5) with its history.
> 
> Could you also check in the Zepp Life app if there might be a firmware update available for the Mi Band 7?

My band 7 was updated to the same link with zeeplife, it is in the latest version.
I use mqtt explorer, but there is no service data steps.
I try to activate the advanced data mode to see if I can see any more service data.
But from what you told me, you have to be aware that you will not be able to see the step data in the successive mi band, am I right?
thank you very much for your collaboration

**Comment by DigiH** [comment]
Correct, it looks as if the Mi Band 7 does not share its steps data freely any longer, as all the Mi Bands 4-6 (at least from my experience, might have already stated earlier) did, unless there might be a new different setting which needs activating, or a privacy setting which might need deactivating.

As no one in our team has a Mi Band 7 we rely on feedback from users like yourself and tomcat-xx, so thank you both for your collaboration.

**Comment by tomcat-xx** [comment]
Update from my side: I reported issues to Xiaomi (at least message in app about steps is wrong). They requested to use Mi Fitness App instead. Since I had to switch from Mi Fit to ZEPP Life not that long ago, I did not even know that there is new/alternative app. Was sceptic about result anyway. And yes, is the same, same options to activate and same result. Reported back and waiting for feedback.

**Comment by elchitico** [comment]
> Update from my side: I reported issues to Xiaomi (at least message in app about steps is wrong). They requested to use Mi Fitness App instead. Since I had to switch from Mi Fit to ZEPP Life not that long ago, I did not even know that there is new/alternative app. Was sceptic about result anyway. And yes, is the same, same options to activate and same result. Reported back and waiting for feedback.

I just installed the app you mention, My Fitness and I see that only the option to share bpm appears, no option appears for the steps

**Comment by tomcat-xx** [comment]
Short update: As expected (at least by me) Mi Fitness App did not change anything. After reporting that back, I was asked to send my Band to repair it ;-) Now again wrote back ...

@elchitico: There is an was no separate switch for steps (in all apps), it was just send when "discoverable" is switched on.

**Comment by DigiH** [comment]
Thanks for the update @tomcat-xx 

Let's hope that with a future firmware update the Mi Band 7 will show the steps again in its broadcast servicedata when Discoverable is turned ON.

**Comment by michi1972-dev** [comment]
I have the same problem. No steps get transfered freely. Must be a Xiaomi Band 7 firmware issue. Any idea?

**Comment by michi1972-dev** [comment]
Why is this issue closed? It is still a problem.

**Comment by DigiH** [comment]
> Why is this issue closed? It is still a problem.

Because this seems to be the status quo for the Mi Band 7 and possibly onwards - that the steps are no longer freely broadcast in the advertising data, therefore currently not receivable nor decodable with Theengs Decoder for OpenMQTTGateway.

**Comment by michi1972-dev** [comment]
Got it. Thank you!
