### ISSUE TITLE
platformio.ini missing board

### ISSUE THREAD

**Issue by PricelessToolkit** [1technophile/OpenMQTTGateway#1653]
"TTGO LILYGO LORA 32 433mhz with OLED display V2" are supported for LoRa
[Link](https://compatible.openmqttgateway.com/index.php/boards/?415_product_cat%5B0%5D=200&415_orderby=option_2&415_device=laptop&415_filtered=true)
 but missing in the file "platformio.ini"

**Comment by 1technophile** [comment]
Environments have been moved to `environments.ini`
https://github.com/1technophile/OpenMQTTGateway/blob/7df72f6983bfa07d7840eb57a347d9daf9b4e903/environments.ini#L778

**Comment by PricelessToolkit** [comment]
Thanks, so I need to define the board in "environments.ini" and don't touch platformio.ini. ?

**Comment by 1technophile** [comment]
My advice is to create a separate prod_env.ini (in the same folder as the others) and have your private environments reside in it.

**Comment by PricelessToolkit** [comment]
thanks!!

**Comment by 1technophile** [comment]
Let me know if you have other questions
