### ISSUE TITLE
Flash (web) on Linux Mint with Chrome

### ISSUE THREAD

**Issue by jerome6994** [1technophile/OpenMQTTGateway#1659]
Good morning
I come to ask a question in order to help me flash an esp32 on chrome for BLE presence on Home Assistant.
I am on Linux Mint recently and by connecting the ESP32 to the computer I do not see the ESP on a serial port by clicking on Install!
I see ttys0, ttys1 ttysX...... but never ttyUSB0 while I have it on my terminal
![image](https://github.com/1technophile/OpenMQTTGateway/assets/66921143/0c33a680-cbdc-48d1-b82f-17869c9483f5)
I don't see where it can come from!
![image](https://github.com/1technophile/OpenMQTTGateway/assets/66921143/b932b5dd-74be-48cd-8e19-5f5d8915c354)
Thanks

**Comment by ColinShorts** [comment]
You might not be part of the dialup group, check with `groups` (run as your
normal user without sudo). You can check the group ownership of the device
node with `ls -l /dev/ttyUSB*`.

Should be as simple as `sudo gpasswd -a <username> dialup`, then logout and
log back in again.

**Comment by jerome6994** [comment]
Good morning
Thanks for the help I actually did an ls -l /dev/ttyUSB* and I didn't have access!
I did :
```
ls -l /dev/ttyUSB0 --> Failed
sudo adduser <USER> dialout
sudo usermod -a -G dialout <USER>
sudo reboot
ls -l /dev/ttyUSB0 --> OK
```
