### ISSUE TITLE
M5core2 + lora 433 mhz module?

### ISSUE THREAD

**Issue by Koekebeest** [1technophile/OpenMQTTGateway#1683]
Is it possible to run this on a m5stack core 2 with a 433mhz lora module on it?

**Comment by 1technophile** [comment]
Which gateway would you like to run, RTL_433 or LORA ?

**Comment by Koekebeest** [comment]
I was thinking of using the Lora module to receive and transmit because the m5core2 isn't able to do that on its own? So I guess, the Lora gateway.

**Comment by 1technophile** [comment]
LORA modules can also be used for 433Mhz reception of FSK and OOK modulation, hence my question.

I haven't tested this module with LORA but on paper it should work

**Comment by Koekebeest** [comment]
Cool, interesting to see if it will work. Going to order it next week. Will keep you updated
Thanks

**Comment by 1technophile** [comment]
Feel free to open a topic in https://community.openmqttgateway.com/ , closing the issue
