### ISSUE TITLE
Missing Environments on  (Option 1) Upload from the web

### ISSUE THREAD

**Issue by usernamegeneratorFTW** [1technophile/OpenMQTTGateway#1684]
**Describe the bug**
On the https://docs.openmqttgateway.com/upload/web-install.html  website there are 67 Environments/ Boards listed in the table which are available via web flash. however, in the dropdown list i only count 62, which means that 5 are missing.
Among the missing boards is the lolin_c3_mini board which I am trying to get running, but fail because no AP is visible after the flash.
To eliminate me as a source of error for this it would be great if the lolin_c3_mini would be flashable on the web.

**Comment by 1technophile** [comment]
Fixed, you should have it in the development builds tomorrow:
https://docs.openmqttgateway.com/dev/

**Comment by usernamegeneratorFTW** [comment]
thank you very much
