### ISSUE TITLE
WiFi not connecting after upgrade to 1.6.0

### ISSUE THREAD

**Issue by jpmorrison** [1technophile/OpenMQTTGateway#1689]
ESP32 running 1.5.1 connects to SSID on any channel. I have two APs, set to non overlapping channels 1 and 11.

After upgrading to 1.6.0 and configuring SSID through the captive portal it connects to AP on channel 1. When I move the ESP32 to a new location it will not connect to WiFi on the AP set to channel 11.

Workaround: on the second AP I changed it to channel 1 and it can connect. This wasn't needed in 1.5.1. OMG should be able to connect to an SSID on any available channel.

**Comment by 1technophile** [comment]
This is strange. I don't see what could have been changed between those two versions causing a change in Wifi connection behavior.
Note that if it was between v1.4.0 and v1.5.1 there was an update of the platform.

Which environment are you using, and what are your routers models?

**Comment by jpmorrison** [comment]
It was working with 1.5.1 esp32dev-multi_receiver. I was unable to run 1.6.0 multi_receiver due to a boot loop but esp32dev-multi_receiver boots. These are release binaries, I didn't compile them myself - is that what you mean by environment?

With 1.6 it kept reverting to wifi setup/captive portal mode until I changed the rf channel.
It's like it remembers the channel it was setup on and won't scan/roam to the other channel.

WiFi AP is a Cisco - I had to change to channel 1 when I moved it downstairs. The other wifi is Technicolor /CommScope according to the Cable company.  Both are 2.4GHz g/n, 20 Mhz, WPA2-PSK/AES.

**Comment by slysiou** [comment]
I also get a boot loop with 1.6 esp32dev-multi_receiver (direct flash from web or compiled with PlatformIO). 
Anyone with the same experience ? 

```
ELF file SHA256: 4e2584206ae5a1c6

E (727) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
Guru Meditation Error: Core  0 panic'ed (LoadStoreError). Exception was unhandled.

Core  0 register dump:
PC      : 0x4012c2ac  PS      : 0x00060930  A0      : 0x80132c50  A1      : 0x3ffe3b40  
A2      : 0x3f41bd88  A3      : 0x3f423ffc  A4      : 0x0000000c  A5      : 0x00060f23  
A6      : 0x00060f20  A7      : 0x00000001  A8      : 0x8012c2ac  A9      : 0x3ffe3b20  
A10     : 0x3ffbab44  A11     : 0xfffc1fff  A12     : 0x00060f20  A13     : 0x00060f23  
A14     : 0x007bed94  A15     : 0x003fffff  SAR     : 0x00000018  EXCCAUSE: 0x00000003  
EXCVADDR: 0x3f41bd88  LBEG    : 0x4008aa1d  LEND    : 0x4008aa2d  LCOUNT  : 0xfffffffe  


Backtrace: 0x4012c2a9:0x3ffe3b40 0x40132c4d:0x3ffe3b60 0x4012c25c:0x3ffe3b80 0x4012a8f2:0x3ffe3ba0 0x4012acbd:0x3ffe3bc0 0x400e302d:0x3ffe3be0 0x4014a787:0x3ffe3c10 0x40083206:0x3ffe3c40 0x40079266:0x3ffe3c90 |<-CORRUPTED


```

**Comment by franki29** [comment]
Hi, I have same problem too.
Using a older version it is working
Br. Frank

**Comment by ilgrank** [comment]
Any update on the matter  @franki29   @jpmorrison   @slysiou ?

**Comment by franki29** [comment]
I am using now OMG_rtl_433_ESP , this works without problem
