### ISSUE TITLE
Sonoff RF bridge reconnect frequently 

### ISSUE THREAD

**Issue by mizrachiran** [1technophile/OpenMQTTGateway#169]
Hi,

I'm using the latest version on a Sonoff RF Bridge. 
It works great but it seems like it reconnect once in ~20 minutes. (I see offline and online messages sent over LWT topic).

Why is that happening? 

![image](https://user-images.githubusercontent.com/617155/35624287-3dfbeef0-0697-11e8-925a-234873420dd3.png)

**Comment by mizrachiran** [comment]
just noticed on my MQTT server (Mosquitto) the following logs:

"Socket error on client OpenMQTTGateway"

**Comment by 1technophile** [comment]
Are you sure you don't have another OpenMQTTGateway with the same name on the same network?
If not please try with the last master version

**Comment by mizrachiran** [comment]
I have only 1 OpenMQTTGateway installed.

**Comment by mizrachiran** [comment]
I am using the latest version

**Comment by 1technophile** [comment]
Did you updated your broker version ?  Which one are you using

**Comment by mizrachiran** [comment]
i'm using v1.0.

**Comment by 1technophile** [comment]
If you are using mosquitto you should update it

**Comment by mizrachiran** [comment]
OK. I will give it a try.
Closing this thread for now.


Thanks!
