### ISSUE TITLE
INA226 incorrect JSON output

### ISSUE THREAD

**Issue by murfy76** [1technophile/OpenMQTTGateway#1691]
Hello,

JSON output from INA226 sensor is incorrect. Output contain space before values, e.g.:  {"volt": 3.3,...} and it should be {"volt":3.3,...} (without space before value). 

My workaround is to modify "ZsensorINA226.ino" to:
...   
//char volt_c[7];
//char current_c[7];
//char power_c[7];
//dtostrf(volt, 6, 3, volt_c);
//dtostrf(current, 6, 3, current_c);
//dtostrf(power, 6, 3, power_c);
INA226data["volt"] = (float)volt;
INA226data["current"] = (float)current;
INA226data["power"] = (float)power;
...

1. Publish INA226 to MQTT with JSON
2. Use Telegraf "mqtt_consumer" with json output to influxdb to read this topic 
3. InfluxDB/Grafana will be not able to read/graph this data

**Expected behavior**
Valid JSON output format like other sensors.

Thank you. 

Peter

**Comment by 1technophile** [comment]
Hello,

Feel free to submit a PR

**Comment by NorbertHD** [comment]
Or set the 2. parameter of dtostrf() to 0, then no leading or trailing spaces are generated.

e.g. dtostrf(volt, 0, 3, volt_c);
