### ISSUE TITLE
LilyGo ESP32-S3 T-Display

### ISSUE THREAD

**Issue by slatif60** [1technophile/OpenMQTTGateway#1708]
I am new to ESP32-S3. I have connected with Arduino IDE but getting following error message when I try to run the example wifi scan
"Sketch uses 638253 bytes (20%) of program storage space. Maximum is 3145728 bytes.
Global variables use 42676 bytes (13%) of dynamic memory, leaving 285004 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.5.1
Serial port COM1
Connecting......................................

A fatal error occurred: Failed to connect to ESP32-S3: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Failed uploading: uploading error: exit status 2 "
Can someone guide me how to fix it.

**Comment by NorthernMan54** [comment]
You like need a serial port driver for your board.  Take a look at the manufacturer web site, they should have instructions
