### ISSUE TITLE
user_config.h entirely ignored

### ISSUE THREAD

**Issue by Dan2705** [1technophile/OpenMQTTGateway#171]
Dear Community,
I noted some "interesting" behavior and would highly appreciate a pointer

Fresh setup with minimal changes to user_config.h (only set wifi password, enabled rf gateway and set IP address for MQTT broker), however, my settings are entirely ignored.

It still shows a 192.168.*.* IP address although it has been obviously changed. 
Did anybody experienced sth similar in the past? Where does the MQTT broker IP address come from? There is no mentioning of 192 in the files at all.

Super confused.

<img width="964" alt="2018-02-03_152322" src="https://user-images.githubusercontent.com/36047012/35765007-8d4eae28-08f6-11e8-990a-d16f9e40aa98.png">
<img width="749" alt="2018-02-03_153127" src="https://user-images.githubusercontent.com/36047012/35765037-604cb856-08f7-11e8-837b-f005904c76ad.png">

Dan

**Comment by 1technophile** [comment]
Yes uncomment espwifimanualsetup if you want to user manual configuration and not wifi manager

**Comment by Dan2705** [comment]
Uff... I could have saved a hell of time by taking the right code version. As a new user to GitHub, clicking the download button on the landing page was the most obvious thing.'
Thanks a lot for pointing out! Actually, I did not even had to uncomment "# define espwifimanualsetup" - it worked out of the box. Thanks again! Great project - cannot wait to get it fully working in my environment
