### ISSUE TITLE
[Feature] Discovery subpath

### ISSUE THREAD

**Issue by nikito7** [1technophile/OpenMQTTGateway#1710]
Discovery topic should have a /

![Screenshot](https://github.com/1technophile/OpenMQTTGateway/assets/45373783/0b6cf1af-c6ce-4b63-8e36-dc05e3f28160)

**Comment by 1technophile** [comment]
Could you detail the problem that you have with the current implementation ?

**Comment by nikito7** [comment]
It's just Visual.
It work ok.

**Comment by nikito7** [comment]
Just as example:

```
"homeassistant/sensor/${id}/${devx}/config" 
```

**Comment by 1technophile** [comment]
Not planning to change this for visual purposes as it would impact all the existing users.

**Comment by nikito7** [comment]
Yes, I know...
