### ISSUE TITLE
Using Widora Air (ESP32) - Can't compile with BLE turned on in config.

### ISSUE THREAD

**Issue by NeoMatrixJR** [1technophile/OpenMQTTGateway#172]
* OpenMQTTGateway version used MASTER
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library) - CURRENT BLUETOOTH LIBRARY - did mods listed on wiki

is this normal to have so many multiple definitions?  I can't get it to compile.

compile log: - [Updated to verbose messages and moved to pastebin](https://pastebin.com/Bfj3zUiZ)

**Comment by 1technophile** [comment]
I relaunched a build to see if esp32 env update makes the build broken, you can follow the result here:
https://travis-ci.org/1technophile/OpenMQTTGateway/jobs/336738178

if it is ok, your issue is most likely due to a bad component version

**Comment by 1technophile** [comment]
the components used for this build can be found here:
https://github.com/1technophile/OpenMQTTGateway/blob/master/.travis.yml

**Comment by 1technophile** [comment]
Indeed the link given in the library folder is not good the last version of ESP32_BLE_Arduino doesn't compile, I confirm that you can take this one and it compile:
https://github.com/nkolban/ESP32_BLE_Arduino/archive/f8fe9d7cdfb20caa54b70849826d1ac6e375ff78.zip

**Comment by NeoMatrixJR** [comment]
@1technophile - I grabbed that last zip you posted and dropped it in place.  Do I still need to modify the files with the ones on the wiki?  Just straight dropping in the zip produced this:
[Recompile pastebin with new zip](https://pastebin.com/v31JRQ1Z)

**Comment by 1technophile** [comment]
Yes you have to overwrite the 2 files

**Comment by NeoMatrixJR** [comment]
works!
