### ISSUE TITLE
le coded phy 125 esp32c3 

### ISSUE THREAD

**Issue by moroz55555** [1technophile/OpenMQTTGateway#1732]
HI
how about support le coded phy 125 ?

**Comment by 1technophile** [comment]
Do you have a BLE device that supports coded PHY in hand?

**Comment by moroz55555** [comment]
Yes. These are the devices https://inplay-tech.com/in100

**Comment by 1technophile** [comment]
That's more a chipset than a device, we would need devices with this chipset or another to implement it, and several users requesting it.

**Comment by jhoogeboom** [comment]
This supports coded PHY and would be very interesting to get working https://github.com/pvvx/ATC_MiThermometer
