### ISSUE TITLE
NVS error and can't save settings

### ISSUE THREAD

**Issue by tiit12** [1technophile/OpenMQTTGateway#1734]
HI

I have ESP32 WT32-ETH01 module and struggle with latest firmware -- I can change the settings, but they aren't saved. 
I see from logs:

begin(): nvs_open failed: NOT_FOUND
N: No WebUI config to load

I tried older version (1.5.6) and that one seems to work with NVS (no errors in log).

Thanks..

Tiit

**Comment by 1technophile** [comment]
Hello,

Did you try to erase the flash ? If yes with which tool?

With prior versions the webUI was not available so this is why you are not encountering the `N: No WebUI config to load`

**Comment by tiit12** [comment]
I installed through web installer and checked Erase flash. Tried also with ESP tool and separate files -- same situation.

Tiit

**Comment by 1technophile** [comment]
Which environment are you using ?

**Comment by tiit12** [comment]
Also from logs:

` N: [WebUI] MQTTtoSYS {"mqtt_server":"192.168.*.*","mqtt_port":"1883","mqtt_user":"****","mqtt_pass":"****","mqtt_secure":false,"gateway_name":"OMG_ESP32_WT32-ETH01","mqtt_topic":"home/"}
     [ 45310][E][vfs_api.cpp:24] open(): File system is not mounted
E: failed to open config file for writing
`

**Comment by tiit12** [comment]
Windows 11 and browser is Edge. ESP tool is version 3.9.5.

**Comment by 1technophile** [comment]
By the way there is a template for bug report

**Comment by tiit12** [comment]
A .. ok .. sorry for that :)

**Comment by 1technophile** [comment]
Could you share the platformio configuration or environment used ?

**Comment by tiit12** [comment]
Actually I did it from your web page :

![image](https://github.com/1technophile/OpenMQTTGateway/assets/78739968/32bf2b3a-cd6a-4f9a-9e20-ce9d06f47dbe)

**Comment by tiit12** [comment]
I did now fresh compile from gitpod -- same result:

![image](https://github.com/1technophile/OpenMQTTGateway/assets/78739968/12777027-913b-4704-8fa8-05f3fd6f9999)



`
N: OpenMQTTGateway URL: http://0.0.0.0/
N: ZwebUI setup                                           done
[  2950][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
N: SYS config not found
[  4464][E][Preferences.cpp:50] begin(): nvs_open failed:                                           NOT_FOUND
N: BT config not found
`

**Comment by 1technophile** [comment]
Do you have a link to your board ?

**Comment by tiit12** [comment]
https://www.cnx-software.com/2020/11/09/6-wt32-eth01-is-a-tiny-esp32-board-with-ethernet/

It is described also on PlatformIO wiki:

https://docs.platformio.org/en/latest/boards/espressif32/wt32-eth01.html

I hope that helps.

**Comment by tiit12** [comment]
I tried Tasmota on that board and Tasmota works (flash is detected and usable).

**Comment by 1technophile** [comment]
Which settings are you trying to change that are not saved ?

**Comment by tiit12** [comment]
MQTT server settings actually, but also WIFI settings .. everything that needs save to NVS -- I see from logs, that filesystem is not mounted and settings can't save. After reboot is everything default.
