### ISSUE TITLE
Unable to access web UI

### ISSUE THREAD

**Issue by chrismox** [1technophile/OpenMQTTGateway#1753]
**Describe the bug**
Unable to access the web UI.
A new installation of nodemcuv2-rf on a WEMOS D1 mini ESP8266.

**To Reproduce**
Browse to the IP address of the device, browser reports:
> This site can’t be reached
> 192.168.1.118 refused to connect.
> Try:
> - Checking the connection
> - Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED

**Environment (please complete the following information):**
* OpenMQTTGateway version used - 1.6.0

**Additional context**
I am able to connect to the web portal to set up wifi and MQTT details. The device then reconnects to the wifi and works correctly in every other sense. It is connected to MQTT and reports RF signals as expected.
Just the web UI remains inaccessible.
The same device used to work fine with a previous version of OpenMQTTGateway. I have tried reinstalling with no further success.

**Comment by gabter1** [comment]
I have the same problem with an ESP32 WROOM 32 development board. I made some tests, and the Web UI works fine with the esp32dev-ble firware, but it is not accessible with the eps32dev-rtl_433 firmware. I uploaded them both, unchanged, from the web page (Option1). I can set the Wifi settings, but after it connects to my home network (I checked, it is connecting fine with rtl_433, too), the UI is gone.

**Comment by 1technophile** [comment]
Could you connect a serial monitor and check the logs please ?

**Comment by gabter1** [comment]
I have no idea why, but it is working now. It might have been a connection issue to the CC1101 and because of that, the ESP32 did not fully initialize.

**Comment by chrismox** [comment]
Apologies for the delay, this is what my serial monitor sees:

*WM: [2] Added Parameter: server
*WM: [2] Added Parameter: port
*WM: [2] Added Parameter: user
*WM: [2] Added Parameter: pass
*WM: [2] Added Parameter: name
*WM: [3] Updated _max_params: 10
*WM: [3] re-allocating params bytes: 40
*WM: [2] Added Parameter: topic
{"mqtt_server":"192.168.1.222","mqtt_port":"1883","mqtt_user":"xxxx","mqtt_pass":"xxxx","mqtt_topic":"OpenMQTTGateway/","gateway_name":"9"}N: RF_EMITTER_GPIO: 3 
N: RF_RECEIVER_GPIO: 5 
N: Setup OpenMQTTGateway end
W: MQTT connection...
N: Connected to broker
N: Subject: /SYStoMQTT
N: Received json : {"uptime":1,"version":"v0.9.5","freemem":41184,"rssi":-63,"SSID":"xxxx","ip":"192.168.1.118","mac":"xx:xx:xx:xx:xx:xx","wifiprt":0,"modules":"R

**Comment by NorthernMan54** [comment]
There should be more logging, can you try collecting a log again?

**Comment by chrismox** [comment]
Apologies for the significant delay in getting back to you.

I have tried setting up another device to see if I can get better results, but I am still unable to connect to the web interface.

The serial log is as follows (with a few redactions):

  "mqtt_server": "192.168.1.222",
  "mqtt_port": "1883",
  "mqtt_user": "xxxx",
  "mqtt_pass": "xxxx",
  "mqtt_topic": "home/",
  "gateway_name": "OMG_ESP8266_RF",
  "mqtt_broker_secure": false,
  "mqtt_broker_cert": "",
  "mqtt_ss_index": 0,
  "ota_server_cert": "",
  "ota_pass": "OTAPASSWORD"
}*wm:[2] Added Parameter: server
*wm:[2] Added Parameter: port
*wm:[2] Added Parameter: user
*wm:[2] Added Parameter: pass
*wm:[2] Added Parameter: secure
*wm:[2] Added Parameter: cert
*wm:[2] Added Parameter: name
*wm:[2] Added Parameter: topic
*wm:[2] Added Parameter: ota
N: Attempting Wifi connection with saved AP: 0
N: RF_EMITTER_GPIO: 3 
N: RF_RECEIVER_GPIO: 0 
N: Switching to RF Receiver
N: OpenMQTTGateway modules: ["RF"]
N: ************** Setup OpenMQTTGateway end **************
W: MQTT connection...
N: Connected to broker
N: Send on /SYStoMQTT msg {"uptime":2,"version":"v1.6.0","discovery":true,"ohdiscovery":false,"env":"nodemcuv2-rf","freemem":33656,"mqttport":"1883","mqttsecure":false,"rssi":-64,"SSID":"xxxx","BSSID":"xxxx","ip":"192.168.1.119","mac":"xxxx","actRec":2,"modules":["RF"]}

**Comment by DigiH** [comment]
Hi @chrismox 

The WebUI is only available for ESP32 based pre-built binaries, not ESP8266

https://docs.openmqttgateway.com/use/webui.html#webui

> "modules":["RF"]

There is no WebUI module installed  on your gateway, so obviously you will not be able to access it.

**Comment by chrismox** [comment]
Ah, I hadn’t appreciated that, I assumed the webUI would be on all devices. Thanks for your help.
