### ISSUE TITLE
Home Assistant DHT Sensors wrong code

### ISSUE THREAD

**Issue by LucaAghemo** [1technophile/OpenMQTTGateway#176]
Just a small correction: 
in the Home Assistant integration section, talking about DHT sensors, the code to be included in configuration.yaml HA file has this line:

state_topic: "home/433toMQTT/dht1/temp" (or hum for humidity)

This is actually wrong, as DHT is not received by RF. Changing the line with:

state_topic: "home/DHTtoMQTT/dht1/temp" (or hum for humidity)

made it work properly for me.

**Comment by 1technophile** [comment]
thanks for the info, don't hesitate to correct it directly into the wiki

**Comment by Landrash** [comment]
Updated Wiki with relevant information.

**Comment by 1technophile** [comment]
I think this can be close,  if not you can reopen it
