### ISSUE TITLE
MQTT password limit to 60 characters ! and no option secure password with certificate

### ISSUE THREAD

**Issue by kwetnico** [1technophile/OpenMQTTGateway#1778]
Hi,

I am trying to configure my ESP (esp32 mini D1) which I flashed without problems with the esp32_ble firmware, however I encounter a problem connecting to my mosquitto server which tells me:
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/03ed4b27-6a8b-49fa-9e33-2840fc91f825)

but looking at the MQTT configuration of my ESP I see that part of the password is missing to connect to the MQTT network...
I use the plugin under jeedom MQTT Manager and it generates passwords with a length of 64 characters. I realize that the OMG interface is apparently limited to 60 characters because it truncates the last letters for me, therefore the user/password is not valid and I am refused connection to the MQTT network, could you increase this limitation?

Another point I would have liked to get around this problem by using secure MQTT but it is impossible to indicate my key I do not have the field (tested under Firefox and Chrome from a Windows 10 PC):
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/3be226df-4303-4e7e-8bcf-14a4da7ce127)

Thanks

(sorry google translate)
OMG version 1.6

**Comment by 1technophile** [comment]
Hello,

The development version has fixed this and will be available in the next release. You can test it below:
https://docs.openmqttgateway.com/dev/

**Comment by kwetnico** [comment]
> Hello,
> 
> The development version has fixed this and will be available in the next release. You can test it below: https://docs.openmqttgateway.com/dev/

Yes perfect with password thanks !
perfect it works no more character limitation for the password.

On the other hand if I want to use my certificate I do not have the possibility under the WebUI to integrate it there is no field
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/9594070c-9777-42b9-90a6-978dfc41c5be)

when are you going to release master ?

**Comment by 1technophile** [comment]
The certificates are available during onboarding if you reset/erase the esp32

**Comment by kwetnico** [comment]
Hi,
I would like to know if the fix has been passed to master? Or should I keep the DEV version on my ESP32?
THANKS

PS: I have another problem, my esp32s take my IP reservations from DHCP whenever they want... is this known? Isn't possible to force adress IP interface in the ESP32 openmqttgateway?

**Comment by 1technophile** [comment]
Hi,

> I would like to know if the fix has been passed to master? Or should I keep the DEV version on my ESP32?

It will be included in the next release, so you can keep the dev until

> PS: I have another problem, my esp32s take my IP reservations from DHCP whenever they want... is this known? Isn't possible to force adress IP interface in the ESP32 openmqttgateway?

This can be set in the code before building (not during runtime)

**Comment by kwetnico** [comment]
> Hi,
> 
> > I would like to know if the fix has been passed to master? Or should I keep the DEV version on my ESP32?
> 
> It will be included in the next release, so you can keep the dev until
> 
> > PS: I have another problem, my esp32s take my IP reservations from DHCP whenever they want... is this known? Isn't possible to force adress IP interface in the ESP32 openmqttgateway?
> 
> This can be set in the code before building (not during runtime)

Where specify  ip adress to esp? I don't see to enter ip static.. 

![OpenMQTTGateway_Wifi_Manager_enter_parameters b56b5f33](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/f301da8b-2f2a-4f70-aa8d-9a0f0eb58240)

**Comment by kwetnico** [comment]
Ok i seee with ide arduino..
Too complicate
I think there is a problem because I have already had the case 2 times out of 3 esp mini d1.. It refuses to take the IP address of the dhcp server.. I have flashed it several times

**Comment by kwetnico** [comment]
Bonjour, désolé en français on se comprendra mieux :)
Je me suis lancé sans connaitre avec réaliser ma configuration personnalisée avec PlatformIO sans connaitre j'ai réussi à créer mon fichier user en indiquant en dur mon IP.
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/52767c5a-e722-432b-be58-efffd2cc358e)

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/e8d02b8d-6d5b-450e-b7c8-d0c7407e6e34)

Il refuse de prendre l'ip que je lui indique...

**Comment by kwetnico** [comment]
hello I tried to build my configuration file but it does not work.
I have an esp32 wroom mini D1 compatible with esp32dev-ble.
I would like to force my IP address thanks for your help.

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/44378303-a378-410c-995b-5c616dc16c98)

**Comment by 1technophile** [comment]
Hello,

You need to add also the following macro:
```
'-DNetworkAdvancedSetup=true'

**Comment by DigiH** [comment]
Hi @kwetnico 

'-DESPWifiManualSetup=true'
is for defining the manual WiFi network conection with your
'-Dwifi_ssid="xxxx"'
'-Dwifi_password="xxxx"'

but for the manual IP definition you also need
'-DNetworkAdvancedSetup=true'
for your
'-DNET_IP="192.168.0.22"'
'-DNET_MASK="255.255.255.0"'
'-DNET_GW="192.168.0.1"'
'-DNET_DNS="192.168.0.1"'

**Comment by kwetnico** [comment]
Thanks,

But the rest of the settings are good?
When I run it via the command it doesn't stop compiling... 
"pio run --target upload"

Not easy when you discover visual studio, not possible to add (fix ip) in the web interface  ?
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/55ab0e2b-3fed-4d5a-84c7-6e08f949d1f2)

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/dfa39c44-7728-44e7-a5c4-65d38df39544)

**Comment by DigiH** [comment]
I assume you want to receive BLE device and have them decoded as well, correct?

For that you should have left everything from the original [env:esp32dev-ble] and just added your additional defines, i.e.

```
[env:esp32dev-ble]
platform = ${com.esp32_platform}
board = esp32dev
board_build.partitions = min_spiffs.csv
lib_deps =
  ${com-esp32.lib_deps}
  ${libraries.ble}
  ${libraries.decoder}
build_flags =
  ${com-esp32.build_flags}
  '-DZgatewayBT="BT"'
  '-DLED_SEND_RECEIVE=2'
  '-DLED_SEND_RECEIVE_ON=0'
  '-DGateway_Name="OMG_ESP32_BLE"' 
  '-DESPWifiManualSetup=true'
  '-Dwifi_ssid="xxxx"'
  '-Dwifi_password="xxxx"'
  '-DNetworkAdvancedSetup=true'
  '-DNET_IP="192.168.0.22"'
  '-DNET_MASK="255.255.255.0"'
  '-DNET_GW="192.168.0.1"'
  '-DNET_DNS="192.168.0.1"'
  etc. …
```

of which you missed quite a few Bluetooth specific lib_deps and build_flags.

I also assume you are making these changes to the existing environment definition in the file environments.ini, right? If so just use the platformio icon on the left (alien head) and expand `env:esp32dev-ble`, then select **Upload**

<img width="310" alt="Screenshot 2023-11-01 at 20 58 03" src="https://github.com/1technophile/OpenMQTTGateway/assets/17110652/94017dda-97f2-4a63-8c4f-c06a1b6770ea">

If however you are defining this environment as an addition to the existing `env:esp32dev-ble`, you need to give it a new unique name, e.g. `env:esp32dev-ble-mine`, which you can then Build and Upload the same as shown above.

Actually it is the latter, as I can just about spot some .et_env.ini in your screenshot above ;) so you will have to finalise your environment with the missing  lib_deps and build_flags AND give it a unique name.

**Comment by kwetnico** [comment]
> I assume you want to receive BLE device and have them decoded as well, correct?
> 
> For that you should have left everything from the original [env:esp32dev-ble] and just added your additional defines, i.e.
> 
> ```
> [env:esp32dev-ble]
> platform = ${com.esp32_platform}
> board = esp32dev
> board_build.partitions = min_spiffs.csv
> lib_deps =
>   ${com-esp32.lib_deps}
>   ${libraries.ble}
>   ${libraries.decoder}
> build_flags =
>   ${com-esp32.build_flags}
>   '-DZgatewayBT="BT"'
>   '-DLED_SEND_RECEIVE=2'
>   '-DLED_SEND_RECEIVE_ON=0'
>   '-DGateway_Name="OMG_ESP32_BLE"' 
>   '-DESPWifiManualSetup=true'
>   '-Dwifi_ssid="xxxx"'
>   '-Dwifi_password="xxxx"'
>   '-DNetworkAdvancedSetup=true'
>   '-DNET_IP="192.168.0.22"'
>   '-DNET_MASK="255.255.255.0"'
>   '-DNET_GW="192.168.0.1"'
>   '-DNET_DNS="192.168.0.1"'
>   etc. …
> ```
> 
> of which you missed quite a few Bluetooth specific lib_deps and build_flags.
> 
> I also assume you are making these changes to the existing environment definition in the file environments.ini, right? If so just use the platformio icon on the left (alien head) and expand `env:esp32dev-ble`, then select **Upload**
> 
> <img alt="Screenshot 2023-11-01 at 20 58 03" width="310" src="https://user-images.githubusercontent.com/17110652/279787192-94017dda-97f2-4a63-8c4f-c06a1b6770ea.png">
> If however you are defining this environment as an addition to the existing `env:esp32dev-ble`, you need to give it a new unique name, e.g. `env:esp32dev-ble-mine`, which you can then Build and Upload the same as shown above.
> 
> Actually it is the latter, as I can just about spot some .et_env.ini in your screenshot above ;) so you will have to finalise your environment with the missing lib_deps and build_flags AND give it a unique name.

I wan't just an ip adress static....  thanks for your help but it's too complicated I'm going to keep the web update method.

**Comment by DigiH** [comment]
Giving up just when you were about to finalise it :(

You got everything right apart from missing the original BLE gateway specific lib_deps and build_flags, and giving your personal environment a new unique name, otherwise the build process didn't know which one of the two identically named `env:esp32dev-ble` environments it really should build and upload, which gave you the 

> doesn't stop compiling...

**Comment by kwetnico** [comment]
> Giving up just when you were about to finalise it :(
> 
> You got everything right apart from missing the original BLE gateway specific lib_deps and build_flags, and giving your personal environment a new unique name, otherwise the build process didn't know which one of the two identically named `env:esp32dev-ble` environments it really should build and upload, which gave you the
> 
> > doesn't stop compiling...

it's good ?

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/2918d6c2-0f20-4d07-875f-a5e02ffddbd5)

**Comment by DigiH** [comment]
I can't see the very end of your environment, but I would say - Yes, looks perfect :)

Does it build and upload work fine when you select Upload on the left?

**Comment by kwetnico** [comment]
> I can't see the very end of your environment, but I would say - Yes, looks perfect :)
>
> Does it build and upload work fine when you select Upload on the left?

I don't understand it compiles and writes for all esp32-dev models

My environnent : 
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/6e903fc9-9e63-4597-a8e7-9578862ca1fb)


he doesn't stop:

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/b67be75b-7a17-45c5-9278-9ee54d8452de)

![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/2b3197d4-16b5-4049-8b4f-786e3cabe097)

...

**Comment by DigiH** [comment]
> My environnent :

Yes, and to only build and upload your environment, click on Upload on your expanded environment on the left.

![image](https://github.com/1technophile/OpenMQTTGateway/assets/17110652/f857669e-8b3c-4363-aa14-ae596fad9f1f)

Then it will only build your environment and upload it to the ESP32 connected.

No command line building required at all.

**Comment by kwetnico** [comment]
> > My environnent :
> 
> Yes, and to only build and upload your environment, click on Upload on your expanded environment on the left.
> 
> ![image](https://user-images.githubusercontent.com/17110652/279792716-f857669e-8b3c-4363-aa14-ae596fad9f1f.png)
> 
> Then it will only build your environment and upload it to the ESP32 connected.

Yes ok but i have an error : 
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/6d27277e-b84e-44cb-85c4-6bf67e74650f)

**Comment by DigiH** [comment]
> Yes ok but i have an error :

Ok, you do not have git installed on your computer, which is required for PlatformIO to fetch libraries, specifically the BLE Decoder and others for your environment. Some unforeseen missing element :(

Do what the prompt tells you - go to 

https://git-scm.com/downloads

and download the installer relevant for your computer OS and install git with it. Then  you are definitely good to go ;)

**Comment by kwetnico** [comment]
> > Yes ok but i have an error :
> 
> Ok, you do not have git installed on your computer, which is required for PlatformIO to fetch libraries, specifically the BLE Decoder and others for your environment. Some unforeseen missing element :(
> 
> Do what the prompt tells you - go to
> 
> https://git-scm.com/downloads
> 
> and download the installer relevant for your computer OS and install git with it. Then you are definitely good to go ;)

I had installed it and I had just deleted it I thought it was mandatory with the ardino IDE application.

**Comment by DigiH** [comment]
It is required for any remote library to be fetched for building, no matter for the Arduino IDE, PlatformIO … manually checking out git repos …

Having a GitHub account here it is also a good idea to keep git installed on your computer ;)

**Comment by kwetnico** [comment]
> It is required for any remote library to be fetched for building, no matter for the Arduino IDE, PlatformIO … manually checking out git repos …
> 
> Having a GitHub account here it is also a good idea to keep git installed on your computer ;)

thank you for your help I finally succeeded (not easy):
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/9c602b99-c7e9-484c-a8dd-7d2ac1d4e934)

With a good ip adress ! 
![image](https://github.com/1technophile/OpenMQTTGateway/assets/55591810/a27bba0e-c113-4628-a034-061f2617dbe3)

Thanks a lot

**Comment by DigiH** [comment]
> thank you for your help I finally succeeded

You're welcome :)

> (not easy)

True, but now you know the basics of creating and uploading custom environments, so any other future environments you might want to create are all following these steps, which you now know.
