### ISSUE TITLE
Publish mqtt message with retained flag

### ISSUE THREAD

**Issue by lhvo** [1technophile/OpenMQTTGateway#1781]
To avoid requesting the status of the devices after the reconnections, it would be great if messages are posted to MQTT with retained flag.

**Comment by DigiH** [comment]
Have a look at the first section of the MQTT ADVANCED PARAMETERS, and in your case you'd likely want to set `sensor_Retain` to true

https://github.com/1technophile/OpenMQTTGateway/blob/development/main/User_config.h#L359-L380

**Comment by lhvo** [comment]
Does it mean that we have to re-build with the #define or can we configure it dynamically during runtime  ?

**Comment by DigiH** [comment]
Yes, this will require a custom build with the #define, as not all, especially very rarely requested options like this one, can be included for runtime changeability to avoid bloating the code and settings JSON publishings.

Does sounds a lot more daunting than it is though when using the Visual Studio Code way

https://docs.platformio.org/en/latest/integration/ide/vscode.html#installation
