### ISSUE TITLE
Bluetooth module XM-15B with a NODEMCU Lolin is not working.

### ISSUE THREAD

**Issue by ctripodi** [1technophile/OpenMQTTGateway#179]
Hello, 
I am trying to use an Bluetooth module XM-15B with a NODEMCU Lolin but is not working.
I could not see any MQTT message.
I am using OpenMQTTGateway version v 0.7
I am using a modulo that is not complatible?

**Comment by 1technophile** [comment]
Hello,
Nope it is not compatible, with a nodemcu the module supported for ble are HM10 and HM11

**Comment by ctripodi** [comment]
OK, Thanks.
