### ISSUE TITLE
Feature Idea: Homematic/Asksin/BidCos interface

### ISSUE THREAD

**Issue by knopserl** [1technophile/OpenMQTTGateway#180]
This project is geat! as I'm trying to implement one gateway for multiple RF/Wifi devices and this looks as the best base for, it would be very attractive to inlude also the homematic Bidcos protocol. There are only a very few implementaions which support Bidcos like Homegear or the AskSin++ library, but with a couple of other side effects. Asksin++ runs not on ESP boards (AVM/ARM based like STM32), require an CC1101 and Homegear requires Linux and a CUL or an ARM SoC mit SPI interfaes etc.
So having Homatic RF protocol supported on ESP (32/8266) with either an CC1101 or even better with RFM69/95 etc. transceiver would be incredible.

**Comment by 1technophile** [comment]
A pr can be submitted for this
