### ISSUE TITLE
ESP32-C3 super mini not supported

### ISSUE THREAD

**Issue by michapr** [1technophile/OpenMQTTGateway#1817]
using the web upload I get the message:
"Your Unknown Chip board is not supported."

used airm2m_core_esp32c3 and other c3 options from pulldown option and the suggested connection "USB JTAG/serial"
(BTW: the "lolin_c3_mini" is missing in options...)

At first tried normal upload - failed, 
Then tried in bootloader mode and got the message that unknown chip (see above).

Board:
![image](https://github.com/1technophile/OpenMQTTGateway/assets/11854556/cc5eac6a-067b-4189-afb0-0b742e83645a)

Any idea?

Thanks!

**Comment by michapr** [comment]
> (BTW: the "lolin_c3_mini" is missing in options...)

was added in the meantime - thanks ;)
But using this web upload I get the same error.

BTW: The upload of the ready firmware is working (using the flash download tool) - so this is a way for all who want to use this chip.

**Comment by BOlaerts** [comment]
In my experience flashing the new ESP32 S2/C3 boards works best with https://adafruit.github.io/Adafruit_WebSerial_ESPTool/

**Comment by 1technophile** [comment]
It is now supported in the development branch, accessible here https://docs.openmqttgateway.com/dev

https://community.openmqttgateway.com/t/install-on-esp32-c3-super-mini/2965/21
