### ISSUE TITLE
presenceUseBeaconUuid doesn't work anymore since V1.7.0

### ISSUE THREAD

**Issue by RoBra81** [1technophile/OpenMQTTGateway#1839]
**Describe the bug**
Since version 1.7.0 although presenceUseBeaconUuid is activated mac address will be send in MQTT presence message. Work find till version 1.6.0

**To Reproduce**
1. Enable HASS presence: mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoBT/config -m '{"hasspresence":true}'
2. Enable presenceUseBeaconUuid: mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoBT/config -m '{"presuseuuid":true}'
3. Check MQTT messages

**Expected behavior**
The uuid should be used as id within MQTT message

**Environment (please complete the following information):**
* OpenMQTTGateway version 1.7.0

**Comment by absentwallaby** [comment]
I'm having the same issue.

**Comment by 1technophile** [comment]
Could you try to set the minimum rssi to -10
https://docs.openmqttgateway.com/use/ble.html#setting-the-minimum-rssi-accepted-to-publish-device-data-default-100

And see if it works

This would enable to confirm an hypothesis

**Comment by absentwallaby** [comment]
ok - this is what I have set in 
".../MQTTtoBT/config"

{"presuseuuid":true,"pubuuid4topic":true,"presenceawaytimer":60000,"save":true,"minrssi":-10}

- Adding the minrssi doesn't seem to have helped - still no uuid / beacons showing up - only MAC addresses.

**Comment by RoBra81** [comment]
Any news on this?

**Comment by 1technophile** [comment]
I will check it before releasing the new version
