### ISSUE TITLE
ESP32 -#elif with no expression Commit f515f9c03a1d65516782b3cfe99ae9cf2daf7e4f

### ISSUE THREAD

**Issue by AKA-47** [1technophile/OpenMQTTGateway#186]
Hi.
Got 2 errors since commit f515f9c03a1d65516782b3cfe99ae9cf2daf7e4f on esp32
ZgatewayBT:125: error: #elif with no expression
ZgatewayBT:147: error: #elif with no expression

**Comment by 1technophile** [comment]
indeed thanks for pointing
