### ISSUE TITLE
Stable OMG/BLE operation with 1.7.0!

### ISSUE THREAD

**Issue by tomcat-xx** [1technophile/OpenMQTTGateway#1867]
This is not an issue, more a solved one. So thanks for this Christmas gift!

I was about few times to report my issue, but then tested again, was not sure, changed settings and so on. With update to 1.4.0 it started. One of my gateways on an D1 Mini board did not run for weeks or months any more, sometimes not even for days. With upgrade to 1.6.0 (1.5.x I skipped) also 2 of the ESP32-WROOM based boards were affected. I cannot say, if just WIFI connection stopped working or operation at all. Even daily restart via MQTT command did not help, sometimes it felt as it even made it worse.

With 1.6.0 I also (finally) switched to PlatformIO, as I could not get it working with IDE. In the past I also had some issues with PlatformIO, don't remember exactly what, but this time I got it working. Had to learn then, that additional changes are needed (deactivation of Home Assistant discovery), to get it running at least for some days. But it still was not stable. Think I did all, that was needed to get same result after flashing with PlatformIO instead of IDE.

Now with 1.7.0 all 6 gateways are running for 3 weeks, without any issue. Thanks!

By the way: With PlatformIO it was just copying of my config file to the new folder, for getting all my setting in. Ok, some small changes because of authorization changes, but that would have come on top of bringing my settings into new User_config.h with IDE.

**Comment by 1technophile** [comment]
Thanks for the feedback!
