### ISSUE TITLE
Add configuring IP adress to 1.8.0 ?

### ISSUE THREAD

**Issue by kwetnico** [1technophile/OpenMQTTGateway#1902]
Hello, Have you planned in the future version 1.8.0 to integrate the possibility of setting and configuring the IP address directly from the configuration interface?
It's too complicated for everyone from visual studio with the custom configuration method.

**Comment by Wheemer** [comment]
That's what DHCP reservations on your router are for.

**Comment by DigiH** [comment]
I think what he means is the `NetworkAdvancedSetup`, available with custom environment definitions, bypassing any router's DHCP range, reservation and assignment.

https://docs.openmqttgateway.com/upload/builds.html#option-a-creating-a-portable-config-file

But AFAIK this is currently only planned to stay as environment definitions.

**Comment by kwetnico** [comment]
Exactement j'ai déjà mis cela en place si vous voulez que plus de personnes viennent vers votre solution qui est très bien je pense que cet ajout sera plus simple pour le plus grand nombre.. A vous de voir..
