### ISSUE TITLE
Which DIY card do you recommend ?

### ISSUE THREAD

**Issue by jmguilbert** [1technophile/OpenMQTTGateway#1910]
To build this example, which card in 433 do you recommend? Can we use a Lilygo Lora 32 v3 for example ? What would be the simplest board without having to use a soldering iron?
Can you provide links to Aliexpress or Amazon?
Big thanks.

**Comment by NorthernMan54** [comment]
The one I use is - https://github.com/NorthernMan54/rtl_433_ESP/blob/main/README.md - [LILYGO® LoRa32 V2.1_1.6.1 433Mhz](https://www.lilygo.cc/products/lora3?variant=42476923879605)

**Comment by jmguilbert** [comment]
the problem is the very fragile soldering of the pins near the screen cable. did you succeed without burning everything?

**Comment by NorthernMan54** [comment]
You don't need to install the pins to use the board, it comes complete.  If you look at my picture in the README, I never installed the pins

**Comment by jmguilbert** [comment]
Okay. Thank. I see.
For the sensors (temp, weight etc) you use a DIY products ?

**Comment by NorthernMan54** [comment]
I use the lilygo board with Acu-Rite and LaCrosse temperature sensors.  The board receives the transmissions and publishes them.

And in one use case I soldered a BME 280 Sensor to the pins to have a local sensor as well
