### ISSUE TITLE
ESP32 + SX12xx or "ttgo-lora-v1"

### ISSUE THREAD

**Issue by jmguilbert** [1technophile/OpenMQTTGateway#1911]
Good morning
Your program "Temperature example" is presented as possible on ESP32+ module sx12xx.
But the "platformIO" of this github is specified as suitable for a "ttgo-lora-v1".
Is it the same thing in the end?
Or do you need to change the type of card concerned.
I can't flash it.
Thank you so much

**Comment by 1technophile** [comment]
Good day,

This is not the same thing, but you could use the same pinout between the module and the esp32 as the ttgo-lora-v1 to make it works.
Not that you need to have the same LoRa module.
