### ISSUE TITLE
web flasher not working

### ISSUE THREAD

**Issue by deanfourie1** [1technophile/OpenMQTTGateway#1930]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
The web flasher tool is not working. The button just does nothing.

**To Reproduce**
Use chrome and attempt to flash a board.

**Expected behavior**
The popup to come up and select a serial port.

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

Not installed yet.

**Additional context**
```
Third-party cookie will be blocked. Learn more in the Issues tab.
/manifest.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
web-install.html:1 Access to script at 'https://unpkg.com/esp-web-tools@3.4.2/dist/web/start-flash-9b1cffdc.js?module' from origin 'https://docs.openmqttgateway.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
unpkg.com/esp-web-tools@3.4.2/dist/web/start-flash-9b1cffdc.js?module:1 
        
        
       Failed to load resource: net::ERR_FAILED
install-button.js?module:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://unpkg.com/esp-web-tools@3.4.2/dist/web/start-flash-9b1cffdc.js?module
web-install.html:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://unpkg.com/esp-web-tools@3.4.2/dist/web/start-flash-9b1cffdc.js?module
install-button.js?module:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://unpkg.com/esp-web-tools@3.4.2/dist/web/start-flash-9b1cffdc.js?module
manifest.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```
* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by 1technophile** [comment]
Hello,

I just tried it and it was working:
![image](https://github.com/1technophile/OpenMQTTGateway/assets/12672732/788f3997-51ab-4026-82e1-ad1adec28236)

Maybe a transient error

**Comment by deanfourie1** [comment]
oh that's weird.

I've tried every solution I think could be blocking it.

**Comment by deanfourie1** [comment]
Are you using latest version of chrome?

**Comment by 1technophile** [comment]
I'm using Version 123.0.6312.122 (Official Build) (64-bit) on Windows
Tested on MacOS also with 122.0.6261.129 and it works

**Comment by 1technophile** [comment]
Alternatively you could try the development version falsher:
https://docs.openmqttgateway.com/dev/

**Comment by DigiH** [comment]
@deanfourie1 

How is this flash erase site working for you?

https://espressif.github.io/esptool-js/

and which OS are you on?

**Comment by 1technophile** [comment]
Closing as no answer

**Comment by deanfourie1** [comment]
I got this working, not sure how or why it wasnnt working, just started working
