### ISSUE TITLE
Continuously send IR message

### ISSUE THREAD

**Issue by konektor001** [1technophile/OpenMQTTGateway#197]
Is it possible to repeat X times an IR message other than Sony protocol?
It would be useful for example sending continuous "volume_up" to an amplifier.
Thanks.

**Comment by 1technophile** [comment]
yes just follow the wiki:
https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-IR#send-data-by-mqtt-with-advanced-ir-parameters

**Comment by 1technophile** [comment]
Indeed, i corrected it. It should work with sendNEC, try maybe a bigger repeat , 10 or 20

**Comment by konektor001** [comment]
Sorry, but for me, the repeat command does not work. If I send quickly the single messages it works (not so effective for MQTT), but it would be better with the repeat command.

**Comment by 1technophile** [comment]
do you see ` IR repeat:` on the serial monitor?

**Comment by 1technophile** [comment]
I'm going to close the issue, you can reopen it if needed
