### ISSUE TITLE
lora configuration is not restored after reboot

### ISSUE THREAD

**Issue by belkone** [1technophile/OpenMQTTGateway#1975]
Hi, 

First of all, thanks for the great job!
I have the following problem and I'm not sure if it's intentional or a bug.

Lora configuration (e.g. spreadingfactor) saved via webgui is not restored after gateway restart.

Additionally, the LORA_SPREADING_FACTOR changed in config_LORA.h and then recompilation also seem not to be applied when the gateway is launched, even though it appears to be correct in the configuration page. I have to enter Lora configuration in WebGUI and save the setting (even without any change) - then Lora communication starts working.

Additionally, when receiving messages, they do not appear on the Gateway screen, on various screenshots on the Internet I saw the received message there - is it supposed to be like that or am I missing something?

Tested on boards: TTGO LoRa32 v2.1-1.6 (T3_v1.6 ) and Heltec WiFi LoRa 32 V2 
with OpenMQTTGateway version 1.7.0 and development

**Comment by westwoodx** [comment]
Hi,
Thanks also for the fantastic software!
Using Heltec LoRa 32, I seem to have a problem similar to belkone with v1.8.0 and 1.7.0.  All Lora parameters such as spreading factor, sync word etc save ok in the webui after a reboot, but Lora doesn't work unless I hit save Lora configuration again in the webui (without any changes, but I use non-default SF and Sync word), then all is good.  If I hard code the parameters in ie LoRa.setSpreadingFactor after LoRa.begin() all works fine!
