### ISSUE TITLE
Please add support for SwitchBot Remote W0301700

### ISSUE THREAD

**Issue by flavio-fernandes** [1technophile/OpenMQTTGateway#1978]
Feature request: SwitchBot Remote W0301700

Dear OpenMQTTGateway guru,

I messed up and did not realize that the W0301700 is not listed on
https://decoder.theengs.io/devices/devices.html .

As a result, I'm unable to use my [Theengs Plug](https://shop.theengs.io/products/theengs-plug-smart-plug-ble-gateway-and-energy-consumption) as a gateway, like I do with my other BLE devices under Home Assistant.

More info on the SwitchBot Remote W0301700 is available on the
[Amazon link](https://a.co/d/04Rm6Yx2).

Could you please help me add support for it? If there is any way I can assist you, please let me know.

Sincerely,

@flavio-fernandes

**Comment by DigiH** [comment]
Hi @flavio-fernandes,

We can try to add the SwitchBot Remote with your help, but so far it doesn't seem that the Remote actually send any BLE advertising data, as required by Theengs Decoder, which is used for BLE decoding in OpenMQTTGateway, as you can see in some other OpenWonderLabs (the SwitchBot manufacturer) threads with other users requesting the same feature.

https://github.com/OpenWonderLabs/SwitchBotAPI/issues/56

https://github.com/OpenWonderLabs/SwitchBotAPI-BLE/issues/14

I don't know if this has already changed with a newer firmware of the Remote, as the above linked repo is sometimes very slow to update any information. You can try turn on **BT: Publish Advertisement data** in your Plug's HA gateway UI and then monitor the undecoded messages from your Remote with MQTT Explorer.

If the undecoded advertisement data changes with different remote button presses, then it likely to be possible for us to implement a decoder for the Remote, but if this still has not been implemented by SwitchBot, then it won't currently be possible until this might change in the future.

You might want to add your voice to the above links in that case ;)
