### ISSUE TITLE
BLE device tracker is not working properly

### ISSUE THREAD

**Issue by rolfberkenbosch** [1technophile/OpenMQTTGateway#198]
Hi all, i found out that the ble (Bluetooth) tracker is not working properly, i see that is sees my device 1 a 2 times in a few hours.

If i run a script from Andreas Spiess, it sees my bluetooth device tracker every time, you can see it below:

``off

BLE Scan restarted.....
BLE Advertised Device found: Name: , Address: 68:64:4b:58:6d:6f, manufacturer data: 4c000906030000000000
BLE Advertised Device found: Name: , Address: 0d:90:f4:91:09:c9, manufacturer data: 060001092000b68b0ad06eb0ae8dec331b769944346c5ee2d6176487c1
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:21:97, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: , Address: 78:f4:92:3c:dd:13, manufacturer data: e00001bbca593bcf, serviceUUID: 0000fe9f-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: iTAG            , Address: ff:ff:10:14:c6:47, appearance: 961, serviceUUID: 0000ffe0-0000-1000-8000-00805f9b34fb, txPower: 0
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:10:11, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:4f:fd, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
E (73103) BT: btc_search_callback  BLE observe complete. Num Resp 84

off

BLE Scan restarted.....
BLE Advertised Device found: Name: , Address: 68:64:4b:58:6d:6f, manufacturer data: 4c000906030000000000
BLE Advertised Device found: Name: , Address: 0d:90:f4:91:09:c9, manufacturer data: 060001092000b68b0ad06eb0ae8dec331b769944346c5ee2d6176487c1
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:21:97, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: , Address: 78:f4:92:3c:dd:13, manufacturer data: e00001bbca593bcf, serviceUUID: 0000fe9f-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:10:11, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
BLE Advertised Device found: Name: iTAG            , Address: ff:ff:10:14:c6:47, appearance: 961, serviceUUID: 0000ffe0-0000-1000-8000-00805f9b34fb, txPower: 0
BLE Advertised Device found: Name: Flower care, Address: c4:7c:8d:66:4f:fd, serviceUUID: 0000fe95-0000-1000-8000-00805f9b34fb
E (103107) BT: btc_search_callback  BLE observe complete. Num Resp 125
``

Is this a config issue ?

**Comment by 1technophile** [comment]
We definitively need more details, what version of code are you using, what library version of BLE ESP32?

**Comment by rolfberkenbosch** [comment]
The BLE device was not working properly, it was a faulty one. I have tested it with an ibeacon, and that works great!
