### ISSUE TITLE
Add support for LILYGO-T3-S3

### ISSUE THREAD

**Issue by StarPicard** [1technophile/OpenMQTTGateway#1990]
LILYGO is shipping a new version of their LoRaWAN board. It comes with newer chips and an esp32-s3.

https://www.lilygo.cc/products/t3s3-v1-0

This board is not supported yet. But it would be great. It should be noted that this board ships with three different Lora transeivers (SX1280, SX1276, SX1262).

Thanks for the great work

**Comment by NorthernMan54** [comment]
Are you asking about Lora Mode or rtl_433 mode ?

For rtl_433 mode, only the SX1276 is likely to work.  The SX1280 is for 2.4 Ghz devices, and the SX1262 doesn't have the direct receive mode needed to decode the signal.

**Comment by StarPicard** [comment]
I actually meant the FSK mode. (I own the sx1262)

**Comment by NorthernMan54** [comment]
Same applies to FSK signals

**Comment by StarPicard** [comment]
OK, so I bought the wrong hardware... But the T3-S3 also comes with a SX1276 chip. Would flashing work out of the box? I ask because it has the other esp chip on board.
