### ISSUE TITLE
Help me with this issue

### ISSUE THREAD

**Issue by kofi6069** [1technophile/OpenMQTTGateway#1994]
Sketch uses 285885 bytes (9%) of program storage space. Maximum is 3145728 bytes.
Global variables use 30732 bytes (9%) of dynamic memory, leaving 296948 bytes for local variables. Maximum is 327680 bytes.

2.Sketch uses 285885 bytes (9%) of program storage space. Maximum is 3145728 bytes.
Global variables use 30732 bytes (9%) of dynamic memory, leaving 296948 bytes for local variables. Maximum is 327680 bytes.
dfu-util 0.11-arduino4

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: No DFU capable USB device available
Failed uploading: uploading error: exit status 74

**Comment by JamiePhonic** [comment]
You'll need to provide more information like the board and receiver you're using, which configuration (environement, i.e. esp32dev-rf, etc) you're trying to flash and how you're trying to flash it (PIO or Arduino)
