### ISSUE TITLE
jeedom - any command to switchbot X1

### ISSUE THREAD

**Issue by anthopocket** [1technophile/OpenMQTTGateway#1998]
hi,

i have a problém with the switchbot X1. I have any command to mqttdiscovery

![image](https://github.com/user-attachments/assets/74d1cf8e-37ca-448f-a792-221696aeb481)
![image](https://github.com/user-attachments/assets/bb77873d-4cdc-480f-a7da-4d068f54661a)

in the mqtt broker, the log is

`[2024-08-09 21:23:31] DEBUG  : new message:{"home":{"OMG_GARAGE":{"OMG_GARAGE":{"BTtoMQTT":{"E6B316D83CE6":{"id":"E6:B3:16:D8:3C:E6","rssi":-77,"brand":"SwitchBot","model":"Bot","model_id":"X1","type":"ACTR","mode":"onestate","state":"on","batt":100}`

the gateway is
![image](https://github.com/user-attachments/assets/3c7e359e-350c-4f71-a728-1f5182886a98)

Thanks you

**Comment by anthopocket** [comment]
communty jeedom

https://community.jeedom.com/t/ne-reconnait-pas-le-switchbot-alors-connu-domg/129100

**Comment by 1technophile** [comment]
What is the bot firmware version?

**Comment by anthopocket** [comment]
Firmware : 4.9
