### ISSUE TITLE
Mi Flora consistent MQTT protocol

### ISSUE THREAD

**Issue by torwag** [1technophile/OpenMQTTGateway#201]
I just noticed that the RSSI value is send by e.g. :

home/BTtoMQTT/445F3666113E  -085

whereas all other data is send by adding a subtopic e.g.: 

home/BTtoMQTT/445F3666113E/temp  20.0
home/BTtoMQTT/445F3666113E/moi 10
home/BTtoMQTT/445F3666113E/lux  500

This makes it unnecessary difficult to parse the MQTT topic, as it is not consistent. 
If the RSSI value will be send in the same way e.g.:
 
home/BTtoMQTT/445F3666113E/rssi -085 

parsing would be easier and the meaning of the payload would be more clear to beginners.

**Comment by 1technophile** [comment]
@torwag could you test the changes from master and say me if ok for you?

**Comment by torwag** [comment]
Looks good to me, flashed a second board with the new code and it seems to work as desired.
I created a fork and did the changes myself, however, did not had time to test them and create a PR.
BTW. I couldn't find how the trc command is used. Seems to be a debug command, but couldn't find any infos about it.
