### ISSUE TITLE
Should the following test for connectivity be && rather than ||

### ISSUE THREAD

**Issue by puterboy** [1technophile/OpenMQTTGateway#2029]
In trying to debug failed MQTT connection in `main.ino`, I noticed the following:
```
mqtt->connection_failure_callback = [] {
    if (WiFi.status() != WL_CONNECTED || ethConnected == false || SYSConfig.offline) {
      // No network connection or offline, ignore this failure
      return;
    }
    failure_number_mqtt++; // we count the failure
```

Shouldn't that be:
```
 if ((WiFi.status() != WL_CONNECTED && ethConnected == false) || SYSConfig.offline) 
```
Because in my case I am using an esp32 with WiFi and I don't have `ESP32_ETHERNET` defined, so `ethConnected = false` always.
I think you just want to check for absence of *any* connection.

**Comment by 1technophile** [comment]
>  if ((WiFi.status() != WL_CONNECTED && ethConnected == false) || SYSConfig.offline) 

Yes that's right, let me fix it
