### ISSUE TITLE
In Home Assistant SYS:Firmware Update state is UNKNOWN

### ISSUE THREAD

**Issue by Hydro-guy** [1technophile/OpenMQTTGateway#2041]
Running Home Assistant Core 2024.8.3 Supervisor 2024.08.0 Operating System 13.1 Frontend 20240809.0 with Mosquitto version 2.0.11 and OpenMQTTGateway v1.7.0  on both a Theengs plug and Lilygo LoRa.   Home Assistant reports that SYS:Firmware Update state is UNKNOWN.
MQTT explorer reports {"stat_t":"home/C8F09EAF63D4/RLStoMQTT","avty_t":"home/C8F09EAF63D4/LWT","name":"SYS: Firmware Update","uniq_id":"C8F09EAF63D4-update","payload_install":"{\"version\":\"latest\"}","pl_avail":"online","pl_not_avail":"offline","cmd_t":"home/C8F09EAF63D4/commands/MQTTtoSYS/firmware_update","device":{"ids":["C8F09EAF63D4"],"name":"C8F09EAF63D4","mdl":"TPLUG01","mf":"Theengs","cu":"http://192.168.5.29/","sw":"v1.7.0"}}

Not very familiar with MQTT - is this an OpenMQTT issue or is Home Assistant not parsing the mqtt correctly

![image](https://github.com/user-attachments/assets/17a85705-ca25-41d6-b4f6-825aaac67cc2)

Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**

**To Reproduce**
1. Publish to '...'
2. Subscribe on '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/1technophile/OpenMQTTGateway/workflows/Build/badge.svg?branch=master)](https://github.com/1technophile/OpenMQTTGateway/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum below
[![Community forum](https://img.shields.io/badge/community-forum-brightgreen.svg)](https://community.openmqttgateway.com)

**Comment by 1technophile** [comment]
Unfortunately github changed its certificate without notice breaking the automatic web update system.
The new binaries will be hosted elsewhere so as to avoid this kind of issue in the future.
The development branch is already setup with the new deployment host and I will give an update process for the Theengs customers. Sorry for the inconvenience.
