### ISSUE TITLE
Mi Flora redundant code part

### ISSUE THREAD

**Issue by torwag** [1technophile/OpenMQTTGateway#206]
Hi,

I found that the code to distinguish between the different sensor data, contains
fer, tem, lux, hum, moi as possible sensor values.
To me fer, tem and lux is clear. However, what is the differences between hum (humidity?) and moi (moisture?)

I observed the mqtt data flow for some time but never received an 'hum' message. Maybe it is redundant or something changed with the firmware versions of the sensor nodes? 
If so, I would suggest to substitute hum to send it out as moi value to make the MQTT messages consistent independent of old and new firmware, as some users even might run (unknowingly)  a mixture of firmware versions, among their sensors.

[Direct link to the code in question](https://github.com/1technophile/OpenMQTTGateway/blob/c0fca716195e5e0be83c74a7ef3e68e358d6d182/ZgatewayBT.ino#L358)

**Comment by 1technophile** [comment]
Hello,

Hum is not used for mi flora on the last revision it is indeed substitued by moi _moisture_ , hum is related to the air humidity measured by mi jia indoor temperature & humidity sensor.

**Comment by 1technophile** [comment]
@torwag Could you close the issue if ok for you

**Comment by torwag** [comment]
Thanks for the explanation.
Maybe some comments in the code point to this.
I will submit a PR and then close this issue.

**Comment by 1technophile** [comment]
@torwag did you progressed on your PR
?

**Comment by torwag** [comment]
#222

**Comment by 1technophile** [comment]
thanks

**Comment by danielpondruff** [comment]
@1technophile is there a way to publish humidity to mqtt? i dont understand why #hum is not publish to mqtt... can you explain this? 

greetings Daniel

**Comment by torwag** [comment]
Hum stands for air humidity and is sensed by yet another xiaomi device NOT the flora. The flora sens moisture of the sorrounding earth.

The protocol works for both devices and they share values like e.g. temperature.

Inside the source code you find a comment about this. 

Hope that makes it clear.
