### ISSUE TITLE
ttgo_lora32_v21 firmware too big 

### ISSUE THREAD

**Issue by Pascal66** [1technophile/OpenMQTTGateway#2085]
**Describe the bug**
When compiling the source code without any modifications, the firmware is too big. this make the lilygo to reboot

**To Reproduce**
- Build and upload

**Environment (please complete the following information):**
* OpenMQTTGateway version used ( development)

**Additional context**

RAM:   [==        ]  19.0% (used 62364 bytes from 327680 bytes)
Flash: [==========]  99.8% (used 1307961 bytes from 1310720 bytes)
Building .pio\build\LilyGo-lora32-v21\firmware.bin
esptool.py v4.5

Removing the ssd1306 library make it working
RAM:   [==        ]  18.9% (used 61872 bytes from 327680 bytes)
Flash: [==========]  97.1% (used 1273133 bytes from 1310720 bytes)

**Comment by 1technophile** [comment]
all the environments are built at each PR and every night as you can see below for the last PR:
https://github.com/1technophile/OpenMQTTGateway/actions/runs/11240356659

As suggested in the troubleshooting section https://docs.openmqttgateway.com/upload/troubleshoot.html#compilation-build-error you may have a wrong version of one or several components involved in the build

**Comment by Pascal66** [comment]
Using the original code without any modifications.
If I'm near 131k, with ssd1306 the heltec or the lilygo reboot.
If I'm under 130k, things work.
If I'm not using the ssd1306, i'm around 127k this is fine.
So under 130k eveything work.

**Comment by 1technophile** [comment]
Fixed by https://github.com/1technophile/OpenMQTTGateway/pull/2110
