### ISSUE TITLE
`sendCustomDataNotification`, only sending 1 frame

### ISSUE THREAD

**Issue by JavanPoirier** [1technophile/OpenMQTTGateway#2098]
https://github.com/1technophile/OpenMQTTGateway/blob/ba9506c0226fb064f7faa6ea53c3e2a5eeeeec27/main/Zblufi.ino#L149C10-L149C14

Using the current call to `esp_blufi_send_notify` appears to only send single frame with partial data. Moving to `esp_blufi_send_custom_data` solves this issue and provides the entire payload.

![image](https://github.com/user-attachments/assets/3d37ece5-20f4-43f7-ab07-84f772480f66)

**Comment by h2zero** [comment]
Yes, if the payload is larger than the connection MTU - 3 bytes then it would be capped at that size. Making this change would be a good idea for sure. The `esp_blufi_send_custom_data` function simply packetizes the data and spam notifies until it's all sent, it is pretty robust as well.
