### ISSUE TITLE
Feature Request:BLE scan custom devices?

### ISSUE THREAD

**Issue by huexpub** [1technophile/OpenMQTTGateway#210]
great A  project， thanks, i do it work for 2 xiaomi bluetooth temp&humi in esp32 ,but BT scan my Bluetooth  keybroad ,Bluetooth  IR controler，Bluetooth headset，so the temp and humi update too long , if only  scan  the ble mac address of manual set，The efficiency of scan will be higher ?

**Comment by tunip** [comment]
Specifying the BLE mac addresses for scanning make sense. If you have multiple ESP32 in the house to cover all BLE devivces you scan sometimes the device multiple times.

**Comment by thundergreen** [comment]
What is the best setting for ibeacon presence detection? Bt scan interval to 1 second? It takes ages to recognise my rssi for my beacon . Wanna speed this up.hiw can I do though ?

**Comment by codegrau** [comment]
@1technophile Would that feature make it possible to "scan" for presence detection with iPhones without an external app like https://github.com/andrewjfreyer/monitor this bash script on Raspberry Pi would do?

**Comment by 1technophile** [comment]
white list and black list of ble devices has been introduced in V0.9.1
https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-bluetooth-BLE-09#setting-a-white-or-black-list
