### ISSUE TITLE
Current code crashes ESP on trace call

### ISSUE THREAD

**Issue by openSoftMan** [1technophile/OpenMQTTGateway#211]
In using current beta code and core 2.4.1 my board crashes at this line whether trace is enabled or not.

Crashes at this [line](https://github.com/1technophile/OpenMQTTGateway/blob/89fca51188c7047fcf1c7b3af765ef4b0aab94dc/OpenMQTTGateway.ino#L749).

Reverting a recent change seems to correct this:

Crashes:
trc(ReceivedSignal[o][0]+"/"+ReceivedSignal[o][1]);

This seems to resolve it:
trc(String(ReceivedSignal[o][0])+"/"+String(ReceivedSignal[o][1]));

Thanks for the work on the project.

**Comment by 1technophile** [comment]
thanks for pointing this
