### ISSUE TITLE
File *.bin with esp32 ou esp8266

### ISSUE THREAD

**Issue by lscosta90br** [1technophile/OpenMQTTGateway#215]
Hi guys !!

Is there any compiled file for esp32 or esp8266 ... I have difficulty compiling.
thankful
Leandro Costa

Before submitting a problem please check the troubleshooting section
https://github.com/1technophile/OpenMQTTGateway/wiki/Troubleshooting

So as to have a more efficient treatment of your request please provide the following information:
* OpenMQTTGateway version used (V0.4, 0.3, master...)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries
* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://travis-ci.org/1technophile/OpenMQTTGateway.svg?branch=master)](https://travis-ci.org/1technophile/OpenMQTTGateway)
* If you are not sure this is a bug or an enhancement post your question to the tchat room below
[![Gitter chat](https://img.shields.io/gitter/room/nwjs/nw.js.svg)](https://gitter.im/OpenMQTTGateway/Questions_support)

**Comment by lscosta90br** [comment]
Thank you !!!
I just found

https://github.com/1technophile/OpenMQTTGateway/releases

**Comment by 1technophile** [comment]
hello, if you are ok with compiling could you close the issue?

**Comment by lscosta90br** [comment]
Compiling ok

**Comment by lscosta90br** [comment]
compiling  ok
