### ISSUE TITLE
error in ZgatewayBT.ino

### ISSUE THREAD

**Issue by stevenhorner** [1technophile/OpenMQTTGateway#225]
Just tried to use a HM10 with older firmware and kept getting an error when compiling regarding `subjectBTtoMQTTRSSI` being undefined.

Line 302 in `ZgatewayBT.ino` should be:
`String mactopic = subjectBTtoMQTT + mac + subjectBTtoMQTTrssi;`

With `rssi `in lowercase

This fixed the compilation but unfortunately my HM10 didn't work because it's on firmware 545, but that's a job for another day.

**Comment by 1technophile** [comment]
Thanks for pointing that !
