### ISSUE TITLE
Wiki error with the Esp IR schema 

### ISSUE THREAD

**Issue by xelfe** [1technophile/OpenMQTTGateway#228]
It's about the Esp IR schema that we can see into the wiki [here](https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-IR-Send-and-Receive).
The schema illustrate a TSOP38238 or a 1828T IR receiver. Both have ground on the middle leg of the receiver. The ground and the vcc have to be switch.
![Esp IR schema](https://raw.githubusercontent.com/1technophile/OpenMQTTGateway/master/img/OpenMQTTgateway_ESP8266_Addon_IR.png)

**Comment by 1technophile** [comment]
Thanks for pointing that, if you are interested don't hesitate to modify the [fritzing file ](https://github.com/1technophile/OpenMQTTGateway/blob/master/img/OpenMQTTgateway_ESP8266_Addon_IR.fzz) and submit a pull request.
