### ISSUE TITLE
Esp IR wiki support

### ISSUE THREAD

**Issue by xelfe** [1technophile/OpenMQTTGateway#229]
There's any reason that Ir stuff is not into the [esp32 part](https://github.com/1technophile/OpenMQTTGateway/wiki/Module-Overview-ESP32) of the wiki ?
I did a quick test and it's seem to work great.

**Comment by 1technophile** [comment]
Yes IR emitting was not available when I integrated RF and BLE to ESP32, is it working now?
If yes are you using irremote or irremoteESP8266?

**Comment by xelfe** [comment]
@1technophile I suppose that I use irremote. I did not change anything. Actually the IR receiver work great but for the IR sender when I do exemple `home/OpenMQTTGateway/commands/IR_SAMSUNG -m 3772793023` my mqtt broker receive it but nothing happen. It's like that my esp32 did not bind that..

**Comment by xelfe** [comment]
@1technophile why not using the native [RMT driver](https://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/rmt.html) fors esp32 ?

**Comment by 1technophile** [comment]
Could be an option but never digged into it. I agree that is better to use embedded hardware when it is present.

**Comment by 1technophile** [comment]
Im' closing this issue, if you have suggestions on an arduino library to use  with RMT and some time to help on this don't hesitate to reopen.
