### ISSUE TITLE
Support for IR controller shield (wemos d1 mini)

### ISSUE THREAD

**Issue by rradar** [1technophile/OpenMQTTGateway#234]
Wemos D1 mini IR controller shield specifications:

- **4x IR LEDs** (940nm) pointing in four different directions
- 1x IR receiver (38 kHz) for learning function
- Tx/Rx mode selection – Sender – D3/GPIO0, Receiver – D4/GPIO2
- 2x 8-pin headers compatible with Wemos/LOLIN D1 mini board

![top](https://user-images.githubusercontent.com/34582688/43037602-2779a45c-8d0f-11e8-9568-ca63f977e313.jpg)
![bottom](https://user-images.githubusercontent.com/34582688/43037603-2b4c2fc8-8d0f-11e8-89e0-ee39c34291f5.jpg)

US $1.40 / piece

Is it for good? Should make a compact desgin in the end :smiling_imp:

**Comment by rradar** [comment]
More technical details here: https://wiki.wemos.cc/products:d1_mini_shields:ir_controller_shield

Including schematic's and datasheet's

> Schematic V1.0.0
> IR12-21c Datasheet
> IRM-H638T Datasheet

**Comment by 1technophile** [comment]
Ordered, will see in a few weeks

**Comment by rradar** [comment]
I have it! Soldered and ready to fly! 

Pins are clear:

D3(GPIO0) | Send
D4(GPIO2) | Receiver

Any tips for code to try? Should it just works out of the box?

**Comment by 1technophile** [comment]
great, just follow the [wiki ](https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-IR-Send-and-Receive) on we say to uncomment ZgatewayIR in user_config.h and change the pins in config_IR.h

**Comment by 1technophile** [comment]
I received mine, don't still tested them, do you have some feedback on your side?

**Comment by rradar** [comment]
hey @1technophile 
sorry - didn't had any time recently and had no running arduino sdk as well...
Maybe the next weekend I have time to try - meanwhile you could give a try and report back ;)

**Comment by 1technophile** [comment]
@rradar I confirm it works natively with these pins:
```
#ifdef ESP8266
  #define IR_RECEIVER_PIN 2
  #define IR_EMITTER_PIN 0
```

Receiver and emitter

Range of emitter is around 2meters for my tv
