### ISSUE TITLE
Add the ability to handle RF codes up to 32bits

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#24]

**Comment by brendanheyu** [comment]
I had to modify IRemoteESP8266.h to increase the buffer for my raw air con controls (midea a/c)

#define RAWBUF 220 // Length of raw duration buffer

**Comment by 1technophile** [comment]
waiting to implement this, there is maybe an issue with RCSwitch about 32 bits support
https://github.com/sui77/rc-switch/issues/78

**Comment by AKA-47** [comment]
It would be nice to be able to send shorter commands.
i have some device sending things like this:

Decimal: 31 (5Bit) Binary: 11111 Tri-State: 11 PulseLength: 82 microseconds Protocol: 0
Raw data: 4056,75,33,29,982,31,965,34,959,40,613,

Decimal: 127 (7Bit) Binary: 1111111 Tri-State: 111 PulseLength: 349 microseconds Protocol: 0
Raw data: 4027,375,2092,352,2079,361,2078,366,2075,364,2090,355,2071,367,2074,

would be nice to do something like 

home/commands/PLSL_82/433_0/BITS_7 to put it into mySwitch.send(data, 24);

quickly tried some debugging and have not seen any issues

how can i help you implementing this?

**Comment by 1technophile** [comment]
You mean that you've done some test sending data with less than 24 bits and it worked, like for example mySwitch.send(31, 5);
or
mySwitch.send(127, 7);
?

**Comment by Flagun** [comment]
Can you please add an option to choose BIT lenght? 
I have devices that use 25 bits. Your code is set to 24. 
I changed the code to 25 and your gateway works correctly with my devices.

**Comment by 1technophile** [comment]
yes, can be settable with the key RFBITS_ into the topic

As an impact the key for IR bits length is now IRBITS_

wiki updated
