### ISSUE TITLE
Bin files

### ISSUE THREAD

**Issue by adas4190** [1technophile/OpenMQTTGateway#244]
Hi. It would be awesome if someone compile firmware for srfb for me as I'm having hard time with arduino. I can flash bin files. It possible please? 

Thank You.

**Comment by adas4190** [comment]
Thank you so much!!

**Comment by adas4190** [comment]
That link is it to the latest revision? I might have a faulty hardware as it sometimes refuse to connect to wifi or do not go to ap mode. It would be lovely if we could restore factory settings by holding the button for 40sec like in tasmota. 

I love the firmware nevertheless is ultra snappy. Thank You.

**Comment by 1technophile** [comment]
Could you try[ this one](https://drive.google.com/file/d/1Tl5mViteJ4cqhSbBt0HVls0j6k23kiia/view?usp=sharing), it is the last revision:

**Comment by 1technophile** [comment]
it is in the [wiki](https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-SRFB#send-data-by-mqtt-to-convert-it-on-rf-signal)

**Comment by adas4190** [comment]
I think I've tried everything but no matter what topic I have used I cannot turn on my cheap rf sockets:(

**Comment by 1technophile** [comment]
When you press the button of your remote do you see something on your broker ?

**Comment by adas4190** [comment]
I can see and use devices but I can only receive codes but I'm stugling to send the code. I tried to serial connection but I'm neeb and I couldny find proper explanation how to do so.

**Comment by 1technophile** [comment]
So as to send code you need to publish data to your mqtt broker ( not to your serial connection), did you tested the commands pointed in the wiki above ?

**Comment by adas4190** [comment]
Ok. I've solved it. It turns out that device (cheat rf outlets) doesnt react when I send the code. I will have to tinker with advenced code options probably. Thank You

**Comment by 1technophile** [comment]
If ok for you with the bin files provided could you close the issue.
