### ISSUE TITLE
Simple Input Detection

### ISSUE THREAD

**Issue by QuagmireMan** [1technophile/OpenMQTTGateway#247]
I see there is an actuator script for output, but I don't see a script to read inputs.  Unless I overlooked something.

It seems it would be very easy to modify the HCSR501 script for this purpose. 

Any thoughts?

**Comment by 1technophile** [comment]
You have an analog read input :
https://github.com/1technophile/OpenMQTTGateway/blob/master/ZsensorADC.ino

**Comment by QuagmireMan** [comment]
It still needs some work and I am learning the ins and outs of github at the same time, but I have started it, it just isn't as complete as I would like it.  How soon is your next release?

**Comment by QuagmireMan** [comment]
I have only tested it on an ESP8266 so far. And I am still very unsure how to merge my code with yours.

**Comment by 1technophile** [comment]
I'm closing the issue as now we have a pull request to discuss
