### ISSUE TITLE
broadlinks

### ISSUE THREAD

**Issue by crowland88** [1technophile/OpenMQTTGateway#248]
awesome work on this project.  please add support for the broadlink devices broadlink rm pro or broadlink mini 3 blackbeam  to use with ir and rf 433mhz devices. `http://www.ibroadlink.com/rm/` 

sorry still new to GitHub and I don't understand the tech info.

**Comment by 1technophile** [comment]
Please follow feature request submission guide before requesting a feature.

**Comment by 1technophile** [comment]
This kind of subject should be discussed on the forum, open an issue for this is not relevant here  ; -)
Please go to http://community.openmqttgateway.com
