### ISSUE TITLE
Weak IR signal

### ISSUE THREAD

**Issue by adas4190** [1technophile/OpenMQTTGateway#249]
Hi. I have build IR gateway with NodeMCU v1 but what I have notices is that IR signal seems to be weak comparing with remote, plus I cannot get my old Sony Tv to react any way. My marantz receiver is fine. I might be my setup issue but I have no clue. 

Thank You.

**Comment by adas4190** [comment]
Sorry. I follow your advice. 😊 thank You

**Comment by 1technophile** [comment]
No problem see you on the forum
