### ISSUE TITLE
Ethernet setup, incorrect (un)comment line

### ISSUE THREAD

**Issue by salvq** [1technophile/OpenMQTTGateway#268]
User_config.h defines line 71 says: // Advanced network config (optional) if you want to use these parameters uncomment line 158, 172 and comment line 171  of OpenMQTTGateway.ino

OpenMQTTGateway.ino line 158, 171 and 172 are not related network, I see network setup on lines from 523:
  //Ethernet.begin(mac, ip); //Comment and uncomment the following line if you want to use advanced network config

What line 158 refers to ?

**Comment by 1technophile** [comment]
I removed those lines and implemented automatic detection of advanced network config if you replace the first value of dns or gateway by something different from 0
