### ISSUE TITLE
Add RF and IR repeater function

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#27]
The goal is when a signal is received tfrom RF or IR to repeat it with the emitter, taking into account loop issues (if multiple gateway don't loop the signal)

**Comment by phlash13** [comment]
Isn't this achievable by simply subscribing to the same MQTT channel to which you publish your IR readings?

**Comment by 1technophile** [comment]
Yes and by adding loop preventing at gateway and multiple gateways level.

**Comment by 1technophile** [comment]
#define repeatRFwMQTT & #define repeatIRwMQTT
