### ISSUE TITLE
ZactuatorONOFF, issue to connect to MQTT broker on UNO + Advanced network config

### ISSUE THREAD

**Issue by salvq** [1technophile/OpenMQTTGateway#270]
Issue to connect to MQTT broker when ZactuatorONOFF defines used, rest defines commented out. MQTT publish does not work, omg is trying to connect to broker in loop without sucess
![image](https://user-images.githubusercontent.com/43242348/45566862-43dd2780-b858-11e8-833a-38f555c6b641.png)

When disable ZactuatorONOFF and uncomment DHT (rest defines are commented out), no problem to connect to broker and working just fine.
![image](https://user-images.githubusercontent.com/43242348/45567039-e2698880-b858-11e8-87ad-c8172c8006dc.png)

**Comment by salvq** [comment]
I am having Arduino UNO, W5100 shield, if you need any addtional information just let me know

OMG_VERSION 0.8
char mqtt_user[20] = "123"; // not compulsory only if your broker needs authentication
char mqtt_pass[20] = "456"; // not compulsory only if your broker needs authentication
char mqtt_server[40] = "192.168.1.112";
char mqtt_port[6] = "1883";

const byte ip[] = { 192, 168, 1, 114 }; //ip adress
const byte gateway[] = { 192, 168, 1, 59 }; //ip adress, if first value is different from 0 advanced config network will be used and you should fill gateway & dns
const byte Dns[] = { 192, 168, 1, 59 }; //ip adress, if first value is different from 0 advanced config network will be used and you should fill gateway & dns
const byte subnet[] = { 255, 255, 255, 0 }; //ip adress

**Comment by 1technophile** [comment]
@salvq do you have several gateways called OpenMQTTGateway (or with the same name)

**Comment by salvq** [comment]
Just one overall, I have been switching between DHT and ONOFF on the same GW.

**Comment by 1technophile** [comment]
Could you try others pins like 8, 9 or 2 for ACTUATOR_ONOFF_PIN?

**Comment by salvq** [comment]
Just did, same over and over again, strange thing is it will not even finish sentence like in sketch trc(F("ZactuatorONOFF setup done ")); ...just ZactuatorONOFF setup

![image](https://user-images.githubusercontent.com/43242348/45572617-0b464980-b86a-11e8-92b9-d2e9550017a4.png)

![image](https://user-images.githubusercontent.com/43242348/45572621-0ed9d080-b86a-11e8-8f03-32de8c02799e.png)

![image](https://user-images.githubusercontent.com/43242348/45572623-113c2a80-b86a-11e8-8d6b-a53fcf1e7e5c.png)

**Comment by salvq** [comment]
Let me also try use MEGA instead of UNO to see if any difference...

**Comment by salvq** [comment]
It is related to UNO, with same settings just different board arduino MEGA it is working fine.

- UNO (DHT working OK, ONOFF can not get connected)
- MEGA (DHT working OK, ONOFF working OK)

![image](https://user-images.githubusercontent.com/43242348/45573116-ce7b5200-b86b-11e8-8618-68f6644ac2af.png)

**Comment by 1technophile** [comment]
Could you give your compilation results on UNO (the end of compilation messages) like remaininh memory ...

**Comment by salvq** [comment]
Here you go. I also did a test with IP settings and looks like it works if GW and DNS are 0's. Please verify from your end how this is related / could be automated otherwise add comment to IP addresses to leave 0's for UNO as default...

Fixed IP settings (can not get connection up with UNO)
![image](https://user-images.githubusercontent.com/43242348/45590889-eb835400-b943-11e8-930c-0f285dca4486.png)

Gateway and DNS to zero (working ok with UNO)
![image](https://user-images.githubusercontent.com/43242348/45590893-06ee5f00-b944-11e8-9647-5e779971c4f2.png)

**Comment by salvq** [comment]
Here you go. I also did a test with IP settings and looks like it works if GW and DNS are 0's. Please verify from your end how this is related / could be automated otherwise add comment to IP addresses to leave 0's for UNO as default...

Fixed IP settings (can not get connection up with UNO)
![image](https://user-images.githubusercontent.com/43242348/45590957-1fab4480-b945-11e8-8c52-e0913ab1ee34.png)


Gateway and DNS to zero (working ok with UNO)
![image](https://user-images.githubusercontent.com/43242348/45590937-bfb49e00-b944-11e8-9e8e-0214110da623.png)
