### ISSUE TITLE
Pins - Wemos D1?

### ISSUE THREAD

**Issue by PaulHam211** [1technophile/OpenMQTTGateway#286]
What pins do the below relate to on a Wemos D1 Mini?

> /*-------------DEFINE PINs FOR STATUS LEDs----------------*/
> #define led_receive 40
> #define led_send 42
> #define led_error 44

**Comment by 1technophile** [comment]
You don't have such pin numbers in wemos d1 mini, you have to change to the pin numbers you would like.

**Comment by 1technophile** [comment]
I m closing the issue, if you have other questions please prefer asking into the forum
