### ISSUE TITLE
Used ESP8266_OpenMQTTGateway.ino.bin.zip and ESP8266 open an AP, but I need a password

### ISSUE THREAD

**Issue by BigDi** [1technophile/OpenMQTTGateway#292]
This not a bug. I searched but I can't find any information about the last release ESP8266_OpenMQTTGateway.ino.bin.zip. I can flashed sucessfully and the ESP created an access point with name OpenMQTTGateway. But it is WPA2 and I need a password...

**Comment by 1technophile** [comment]
It is "your_password"

**Comment by nice2943** [comment]
thx~
