### ISSUE TITLE
new request: Compatibility by Domoticz

### ISSUE THREAD

**Issue by ar99** [1technophile/OpenMQTTGateway#317]
Hi.
Trying to connect some sensors to domoticz trought MQTTgateway, but domoticz needs a JSON format.
More info here: https://www.domoticz.com/wiki/MQTT

**Comment by 1technophile** [comment]
Hello,

Json publishing and receiving is available in v0.9beta, you can test it if you want in the master branch, nevertheless I don't think it respects the domoticz standard.

**Comment by csigabit** [comment]
I suggest to use Node-Red between OpenMQTTGateway and domoticz.

**Comment by 1technophile** [comment]
I'm closing this issue, if you need other info don't hesitate to reply
