### ISSUE TITLE
RF raw sending oddity

### ISSUE THREAD

**Issue by indykoning** [1technophile/OpenMQTTGateway#326]
**Describe the bug**
I am trying to send raw rf data with the sonoff rf bridge, so first i subscribed to mqtt topic `home/openMQTTGateway/SRFBtoMQTT/Raw` and recieve my raw data. However when i try to send it using `home/OpenMQTTGateway/commands/MQTTtoSRFB/Raw` [as shown here](https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-SRFB) with the raw payload i recieve this exact payload on `home/openMQTTGateway/SRFBtoMQTT` However not on `home/openMQTTGateway/SRFBtoMQTT/Raw` and i dont recieve the correct code on `home/openMQTTGateway/SRFBtoMQTT`

**To Reproduce**
1. Publish to 'home/OpenMQTTGateway/commands/MQTTtoSRFB/Raw'
2. Subscribe on 'home/openMQTTGateway/SRFBtoMQTT and home/openMQTTGateway/SRFBtoMQTT/Raw'
3. See error

**Expected behavior**
I expected this raw data to be sent by the RF bridge in a way that i recieve the raw value back on the raw topic and get a smaller code on the `SRFBtoMQTT` not the raw code i tried to send out.
However i recieve the raw value on `SRFBtoMQTT` and i recieve nothing on the `SRFBtoMQTT/Raw` topic

**Screenshots**
What i recieve when i click a button on my rf remote
![data-recieved-from-remote](https://user-images.githubusercontent.com/15870933/49697274-79728200-fbb5-11e8-867e-53e65c60ffb1.png)
What i recieve by sending and recieving the same raw code from the rf bridge
![recieved-from-sending](https://user-images.githubusercontent.com/15870933/49697283-973fe700-fbb5-11e8-8191-dfc636f85979.png)

**Comment by 1technophile** [comment]
Did you get this behaviour with v0.8.1 or v0.9beta?

**Comment by indykoning** [comment]
I am pretty sure Version 0.8.1 however i have had this setup for a couple of weeks now, and tried tackling some pesky rf recievers just now.

Is there any way to check which version is installed?

**Comment by indykoning** [comment]
I was still on V0.7 waiting for V0.8.1 (or the one that fixes issue [#310)](https://github.com/1technophile/OpenMQTTGateway/issues/310)

So i might try updating to this new version, Is it possible to do this OTA? i've noticed that the arduino ide is discovering it

**Comment by 1technophile** [comment]
yes you should be able to do it by OTA, you can try with v0.8.1

**Comment by indykoning** [comment]
I've just updated to V0.8.1 using the bin file (i dont have all the required arduino libraries on hand) and the sonoff doesn't seem to send out a wifi network to set it up further... is there maybe a way to set up the mqtt server and router information via the RX and TX pins and an app like Termite?

**Comment by indykoning** [comment]
I got it connecting again by entering my wifi and mqtt broker credentials into the source code, compiling that and uploading it. However it doesn't seem to send any RF messages it recieves via mqtt or returning the RF codes to MQTT. I can see the red RF light light up when i press a button on my RF remote. But i don't see anything show up on the mqtt topics. When the device boots i get the version information etc. And i periodically get mqtt messages about the network connectivity, but no RF signals.

Did i forget something? To enable a module/set a pin for the Sonoff RF Bridge?

**Comment by 1technophile** [comment]
Did you uncommented ZgatewaySRFB in user_config.h and commented the others gateways?
