### ISSUE TITLE
cannot receive or send rf codes

### ISSUE THREAD

**Issue by bachoo786** [1technophile/OpenMQTTGateway#328]
hi 

so I am subscribed to home/OpenMQTTGateway/433toMQTT topic and I can receive some rf but I get lots of characters i expect to receive digits only.

so my results that I get is: {"value":9313457,"protocol":1,"length":24,"delay":333}

I only expect to receive 9313457.

Can someone help me please? How can I just get 9313457?

thanks.

**Comment by 1technophile** [comment]
If you are using OMG for production use you should use V0.8 and not v0.9beta.

If you want to stay with beta just comment jsonpublishing and uncomment simplepublishing in [user_config.h](https://github.com/1technophile/OpenMQTTGateway/blob/ed44418a7f869d00bf770c3cce2687e43107e0db/User_config.h#L126)

**Comment by bachoo786** [comment]
is there any hiccups with v0.9beta? can I just use it as normal?

**Comment by 1technophile** [comment]
It could, that s why it is tagged as beta. For your day to day use uou should take v0.8

**Comment by bachoo786** [comment]
right lets see thank you
