### ISSUE TITLE
Make Gateway_Name a variable stored in config file on FS

### ISSUE THREAD

**Issue by mpember** [1technophile/OpenMQTTGateway#338]
I may have overlooked something obvious, but is there any reason why **Gateway_Name** cannot be made a variable stored in the json file that is created via the initial WiFiManager portal?

I understand that it is possible to change the setting in the header file.  I am just wondering if there is a functionality / usability / programming reason for this value to have been left hard-coded in the compiled binary.

It would be handy to have a single binary that can be used across any of my deployed devices.

**Comment by 1technophile** [comment]
done
