### ISSUE TITLE
valueAsASubject breaks duplication check

### ISSUE THREAD

**Issue by PeeVv** [1technophile/OpenMQTTGateway#346]
When setting valueAsASubject to true  (#298), the duplication check breaks and RF -> Mqtt sends multiple messages (+- 30 in 3 seconds in my case) to the broker. I run 0.9beta (built from source) on a NodeMCU v1.0. Setting valueAsASubject to false fixes it, but I would like to use it to prevent the Home Assistant 'No matching payload found for entity' errors.

**Comment by 1technophile** [comment]
an [enhancement ](https://github.com/1technophile/OpenMQTTGateway/commit/27fa38ec45351bcb4e3c1dc9b4b51b12de19b313)has been apply to duplicate in master, could you check if it correct your issue?

Alternatively please find a [topic ](https://community.home-assistant.io/t/mqtt-py-log-warning-no-matching-payload-found-for-entity/42995/43)discussing about how to avoid the HASS errors

**Comment by PeeVv** [comment]
Ah yes, it works now, many thanks!
