### ISSUE TITLE
Wemos d1 mini

### ISSUE THREAD

**Issue by scouseboy999** [1technophile/OpenMQTTGateway#348]
Hi,

I have successfully flashed the D12 mini with the OpenMQTTGateway V0.9beta, however my mqtt server ip address in incorrect.  the unit does not seem to drop back into ap mode to allow me to correct them.

Grateful for a pointer.  I suspect it is something to do with maxMQTTretrys (set to 4 ) in User_config.h but this does not seem to affect it.

Regards

Stuary

**Comment by 1technophile** [comment]
Hello, you should have an option in arduino ide in the tools menu to erase your flash when uploading.

**Comment by scouseboy999** [comment]
Hi,
Thanks for the pointer.  Still learning all about this.

I will mark as closed.

Cheers
