### ISSUE TITLE
Enable wifiManager.setConfigPortalTimeout(xxxx) to avoid OMG issues after a MQTT server restart 

### ISSUE THREAD

**Issue by ctripodi** [1technophile/OpenMQTTGateway#350]
Hello @1technophile , I has been using this excellent project for the last year. (modules enabled RF433, BT, IR, DHT)
It is working fine, however I could see that sometimes after a power blackout, OMG start more quickly that the MQTT server, so, OMG start the configuration portal, and stay  in this status, until a new restart of OMG.
So, I guess that maybe you can add this setting to your code wifiManager.setConfig Portal Timeout(your_config_seconds);
Regards.

**Comment by odis68** [comment]
I also watch it.

**Comment by 1technophile** [comment]
done
