### ISSUE TITLE
jsonPublishing true // maybe misleading

### ISSUE THREAD

**Issue by AKA-47** [1technophile/OpenMQTTGateway#352]
Its a little strange that you have to comment the setting instead setting it to false.
maybe mention this in the code instead only on the wiki.

#define jsonPublishing true //comment if you don't want to use Json publishing (one topic for all the parameters)

**Comment by AKA-47** [comment]
ok. found my problem...
second param is simple publishing which needs to be set to true

**Comment by debuglevel** [comment]
I think this is a valid issue. The value `true` suggest that `false` will deactivate it. Even if the wiki mentions it, the code should be clear IMHO.

**Comment by debuglevel** [comment]
Relates to #1141
