### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by maxi1134** [1technophile/OpenMQTTGateway#353]
I see lots of mentions of the #command topic, But not explanation on what it is. Or what commands we can use.

**Comment by 1technophile** [comment]
> Or what commands we can use.

Did you read the wiki?

**Comment by 1technophile** [comment]
You are willing to use an open source software on which people are working on their free time. If you are not ready to spend time to search things you should better go for a commercial alternative.

**Comment by maxi1134** [comment]
Sorry to bother. I'll leave.
