### ISSUE TITLE
MQTT server settings are not saved in the WIFI manager.

### ISSUE THREAD

**Issue by odis68** [1technophile/OpenMQTTGateway#354]
version 0.9. MQTT server settings are not saved in the WIFI manager. ESP8266 After a power failure, the settings return to 192.168.1.17. On version 0.8 this was not observed.

**Comment by 1technophile** [comment]
does it pop up the web page for setting the credential also?

**Comment by odis68** [comment]
Yes, where is the installation of the WiFi ssid address MQTT login and password. After installation, everything connects to WiFi and the broker and then how you take off the power, everything disappears. It is interesting that when you returned to version 0.8 it was not necessary to enter the settings, restore yourself and everything connected.

**Comment by 1technophile** [comment]
the configuration for mqtt is [here](https://github.com/1technophile/OpenMQTTGateway/blob/0180a0dbd55ed8e0799e30ee84f68070a6f478fa/User_config.h#L69)

**Comment by odis68** [comment]
I take the finished firmware. bin file

**Comment by 1technophile** [comment]
Thanks for the info I will test it.

**Comment by 1technophile** [comment]
Here is my results:
-upload from Arduino IDE -> I don't reproduce the issue
-upload from esptool with the bin file present in the v0.9 release page-> There is an error when mounting the file system of the ESP

I have rebuilt the bin files,
flashed [this one](https://github.com/1technophile/OpenMQTTGateway/releases/download/v0.9/ESP8266_OpenMQTTGateway_V09_IRRFBT.ino.bin.zip)

And now there is no error of mounting FS anymore and by the way the parameters are conserved.

Please note that I have added to the release page several configuration for esp8266 (rf only, rf + ir and rf + ir + bt)

**Comment by odis68** [comment]
Thank you so much I will test as soon as I can

**Comment by 1technophile** [comment]
I close thie issue, if you reproduce it don't hesitate to reopen
