### ISSUE TITLE
Switching off HM10 LED when not connected (BLE mode)

### ISSUE THREAD

**Issue by End0rphi** [1technophile/OpenMQTTGateway#357]
I use several HM10 with ESP8266 in my home to read out MiJia devices very successfully, but had to switch off the annoying LED of the HM10 with "AT+PIO11" in ZgatewayBT.ino in line 201:

`      softserial.print(F("AT+PIO11")); // When not connected (as in BLE mode) the LED is off. When connected the LED is solid on.`

It would be "nice to have" this as a built-in feature in a future release.
It should be configurable via a DEFINE in config_BT.h for ESP8266 users.

**Comment by 1technophile** [comment]
done in development branch
