### ISSUE TITLE
Reset of MQTT values (multi gateway setup)

### ISSUE THREAD

**Issue by tunip** [1technophile/OpenMQTTGateway#359]
**Describe the bug**
I use 3 ESP32 gateways with BT only enabled for my 3 Xiaomi Flower & 7 MiJia devices.
MQTT values are cleared from time to time for the MiJia's (Flower sensors are not affected).

Custom OMG settings for each gateway: 
As I need a unique state_topic in Home Assistant, I removed the Gateway_Name from the topic in config_BT.h.
The Gateway_Name is still unique on each ESP32 in User_config.h.

**To Reproduce**
1. Publish to 'OMG/BTtoMQTT/xiaomi-mac'
2. Subscribe on 'OMG/BTtoMQTT/xiaomi-mac'
3. See screenshot

**Expected behavior**
In my example, the temperature should not be "cleared" from one of the three gateways.

**Screenshots**
![val_set](https://user-images.githubusercontent.com/11404472/52720911-d2410b00-2fa8-11e9-8d14-1cd479de8344.jpg)
![val_del](https://user-images.githubusercontent.com/11404472/52720914-d40ace80-2fa8-11e9-9f59-dd168d0e64ea.jpg)

![val_big](https://user-images.githubusercontent.com/11404472/52723029-0fa79780-2fad-11e9-8892-99afbc7be6b6.jpg)
After next scan interval they are back. But sometimes they are gone.

**Environment:**
* OpenMQTTGateway version used: V0.9

* Home Assistant sensors:
```
- platform: mqtt
  name: "ble sensor 1 temperatur"
  state_topic: "OMG/BTtoMQTT/4C65A8D065D6"
  availability_topic: "OMG/GW1/LWT"
  value_template: "{{ value_json.tem }}"
  unit_of_measurement: '°C'
  device_class: temperature
- platform: mqtt
  name: "ble sensor 1 luftfeuchtigkeit"
  state_topic: "OMG/BTtoMQTT/4C65A8D065D6"
  availability_topic: "OMG/GW1/LWT"
  value_template: "{{ value_json.hum | round(0) }}"
  unit_of_measurement: '%'
  device_class: humidity
```

**Comment by 1technophile** [comment]
Hello,

Did you identified the mqtt message that is setting the value to undefined ?

**Comment by tunip** [comment]
Gateway publish:
`OMG/BTtoMQTT/4C65A8.....8`
`{"hum":"63.5"}`
...temperature is gone

next scan...

`OMG/BTtoMQTT/4C65A8.....8`
`{"hum":"63.5","tem":"23.2"}`
...temperature is back

Why home assistant undefines temperature when only humidity is published from the gateway is a good question. If both values are published everything is fine.

Maybe I need to publish every value in a seperate topic.

**Comment by 1technophile** [comment]
We need to search on Hass doc to see if there is a way to don't reset the values when the key is not present, or maybe ask the commmunity in hass forum

**Comment by tunip** [comment]
You are right. I will ask this in the HA community. Many thx
