### ISSUE TITLE
Compile error v0.9 master

### ISSUE THREAD

**Issue by jeanniquini** [1technophile/OpenMQTTGateway#364]
#define jsonPublishing true
#define jsonReceiving true
#define ZgatewayRF     "RF"   
#define ZgatewayBT     "BT"

[log.txt](https://github.com/1technophile/OpenMQTTGateway/files/2902193/log.txt)

**Comment by 1technophile** [comment]
Did you followed the troubleshooting section:
https://github.com/1technophile/OpenMQTTGateway/wiki/Troubleshooting

As the compilation is ok with travis:
https://travis-ci.org/1technophile/OpenMQTTGateway

This is likely related to you environment, and from what I see from the libraries that you are using in particular check the version of arduinojson

**Comment by jeanniquini** [comment]
I had version 6.8.0-beta of arduinoJson. That was the problem.
Thanks.
