### ISSUE TITLE
"your_password" not working on AP

### ISSUE THREAD

**Issue by roybosch** [1technophile/OpenMQTTGateway#365]
Hi there!

I just followed this youtube video to install OpenMQTTGateway on my Sonoff bridge: https://www.youtube.com/watch?v=Ega4U1KRlso&t=472s. Everything seemed to go alright. 

Now an AP appeared in my WIFI list, but I couldn't connect to it using "your_password" as a password. After a while my telephone seemed to try it again and then the message "Internet possibly not available". I then expected a webpage would open on which I can change the settings. This didn't happen. The IP adress as shown in my AP settings was 192.168.4.2. Connecting to this IP adress did not work. The browser returned a "ERR_CONNECTION_REFUSED".

Do you have any idea what a solution could be?

Kind regards,

Roy

**Comment by 1technophile** [comment]
Hello,

I m missing infos like the version used of OMG. Did you try with another smartphone ?

**Comment by roybosch** [comment]
It seemed that after trying many times it suddenly worked. I managed to fill in the settings.
