### ISSUE TITLE
Missing unit for ADC interval

### ISSUE THREAD

**Issue by bphermansson** [1technophile/OpenMQTTGateway#370]
In config_ADC.h I see:

`#define TimeBetweenReadingADC 200`

What unit is it? ms, 200ms?

**Comment by 1technophile** [comment]
yes it is ms

**Comment by bphermansson** [comment]
So you shouldnt use a value less then 200, if you do the Esp will lose it's network connection?

**Comment by 1technophile** [comment]
yes that's why it is set to 500 per default

**Comment by 1technophile** [comment]
I close the issue if you have other question you can ask into the forum:
https://community.openmqttgateway.com
