### ISSUE TITLE
Problems with Sony IR

### ISSUE THREAD

**Issue by phlash13** [1technophile/OpenMQTTGateway#38]
I had to change the following code in "ZGatewayIR.ino" from
`  if (strstr(topicOri, "IR_Sony") != NULL){
    irsend.sendSony(data, 12);
    signalSent = true;`

to

`  if (strstr(topicOri, "IR_Sony") != NULL){
    irsend.sendSony(data, 15, 3);
    signalSent = true;`

Because my Sony AVR relies on having IR signals repeated 3 times (this is the last parameter...) and uses 15bit signals...

Maybe you could generalize the function a bit more, or is there a way to tell how many repetitions and which bit-length to use via MQTT?

**Comment by 1technophile** [comment]
there is not at this time, but it's a good idea I will add it

**Comment by wolass** [comment]
This actually is an issue in the IRremote library rather than openMQTTGateway see this issue: https://github.com/markszabo/IRremoteESP8266/issues/124

**Comment by phlash13** [comment]
This _was_ an issue with IRremote, and as you can see from my example it works with the additional parameter (which isn't used by openMQTTGateway...)!
In addition to that openMQTTGateway uses fixed bit lengths which also isn't that great...

**Comment by wolass** [comment]
U R right @phlash13.

**Comment by 1technophile** [comment]
Added:
https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-IR#send-data-by-mqtt-with-advanced-ir-parameters

Waiting for your feedback

**Comment by 1technophile** [comment]
@phlash13 could you close the issue if it is OK for you
