### ISSUE TITLE
OpenMQTTGateway does not reconnect to mqtt broker

### ISSUE THREAD

**Issue by Aggebitter** [1technophile/OpenMQTTGateway#398]
When rebooting mqtt brooker OpenMQTTGateway does not reconnect to my Mosquitto broker.
as it uses QoS 0 (fire and forget) there is no way for it to detect that the broker is down.

Could sys messages be QoS 1 (home/OpenMQTTGateway/SYStoMQTT) and if no ack response just do a reconnect to the broker ?

// Agge

**Comment by 1technophile** [comment]
I'm not reproducing this issue,

could you please follow the issue template by giving more details on, board used, gateways activated, arduino ide env, board manager version, mosquitto version ...

**Comment by 1technophile** [comment]
Reproduced if the broker is stopped a long time (several minutes)

**Comment by 1technophile** [comment]
solved in dev branch
