### ISSUE TITLE
Use status led for checking gateway state

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#40]
https://community.home-assistant.io/t/433mhz-infrared-ir-to-and-from-mqtt-on-esp8266/6779/187?u=1technophile

wifi state
mqtt connection
sending or receiving

**Comment by 8666** [comment]
I have a mod that has led for sending, receiving and disconnected from mqtt broker

**Comment by Landrash** [comment]
@1technophile If there's room for it in the memory using a WS2812 for different states would be nice. 
The http://fastled.io/ library is rather good.

**Comment by 1technophile** [comment]
@8666 it could be interesting to submit a pull request with this mod
@Landrash didnt know this driver, interesting, maybe you could open an issue as an enhancement diffenrenciated from this one. As this one was more for gateway state and the ws2812 seems more for fairy lights

**Comment by 8666** [comment]
I made pull request but I have this "The Travis CI build failed"
https://github.com/8666/OpenMQTTGateway

**Comment by 1technophile** [comment]
already integrated
