### ISSUE TITLE
Default password to OpenMQTTGateway

### ISSUE THREAD

**Issue by ecajrt** [1technophile/OpenMQTTGateway#405]
Hi

After flashing OpenMQTTGateway_1 using ESPEasy flasher the AP OpenMQTTGateway is showing as a wifi in my phone. When trying to connect it asks for password. I guess it's a default password to get in and do the initially settings. For a ESP8266 it is 'espeasy' but for this???

**Comment by akasma74** [comment]
Have your tried your_password   ? ;)

**Comment by ecajrt** [comment]
I tried it without progress. Byt this is in the installation process where
the rf bridge still act as a accesspoint. It should have its own temporary
password until I get in and configure it as a client to my own Wifi. At
least it work that way with other esp8266 stuff configured with the ESPEasy
Flasher. ...like this is.

Regards  Johan

Den tor 23 maj 2019 23:45akasma74 <notifications@github.com> skrev:

**Comment by ecajrt** [comment]
...or do you mean that your_password is the actual default password? :-)

Den fre 24 maj 2019 kl 12:48 skrev Johan Reit <johan.reit@gmail.com>:

**Comment by akasma74** [comment]
that's exactly what I mean ;)

**Comment by ecajrt** [comment]
Ok, thanks a lot! :-)

Den fre 24 maj 2019 kl 13:44 skrev akasma74 <notifications@github.com>:

**Comment by 1technophile** [comment]
The default password is also indicated into the wiki for info:
https://github.com/1technophile/OpenMQTTGateway/wiki/Module-Overview-ESP8266#software-setup

**Comment by agrynco** [comment]
What if I did not define any spasswords and not it does not aalow me to connect to the device?

**Comment by 1technophile** [comment]
If you uploaded the latest version the password is compulsory.
If you don't recall it, you can still do a new upload from scratch and Erase the flash
