### ISSUE TITLE
Can this work only for transmit?

### ISSUE THREAD

**Issue by wicadmin** [1technophile/OpenMQTTGateway#406]
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-IR-Send-and-Receive

Would this work if I only integrate the IR diode part to transmit? The idea is to send the IR code via MQTT from HA system and have it send to TV via IR.

Please advise.

Thank you.

**Comment by 1technophile** [comment]
yes it will work if you set up only the IR diode for transmitting

**Comment by wicadmin** [comment]
Great....thank you.
