### ISSUE TITLE
infrared receiver

### ISSUE THREAD

**Issue by edgiru** [1technophile/OpenMQTTGateway#416]
What element (infrared receiver) is used in your project? I did not find a model in the wiki description.

**Comment by 1technophile** [comment]
Hello,

For this kind of discussion, you should go to http://community.openmqttgateway.com
You can use this kind of module:
https://www.banggood.com/Mini-38KHz-IR-Infrared-Transmitter-Module-IR-Infrared-Receiver-Sensor-Module-For-Arduino-RPI-STM32-p-1066428.html?rmmds=search&cur_warehouse=CN
