### ISSUE TITLE
Support for WT0124 Pool Thermometer (RF 433)

### ISSUE THREAD

**Issue by ggggh** [1technophile/OpenMQTTGateway#423]
WT0124 Pool Thermometer (RF 433) traffic is not captured by RF or Pilight modules.  When using an SDR running rtl_433 traffic is correctly captured and decoded.

Would like for support to be added for the device, and would be able to provide raw signal info as needed.

**Comment by 1technophile** [comment]
Could you provide raw info and corresponding values to see how it looks like?

**Comment by 1technophile** [comment]
hmm, I'm closing this issue as it is also discussed here:
https://community.openmqttgateway.com/t/pool-temp-433mhz/474/6
