### ISSUE TITLE
Make build reproducible / add library version to platformio.ini

### ISSUE THREAD

**Issue by Rotzbua** [1technophile/OpenMQTTGateway#427]
**Is your feature request related to a problem? Please describe.**

Make build reproducible. The libraries in `platformio.ini` do not contain a version. If a library breaks backwards compatibility, the project will not compile or work.

**Describe the solution you'd like**

Add library version to `platformio.ini`.
https://github.com/1technophile/OpenMQTTGateway/blob/development/platformio.ini

**Comment by 1technophile** [comment]
done
