### ISSUE TITLE
OBD2 support?

### ISSUE THREAD

**Issue by fragolinux** [1technophile/OpenMQTTGateway#429]
hi, can't find any info in blog/forum/issues/wiki about support for cheap obd2 adapters like this one, are they usable with your software? I'd like to check my battery levels, for example... thanks in advance :)

https://www.banggood.com/V1_5-Mini-ELM327-OBD2-II-Diagnostic-Car-Auto-Interface-Scanner-with-Bluetooth-Function-p-1024834.html

**Comment by 1technophile** [comment]
OBD2 is not supported for the moment
