### ISSUE TITLE
Is it possible create some little rules? 

### ISSUE THREAD

**Issue by itProfi** [1technophile/OpenMQTTGateway#432]
Helllo, Florian! Is it possible to create any Rules engine inside gateway? For examle, it recieve data from Xiaomi Mijia Temperature and inside firmware (for example through mqtt, like ON_OFF Actuator) and if temp>x turn pin ON, if temp<x turn pin OFF)..
Based on this one could create a stand-alone thermostat without any IoT systems...!!
Like Tasmota rules..

**Comment by 1technophile** [comment]
Hello, not right now, but I'm interested in integrating this kind of function to OMG.
It could cover use cases also like triggering a siren when PIR sensor detect a presence.

**Comment by itProfi** [comment]
Ok, we are wait it! :)

**Comment by Legion2** [comment]
@itProfi this is simple, use your favorite programming language and connect ot the MQTT Broker. Than you can subscribe to a topic and process messages and send new messages on topics.
The MQTT Broker is the integration point of the system.

**Comment by itProfi** [comment]
@Legion2 Thanks! I know that. I want have 5-7 stand-alone thermostat without any IoT systems...!!

**Comment by Legion2** [comment]
Then you don't need OMG with a MQTT broker. You only need libraries to read the temperature and then make the simple if-then-else in Arduino code.

**Comment by akasma74** [comment]
there is also esphome that can be used with or without HA, comes with a lot of flexible configuration options and extensibility.

**Comment by itProfi** [comment]
Ok, i try...

**Comment by mpember** [comment]
ESPEasy may be better suited to your needs.
https://www.letscontrolit.com/wiki/index.php?title=Tutorial_Rules

**Comment by itProfi** [comment]
@mpember Thanks, but ESPEasy can't Xiaomi Mijia Temperature (no Bluetooth sensor)..(
