### ISSUE TITLE
multiple lora terminal in just one mqtt message

### ISSUE THREAD

**Issue by mttbx** [1technophile/OpenMQTTGateway#436]
Hi, I've wrote a mqtt server and client on the cloud. I want to communicate with the terminals in a building. I plan to use lora to construct a network in the building. My question is can I use your library to upload multiple terminal data to the cloud and control  multiple terminals  in the building from cloud in just one mqtt message? I think this may ease the pressure on the cloud.

**Comment by 1technophile** [comment]
Hi,

Please go the [forum](https://community.openmqttgateway.com) it is more dedicated to questions
