### ISSUE TITLE
 mqtt_server not declared in scope

### ISSUE THREAD

**Issue by 31warren** [1technophile/OpenMQTTGateway#437]
I am attempting setup a Pilight OMG on a modified Sonoff RF Bridge using the Arduino IDE and the latest code from GitHub. I am using main.ino from the ZgatewayPilight.

I have installed ESP8266 and WiFiManager in Arduino and have configured WiFi and MQTT settings in the config file (using a MQTT server name and commenting out the IP Address).

When I try to compile the .ino file I get the following error:

main:693:18: error: 'mqtt_server' was not declared in this scope

Any suggestions??

Thanks

**Comment by 1technophile** [comment]
Hello,
please follow the issue template, there is a lot of information missing in your issue to have an helping answer.
