### ISSUE TITLE
Release page has incorrect file name

### ISSUE THREAD

**Issue by mpember** [1technophile/OpenMQTTGateway#439]
The CODE file is named **CODE-OpenMQTTGateway-V091.zip**

Does this mean is does not contain the latest code?

**Comment by Legion2** [comment]
Yes the file name is wrong, but it contains the correct sources.

**Comment by Legion2** [comment]
@1technophile How are the files uploaded, are they generated in a CI pipeline or do you create them?

**Comment by 1technophile** [comment]
For the moment I create them but with PIO I think it could be improve

Name corrected
