### ISSUE TITLE
Outdated wiki pages

### ISSUE THREAD

**Issue by Legion2** [1technophile/OpenMQTTGateway#441]
Some wiki pages contain old information from previous versions of OMG, that are now no more valid. This includes references to moved, deleted or modified code. Some pages include broken links that resolve to 404 Not Found and some step-by-step explanations don't work with the current OMG version.
Here a list of some pages where the information is not consistent with the current status of OMG. If you find more such outdated information please post them in the comments:
- [x] [Arduino I2C-Bus Modules #Software setup](https://github.com/1technophile/OpenMQTTGateway/wiki/Arduino-I2C-Modules#software-setup)
- [x] [Module Overview ESP8266 #Software setup](https://github.com/1technophile/OpenMQTTGateway/wiki/Module-Overview-ESP8266#software-setup)
- [x] [Module Overview ESP32 #Software setup](https://github.com/1technophile/OpenMQTTGateway/wiki/Module-Overview-ESP32#software-setup)
- [x] [Decreasing Gateway SRAM usage for arduino AVR boards](https://github.com/1technophile/OpenMQTTGateway/wiki/Decreasing-Gateway-SRAM-usage-for-arduino-AVR-boards) OpenMQTTGateway.ino was renamed
- [x] [PIR Modules](https://github.com/1technophile/OpenMQTTGateway/wiki/PIR-Modules) broken links
- [x] [User guide json](https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-json) code is outdated
- [x] [User guide ADC 09](https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-ADC-09) broken links

**Comment by valdiks** [comment]
Broken link to user_config.h:
https://github.com/1technophile/OpenMQTTGateway/wiki/GSM-GPRS---2G-gateway
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-RFM69-Module
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-IR-Send-and-Receive
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-I2C-Modules
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-BT-Module
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP8266-DHT-Modules
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP32-RF-Send-and-Receive
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP32-IR-Send-and-Receive
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP32-BT-Module
https://github.com/1technophile/OpenMQTTGateway/wiki/ESP32-LORA-Module
https://github.com/1technophile/OpenMQTTGateway/wiki/Sonoff-RFB

**Comment by 1technophile** [comment]
Done, if someone wants to do a review don't hesitate.

**Comment by Legion2** [comment]
You only removed the setup parts?

**Comment by 1technophile** [comment]
For wifi and mqtt it is on a [single ](https://github.com/1technophile/OpenMQTTGateway/wiki/Wifi-and-mqtt-connection) location.

For platformio it is [here ](https://github.com/1technophile/OpenMQTTGateway/wiki/Platformio-ini-configuration)

These 2 links are called from the [How to start](https://github.com/1technophile/OpenMQTTGateway/wiki/HowToStart)

**Comment by 1technophile** [comment]
I have made a complete rework of the doc below:
https://1technophile.github.io/OpenMQTTGateway

There can be some improvments or comments to add. If you find some don't hesitate to submit a PR to the gh-pages branch.
