### ISSUE TITLE
ESP32 RF and IR Pin identical

### ISSUE THREAD

**Issue by h4nc** [1technophile/OpenMQTTGateway#443]
Not really a bug, but don’t know where to put it.

I noticed that the IR and RF receive Pins are identical at 27.

So I set IR receive to 26 and it works. I would suggest changing that in config_IR.h

**Comment by 1technophile** [comment]
Well seen ! 
Do you have other working pins for ir receive that we could suggest in complement ?

**Comment by h4nc** [comment]
I did not test other pins, but is it necessary? It works with 26, or is it used for something else?

**Comment by 1technophile** [comment]
If you have some times it can help other users that doesn't have free the 26 or 27 pins.

**Comment by h4nc** [comment]
Will test it if I have some spare time.

**Comment by 1technophile** [comment]
update done
