### ISSUE TITLE
 compilation error IR

### ISSUE THREAD

**Issue by clubbit** [1technophile/OpenMQTTGateway#460]
Good afternoon, it says that the error is in line 111 "ZgatewayIR"

String hex = resultToHexidecimal(&results);

I use libraries from your set.

Arduino: 1.8.1 (Windows 10), Плата:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino: In function 'boolean reconnect()':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:151:57: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       pub(will_Topic,Gateway_AnnouncementMsg,will_Retain);

                                                         ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:151:57: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:153:48: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       pub(version_Topic,OMG_VERSION,will_Retain);

                                                ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:153:48: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino: In function 'void stateMeasures()':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:763:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       pub(subjectSYStoMQTT,JSONmessageBuffer);

                                             ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino: In function 'void pub(char*, long int)':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1135:31: warning: conversion lacks type at end of format [-Wformat=]

     sprintf(val, "%l", payload);

                               ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1135:31: warning: too many arguments for format [-Wformat-extra-args]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1135:31: warning: conversion lacks type at end of format [-Wformat=]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1135:31: warning: too many arguments for format [-Wformat-extra-args]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino: In function 'void pub(char*, double)':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1141:31: warning: format '%d' expects argument of type 'int', but argument 3 has type 'double' [-Wformat=]

     sprintf(val, "%d", payload);

                               ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\OpenMQTTGateway_v092.ino:1141:31: warning: format '%d' expects argument of type 'int', but argument 3 has type 'double' [-Wformat=]

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino: In function 'void IRtoMQTT()':

ZgatewayIR:111: error: 'resultToHexidecimal' was not declared in this scope

       String hex = resultToHexidecimal(&results);

                                                ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:148:35: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

         pub(subjectIRtoMQTT,IRdata);

                                   ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:153:42: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

             pub(subjectMQTTtoIR,MQTTvalue);

                                          ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino: In function 'void MQTTtoIR(char*, char*)':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:171:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

     for(int i = 0; i < s; i++)

                        ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:187:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

       for(int i = 0; i < s; i++)

                          ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:192:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

         if ((datacallback[i] == ',') || (i == s - 1))

                                                   ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:214:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

       for(int i = 0; i < s; i++)

                          ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:219:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

         if ((datacallback[i] == ',') || (i == s - 1))

                                                   ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:265:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       pub(subjectGTWIRtoMQTT, datacallback);

                                           ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino: In function 'void MQTTtoIR(char*, ArduinoJson::JsonObject&)':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:296:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

             for(int i = 0; i < s; i++)

                                ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:309:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

               for(int i = 0; i < s; i++)

                                  ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:314:50: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

                 if ((raw[i] == ',') || (i == s - 1))

                                                  ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:336:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

             for(int i = 0; i < s; i++)

                                ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:341:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

               if ((raw[i] == ',') || (i == s - 1))

                                                ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:366:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

             pub(subjectGTWIRtoMQTT, IRdata);

                                           ^

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino: In function 'boolean sendIdentifiedProtocol(const char*, long unsigned int, const char*, unsigned int, uint16_t)':

C:\Users\xpiri\Documents\Arduino\OpenMQTTGateway_v092\ZgatewayIR.ino:380:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

     while (strlen(pointer) > 0 && i < valueBITS) {

                                       ^

ZgatewayIR:505: error: 'kCoolixBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kCoolixBits;

                                         ^

ZgatewayIR:512: error: 'kRCMMBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kRCMMBits;

                                         ^

ZgatewayIR:526: error: 'kGicableBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kGicableBits;

                                         ^

ZgatewayIR:527: error: 'kGicableMinRepeat' was not declared in this scope

         if (valueRPT == repeatIRwNumber) valueRPT = std::max(valueRPT, kGicableMinRepeat);

                                                                        ^

ZgatewayIR:534: error: 'kSherwoodBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kSherwoodBits;

                                         ^

ZgatewayIR:535: error: 'kSherwoodMinRepeat' was not declared in this scope

         if (valueRPT == repeatIRwNumber) valueRPT = std::max(valueRPT, kSherwoodMinRepeat);

                                                                        ^

ZgatewayIR:542: error: 'kMitsubishiBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMitsubishiBits;

                                         ^

ZgatewayIR:543: error: 'kMitsubishiMinRepeat' was not declared in this scope

         if (valueRPT == repeatIRwNumber) valueRPT = std::max(valueRPT, kMitsubishiMinRepeat);

                                                                        ^

ZgatewayIR:550: error: 'kNikaiBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kNikaiBits;

                                         ^

ZgatewayIR:557: error: 'kMideaBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMideaBits;

                                         ^

ZgatewayIR:564: error: 'kMagiquestBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMagiquestBits;

                                         ^

ZgatewayIR:571: error: 'kLasertagBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kLasertagBits;

                                         ^

ZgatewayIR:578: error: 'kCarrierAcBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kCarrierAcBits;

                                         ^

ZgatewayIR:585: error: 'kMitsubishiBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMitsubishiBits;

                                         ^

ZgatewayIR:586: error: 'kMitsubishiMinRepeat' was not declared in this scope

         if (valueRPT == repeatIRwNumber) valueRPT = std::max(valueRPT, kMitsubishiMinRepeat);

                                                                        ^

ZgatewayIR:593: error: 'kAiwaRcT501Bits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kAiwaRcT501Bits;

                                         ^

ZgatewayIR:594: error: 'kAiwaRcT501MinRepeats' was not declared in this scope

         if (valueRPT == repeatIRwNumber) valueRPT = std::max(valueRPT, kAiwaRcT501MinRepeats);

                                                                        ^

ZgatewayIR:601: error: 'kSanyoLC7461Bits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kSanyoLC7461Bits;

                                         ^

ZgatewayIR:608: error: 'kDaikinStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kDaikinStateLength;

                                         ^

ZgatewayIR:615: error: 'kKelvinatorStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kKelvinatorStateLength;

                                         ^

ZgatewayIR:622: error: 'kMitsubishiACStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMitsubishiACStateLength;

                                         ^

ZgatewayIR:629: error: 'kSanyoLC7461Bits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kSanyoLC7461Bits;

                                         ^

ZgatewayIR:636: error: 'kGreeStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kGreeStateLength;

                                         ^

ZgatewayIR:643: error: 'kArgoStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kArgoStateLength;

                                         ^

ZgatewayIR:650: error: 'kTrotecStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kTrotecStateLength;

                                         ^

ZgatewayIR:657: error: 'kToshibaACBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kToshibaACBits;

                                         ^

ZgatewayIR:670: error: 'kMagiquestBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kMagiquestBits;

                                         ^

ZgatewayIR:677: error: 'kHaierACStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kHaierACStateLength;

                                         ^

ZgatewayIR:684: error: 'kHitachiAc2StateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kHitachiAc2StateLength;

                                         ^

ZgatewayIR:691: error: 'kHitachiAc2StateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kHitachiAc2StateLength;

                                         ^

ZgatewayIR:698: error: 'kHitachiAc2StateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kHitachiAc2StateLength;

                                         ^

ZgatewayIR:705: error: 'kGicableBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kGicableBits;

                                         ^

ZgatewayIR:712: error: 'kHaierACYRW02StateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kHaierACYRW02StateLength;

                                         ^

ZgatewayIR:713: error: 'class IRsend' has no member named 'sendHaierACYRW02'

         irsend.sendHaierACYRW02(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:719: error: 'kWhirlpoolAcStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kWhirlpoolAcStateLength;

                                         ^

ZgatewayIR:720: error: 'class IRsend' has no member named 'sendWhirlpoolAC'

         irsend.sendWhirlpoolAC(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:726: error: 'kSamsungAcStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kSamsungAcStateLength;

                                         ^

ZgatewayIR:727: error: 'class IRsend' has no member named 'sendSamsungAC'

         irsend.sendSamsungAC(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:733: error: 'kLutronBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kLutronBits;

                                         ^

ZgatewayIR:734: error: 'class IRsend' has no member named 'sendLutron'

         irsend.sendLutron(data, valueBITS, valueRPT);

                ^

ZgatewayIR:740: error: 'kElectraAcStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kElectraAcStateLength;

                                         ^

ZgatewayIR:741: error: 'class IRsend' has no member named 'sendElectraAC'

         irsend.sendElectraAC(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:747: error: 'kPanasonicAcStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kPanasonicAcStateLength;

                                         ^

ZgatewayIR:748: error: 'class IRsend' has no member named 'sendPanasonicAC'

         irsend.sendPanasonicAC(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:754: error: 'kPioneerBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kPioneerBits;

                                         ^

ZgatewayIR:755: error: 'class IRsend' has no member named 'sendPioneer'

         irsend.sendPioneer(data, valueBITS, valueRPT);

                ^

ZgatewayIR:761: error: 'kLgBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kLgBits;

                                         ^

ZgatewayIR:762: error: 'class IRsend' has no member named 'sendLG2'

         irsend.sendLG2(data, valueBITS, valueRPT);

                ^

ZgatewayIR:768: error: 'class IRsend' has no member named 'sendMWM'

         irsend.sendMWM(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:774: error: 'kDaikin2StateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kDaikin2StateLength;

                                         ^

ZgatewayIR:775: error: 'class IRsend' has no member named 'sendDaikin2'

         irsend.sendDaikin2(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:781: error: 'kVestelAcBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kVestelAcBits;

                                         ^

ZgatewayIR:782: error: 'class IRsend' has no member named 'sendVestelAc'

         irsend.sendVestelAc(data, valueBITS, valueRPT);

                ^

ZgatewayIR:788: error: 'kSamsung36Bits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kSamsung36Bits;

                                         ^

ZgatewayIR:789: error: 'class IRsend' has no member named 'sendSamsung36'

         irsend.sendSamsung36(data, valueBITS, valueRPT);

                ^

ZgatewayIR:795: error: 'kTcl112AcStateLength' was not declared in this scope

         if (valueBITS == 0) valueBITS = kTcl112AcStateLength;

                                         ^

ZgatewayIR:796: error: 'class IRsend' has no member named 'sendTcl112Ac'

         irsend.sendTcl112Ac(dataarray, valueBITS, valueRPT);

                ^

ZgatewayIR:802: error: 'kTecoBits' was not declared in this scope

         if (valueBITS == 0) valueBITS = kTecoBits;

                                         ^

ZgatewayIR:803: error: 'class IRsend' has no member named 'sendTeco'

         irsend.sendTeco(data, valueBITS, valueRPT);

                ^

exit status 1
'resultToHexidecimal' was not declared in this scope

**Comment by clubbit** [comment]
updated the library to the latest version. everything worked

**Comment by 1technophile** [comment]
Good !
