### ISSUE TITLE
Pilight build not working?

### ISSUE THREAD

**Issue by klockie86** [1technophile/OpenMQTTGateway#462]
Hello,

First of all, what as nice project, very easy to setup. Flashing my nodemcu was done in a few seconds.

However I'm having a small issue with a pilight build.
I've forked the development branch, then did my settings in User_config.h. 
I removed the comment on "#define ZgatewayPilight "Pilight" //ESP8266, Arduino, ESP32".
Then I compiled the project with "PIO Upload (nodemcuv2-rf)"

After setting up wifi and mqtt, after booting the following message appears in the serial console:
`
....
RF setup ok
ZgatewayPilight setup cannot be done, comment first ZgatewayRF && ZgatewayRF2 && ZgatewayRF315
....
`
However I have the ZgatewayRF & ZgatewayRF2 commented, ZgatewayRF315 is not pressent at all in my user_config.

**Comment by klockie86** [comment]
Nevermind, i used the wrong platformio.ini file. So I didn't have the "PIO Upload (nodemcuv2-pilight option)"

**Comment by TopdRob** [comment]
I'm having this issue as well. I was wondering what you exactly did to solve it?

**Comment by klockie86** [comment]
For building use; "nodemcuv2-pilight". This includes the right libraries.
