### ISSUE TITLE
Don't expose sensitive details in serial log

### ISSUE THREAD

**Issue by brainboutique** [1technophile/OpenMQTTGateway#463]
Current: 
*WM: [3] Method: POST
*WM: [2] Parameters 
*WM: [2] -------------------- 
*WM: [2] server: ******.local
*WM: [2] port: 1883
*WM: [2] user: your_username
*WM: [2] pass: your_password
*WM: [2] -------------------- 
...
*WM: [1] Connecting to new AP: *****
*WM: [3] Using Password: ******

I.e. whoever gains physical access to the device can snoop wifi credentials.

Expected: Do NOT show any sensitive information on serial port for standard binaries...

**Comment by 1technophile** [comment]
These traces are coming from Wifi Manager library, I think the request should be submitted directly to this repository:
https://github.com/tzapu/WiFiManager
