### ISSUE TITLE
Adding DHT sensor

### ISSUE THREAD

**Issue by BertrumUK** [1technophile/OpenMQTTGateway#47]
I have enabled the sensor in the User_config.h "#define ZsensorDHT" but I cannot see where the pins are enabled for the dht11 to be picked up from?

**Comment by BertrumUK** [comment]
RF is working a treat in HA but I want to remove the wiring from my Raspberry PI 3 and run them from a NodeMCU via MQTT.

**Comment by 1technophile** [comment]
Data pin for DHT is defined into ZsensorDHT.ino line 30, for nodemcu you can choose maybe GPIO15 which correspond to D8 by writing
`DHT dht(15,DHT11);`

After you connect DHT Vcc to 5V power source and the ground to the ground power source

**Comment by BertrumUK** [comment]
Thanks for that. Will changing to DHT22 allow that dht version to work?

**Comment by 1technophile** [comment]
yes just replace DHT11 by 
`DHT dht(15,DHT22);`

**Comment by BertrumUK** [comment]
Thank you very much.
