### ISSUE TITLE
Pilight command message json string

### ISSUE THREAD

**Issue by AlmightyFrog** [1technophile/OpenMQTTGateway#483]
This Issue is related to #387, but looking at command side.
As per https://github.com/1technophile/OpenMQTTGateway/wiki/User-guide-PiLight-09 you can see it expects for commands a json string in message.

I currently give both OMG and NodeRed a new try. This is no big issue, but a little weird. Let's just take following function node code
```
if (msg.payload.message.systemcode == 25)
{
    if (msg.payload.message.unitcode == 1)
    {
        var str = {
                "id" : 845,
                "unit" : 0
            };
        
        if (msg.payload.message.state == "on")
        {
            str.on = 1;
        }
        else
        {
            str.off = 1;
        }

        var newMsg = { payload: {
            "message": JSON.stringify(str),
            "protocol":"quigg_gt9000",
        } };

        return newMsg;
    }
}
```

For it to be working with OMG I need to add the JSON.stringify(), without it it would be perfectly fine JSON still, but not accepted by OMG.

First output is with JSON.stringify():
```
Hey I got a callback 
MQTTtoPilight json data analysis
MQTTtoPilight msg & protocol ok
Adv data MQTTtoPilight push state via PilighttoMQTT
Pub json into:
home/OpenMQTTGateway/PilighttoMQTT
{"message":"{\"id\":845,\"unit\":0,\"off\":1}","protocol":"quigg_gt9000"}
Pub data per topic
message
{"id":845,"unit":0,"off":1}
protocol
quigg_gt9000
```

Second output is without JSON.stringify():
```
Hey I got a callback 
MQTTtoPilight json data analysis
MQTTtoPilight failed json read
protocol is not available
```
Please also note, that error message "protocol is not available" is missleading.

Is it planned to get this fixed in future?

Edit: For sake of completeness, I an using commit 1c147e3289f73aa5dc49248475043bc39ca302cb  which is as per now latest development HEAD.

**Comment by 1technophile** [comment]
Thanks for reporting this, I will take a look
