### ISSUE TITLE
make call

### ISSUE THREAD

**Issue by utya1988** [1technophile/OpenMQTTGateway#492]
Hello. Can i make call using mqtt using 2g gateway? thanks
If not could you explan, how can i make it.

**Comment by 1technophile** [comment]
Hello,

Making a call is not currently supported (only sending and receiving SMS)

**Comment by utya1988** [comment]
Maybe. I can change some lines ot the code to implement this feature?

**Comment by 1technophile** [comment]
Yes , here is the methods available on the library used
https://github.com/skorokithakis/A6lib/blob/master/A6lib.h

**Comment by 1technophile** [comment]
For my curiosity could you share the use case behind your request?

**Comment by utya** [comment]
I have the gate for parking. For open the gate i should make the call.

**Comment by 1technophile** [comment]
You could use the SMS function of the library to trigger your gate opening or closing, also you may take a look to the library below:
https://github.com/vshymanskyy/TinyGSM
