### ISSUE TITLE
Led status pin NodeMCU

### ISSUE THREAD

**Issue by byte4geek** [1technophile/OpenMQTTGateway#495]
Hi,

i have no problem whit the project, i have all working and correctly integrated with home assistant but...
...what pin can i use on NodeMCU to connect the leds to see the status?

i found the lines in the User_config.h

/*-------------DEFINE PINs FOR STATUS LEDs----------------*/
#ifdef ESP8266
  #define led_receive 40
  #define led_send 42
  #define led_info 44

but i dont know the related pins.

**Comment by 1technophile** [comment]
Hello,

You can take the pins that you don't use from this sheet:
https://docs.google.com/spreadsheets/d/1_5fQjAixzRtepkykmL-3uN3G5bLfQ0zMajM9OBZ1bx0/edit#gid=1864843263

**Comment by byte4geek** [comment]
Thanks, using you docs i configured the leds
