### ISSUE TITLE
 请求添加ssd1306 Request to add ssd1306

### ISSUE THREAD

**Issue by 671792320** [1technophile/OpenMQTTGateway#497]
Thank you very much for developing this project. How can I request to add ssd1306 OLED support. Thank you

**Comment by 1technophile** [comment]
Hello,
What are the informations that you would like to display on the screen?

**Comment by 671792320** [comment]
> Hello,
> What are the informations that you would like to display on the screen?

Thank you for your reply

I want to display the received RF code and temperature and humidity code on the display,

If you can customize the display and call all the plug-in support under your project, it will be more perfect

**Comment by 1technophile** [comment]
> If you can customize the display and call all the plug-in support under your project, it will be more perfect

By plugin you mean the different activated gateways and sensors?

**Comment by 671792320** [comment]
> > If you can customize the display and call all the plug-in support under your project, it will be more perfect
> 
> By plugin you mean the different activated gateways and sensors?

Yes, I want to show some data on the OLED

**Comment by AskAlice** [comment]
still would love this

**Comment by 1technophile** [comment]
It is now possible
