### ISSUE TITLE
DHT12

### ISSUE THREAD

**Issue by RaZer0r** [1technophile/OpenMQTTGateway#498]
any possibility to add compatibility to DHT 12 sensors?

I tried just updating the DHT library to 1.3.8 and compiling works, but no data is received on the mqtt topic :(.

**Comment by 1technophile** [comment]
Hello,
did you updated the DHT library and the unified sensor one?
Alternatively once updated are you able to retrieve data with a DHT22 or 11?

**Comment by RaZer0r** [comment]
only the DHT library so far. I don't have a DHT22 or 11 available unfortunately :(

**Comment by 1technophile** [comment]
Did you try to update the unified sensor library also?

**Comment by 1technophile** [comment]
Did you tried with both libraries updated?

**Comment by 1technophile** [comment]
If you are interested in this, do not hesitate to propose a PR
