### ISSUE TITLE
Wifi disconnected

### ISSUE THREAD

**Issue by byte4geek** [1technophile/OpenMQTTGateway#516]
Hi, im running 0.9.3rc wiht RF receiver and DHT

on platformio.ino i enabled:
default_envs = nodemcuv2-rf

sometimes i find the nodeMCU halted with this continuous message on serial:

wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected

when i press reset button the system restart correctly.
Is it possible to do an automatic restart in this case?

**Comment by 1technophile** [comment]
Hi,

If you wait for several minutes, it does not reconnect automaticaly?

**Comment by byte4geek** [comment]
i'm wait for 30mins and no reconnect.

**Comment by dandresm** [comment]
Hi, same here. I have an esp32 with 0.9.3rc version and DHT, RF, RF2 and BLE enabled on it.
![Screenshot_20191230-142638__01](https://user-images.githubusercontent.com/9026548/71583937-bedf5580-2b10-11ea-9a91-2541366a75c1.jpg)
In my case, this behaviour comes from previous version.

**Comment by 1technophile** [comment]
> i'm wait for 30mins and no reconnect.

I have uploaded to a nodemcu the nodemcu-v2-rf env (v0.9.3rc).
I have stopped my wifi and here is the result from the serial monitor:
```
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
wifi disconnected
MQTT connection...
Connected to broker
Subscription OK to the subjects
Uptime (s)
234
```

It does reconnect automatically when I restart the wifi. I reproduced this behavious several times.

I also added a DHT to the NodeMCU and I also get automatic wifi reconnection:
```
Pub json into:
home/OpenMQTTGateway_ESP8266_TEST/DHTtoMQTT/dht1
{"hum":51.8,"temp":19.1}
wifi disconnected
wifi disconnected
wifi disconnected
MQTT connection...
Connected to broker
Subscription OK to the subjects
```

Could you indicate me the board used and if you are uploading by PIO or other method?

**Comment by byte4geek** [comment]
I'm using AZ-DELIVERY NodeMcu V3
im uploading the firmware using the usb port on board and the Flahs Download Tool 2.6.5.
the firmware is self compiled by ATOM.

**Comment by 1technophile** [comment]
> the firmware is self compiled by ATOM
By self compiled you mean that you compile it yourself with stock parameters of platformio.ini and user_config.h files?

**Comment by byte4geek** [comment]
Yes

**Comment by 1technophile** [comment]
I have a nodemcu v3 I will try with it

**Comment by 1technophile** [comment]
@byte4geek do you still see wifi disconnection without automatic reconnection?

**Comment by byte4geek** [comment]
I change my old Router with a Fritz!Box, more stable, this issue is not longer present

**Comment by marrobHD** [comment]
After rebooting my sonoff rf bridge it won´t connect back to WiFi.
It shows at the bottom:
`Not Connected to JK12NoT_Oben`
<img width="390" alt="779-606-max 1" src="https://user-images.githubusercontent.com/29308361/78574543-695ec700-782a-11ea-9571-7a799413e2aa.png">

**Comment by 1technophile** [comment]
Maybe wait 120s for the portal to come off, if you're access point hasn't change it should reconnect
