### ISSUE TITLE
Add OTA option for remote updating

### ISSUE THREAD

**Issue by BertrumUK** [1technophile/OpenMQTTGateway#52]
It would be a nice option to add an OTA update option so that new updates can be sent via WiFi

**Comment by jumpalottahigh** [comment]
This could be a good starting point:
https://github.com/esp8266/Arduino/tree/master/libraries/ArduinoOTA

**Comment by BertrumUK** [comment]
Looks good 😉

**Comment by PatteWi** [comment]
I already implemented it, @1technophile is testing it this weekend ;)

**Comment by BertrumUK** [comment]
Thanks Patrick. Will see how it goes then update my current config and try it myself 👍

**Comment by PatteWi** [comment]
I tested it yesterday for mine and I think it works great, but it didn`t use all gateways, just RF and IR.

**Comment by 1technophile** [comment]
Working with the full gateway thanks for the work
