### ISSUE TITLE
ZgatewayBT:453:49: error: 'class BLEAdvertisedDevice' has no member named 'getServiceDataCount'

### ISSUE THREAD

**Issue by jjtoard** [1technophile/OpenMQTTGateway#526]
Hello,

I tried almost everything I think to get the openmqttgateway installed on my esp32 but don't succeed in it.

Error I get at this point is :
ZgatewayBT:453:49: error: 'class BLEAdvertisedDevice' has no member named 'getServiceDataCount'

Error below is :

ZgatewayBT:457:70: error: no matching function for call to 'BLEAdvertisedDevice::getServiceData(int&)'

           std::string serviceData = advertisedDevice.getServiceData(j);

In file included from D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEClient.h:22:0,

                 from D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEDevice.h:19,

                 from Z:\xxxx\openmqttgateway_v1\ZgatewayBT.ino:410:
D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEAdvertisedDevice.h:38:14: note: candidate: std::__cxx11::string BLEAdvertisedDevice::getServiceData()

  std::string getServiceData();

              ^

D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEAdvertisedDevice.h:38:14: note:   candidate expects 0 arguments, 1 provided

ZgatewayBT:475:87: error: no matching function for call to 'BLEAdvertisedDevice::getServiceDataUUID(int&)'

           BLEdata.set("servicedatauuid", (char *)advertisedDevice.getServiceDataUUID(j).toString().c_str());

                                                                                       ^

In file included from D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEClient.h:22:0,

                 from D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEDevice.h:19,

                 from Z:\xxxx\openmqttgateway_v1\ZgatewayBT.ino:410:

D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEAdvertisedDevice.h:39:14: note: candidate: BLEUUID BLEAdvertisedDevice::getServiceDataUUID()

  BLEUUID     getServiceDataUUID();

              ^

D:\Software\arduino-1.8.10-windows\arduino-1.8.10\portable\packages\esp32\hardware\esp32\1.0.4\libraries\BLE\src/BLEAdvertisedDevice.h:39:14: note:   candidate expects 0 arguments, 1 provided

Can someone help me fixing this

**Comment by 1technophile** [comment]
Hi,

This is because you are not using the good BLE library. You should take the one from the release page  : 
https://github.com/1technophile/OpenMQTTGateway/releases/download/v0.9.3/esp32dev-ble-libraries.zip

**Comment by jjtoard** [comment]
now it compiles till the end but I get an error that the scetch is to large
I also tried to remove all the .ino and all the .h file except for the user_config.h, config_BT.h, ZgatewayBT.ino but then I get errors again

**Comment by 1technophile** [comment]
Yes, indeed. You need to select into your arduino ide menu the min spiffs partition so as to free space for the program.

**Comment by jjtoard** [comment]
what board should I use then

**Comment by 1technophile** [comment]
You need to choose esp32dev and select min spiffs in flash or partition scheme sub menu

**Comment by jjtoard** [comment]
first compilation, lots of errors,
second compilation worked fine
could finally upload the code
testing will be for tomorrow
thanks a lot for helping.

Could the code on github be updated.  I can imagine I'm not the only one having this issues.

Again thanks a lot for the help.

**Comment by 1technophile** [comment]
Yes indeed, docs will be updated.
