### ISSUE TITLE
Web User Interface

### ISSUE THREAD

**Issue by Sansibari** [1technophile/OpenMQTTGateway#533]
It would be nice if OMG also had a web user interface like Tasmota for changing parameters online.
A console included in the web interface (similar to Tasmota) would also be useful for debugging.
Thanks!

**Comment by 1technophile** [comment]
hello, is it not the same request as #530

**Comment by Sansibari** [comment]
Hi, yes it's sam request. Sorry, I missed out this issue!
Thanks!
