### ISSUE TITLE
xiaomi mijia parsing problems with latest update

### ISSUE THREAD

**Issue by Sansibari** [1technophile/OpenMQTTGateway#535]
After updating the xiomi miji the values can't be parsed anymore (see attached printscreen form mqtt-explorer). Only the xiomi mi scale is parsed correct.

![Capture_6](https://user-images.githubusercontent.com/48505288/72683998-4e27c980-3b0f-11ea-9b35-7d8c57213454.jpg)

**Comment by 1technophile** [comment]
did you checked the history values of the mi jia to see if the sensor value were not reported previously?

**Comment by Sansibari** [comment]
unfortunately I got no history data saved.

**Comment by 1technophile** [comment]
Could you indicate the firmware version of your mi jia?

**Comment by Sansibari** [comment]
sent to you by email

**Comment by 1technophile** [comment]
Could you post it here maybe, I haven't received it?

**Comment by Sansibari** [comment]
The firmware is 1.01.0066

Maybe for your interest:  I can see the device and the values in ioBroker via ble adapter:

![IOB 2020-01-21_122518_192 168 1 127](https://user-images.githubusercontent.com/48505288/72990996-b0404180-3e23-11ea-9d77-e1ef975e9bca.png)

If you need more information don't hesitate to request.

Thank you!
