### ISSUE TITLE
How to disable config messages

### ISSUE THREAD

**Issue by byte4geek** [1technophile/OpenMQTTGateway#536]
Hi there is a way to disable the auto config message?
I prefer to configure manually the sensors on Home-Assistant

these message generate a mount of Traffic that i don't use.
Example of the message i want to disable:

` homeassistant/switch/4C11AE0AXXXXXX24704/config {"stat_t":"home/OpenMQTTGateway_ESP8266_RF/433toMQTT","name":"32024704","uniq_id":"4C11AE0ACXXXXXX4704","pl_on":"32000704","cmd_t":"home/OpenMQTTGateway_ESP8266_RF/commands/MQTTto433","device":{"name":"OpenMQTTGateway_ESP8266_RF","manufacturer":"OMG_community","sw_version":"version_tag","identifiers":["4C11AXXXXB"]}} `

Thanks a lot

**Comment by 1technophile** [comment]
Hello,

Yes , just remove the line below:
https://github.com/1technophile/OpenMQTTGateway/blob/4115f2a723f6d3d981cb7aaf42d52bd725417560/platformio.ini#L123

**Comment by byte4geek** [comment]
thanks a lot it works fine
