### ISSUE TITLE
Move version information from the version topic to SYStoMQTT

### ISSUE THREAD

**Issue by akasma74** [1technophile/OpenMQTTGateway#537]
**Is your feature request related to a problem? Please describe.**
I think there is no point in publishing OMG version in a separated topic with a retain flag.
It just adds up to all that retained messages and makes little sense on its own.

**Describe the solution you'd like**
Just publish the version information alongside everything else like

> home/OMG_2nd_floor/SYStoMQTT {"version": "0.9.2", "uptime":3480,"freeMem":45352,"rssi":-56,"SSID":"wifi","ip":"192.168.0.37","mac":"61:C6:3A:EA:20:88","modules":"RF"}

**Comment by 1technophile** [comment]
good idea!

**Comment by akasma74** [comment]
@1technophile any chance for it to be implemented?

**Comment by 1technophile** [comment]
yes, as it is easy it will be added to next version
