### ISSUE TITLE
RF Sender jams all other RF traffic

### ISSUE THREAD

**Issue by nvschilleman** [1technophile/OpenMQTTGateway#539]
I don't know if this is really an OpenMQTTGateway issue or not. But when my RF transceiver is connected to my NodeMCU board, it jams all RF traffic. I cannot reveice RF commands, and my KAKU lights won't turn on or off by the original remote. When i disconnect the transceiver I am able to receive commands. But when I connect the transceiver again and try to send commands over MQTT nothing happens.

Anyone knows what the problem is?

I use an STX882 transmitter.

I use this receiver: https://www.banggood.com/433Mhz-RF-Transmitter-With-Receiver-Kit-For-Arduino-ARM-MCU-Wireless-p-74102.html?p=SZ25159101562014119R&custlinkid=154640&cur_warehouse=CN

Still havent had time to build the SRX receiver and the above receiver works fine.

**Comment by 1technophile** [comment]
If you use the last version of rcswitch library you should not have this issue.
