### ISSUE TITLE
Docu: Needed/recommended Features of NodeMCU Firmware

### ISSUE THREAD

**Issue by dakky** [1technophile/OpenMQTTGateway#54]
As new nodemcu firmwares are only available via custom firmware builder (https://nodemcu-build.com/) it would be helpful to have a list of modules, which are needed in order to run this project (min requirements/recommended modules)

**Comment by 1technophile** [comment]
@dakky what do you mean by modules, do you have some examples to give?

**Comment by 1technophile** [comment]
@dakky could you detail your issue please or close it

**Comment by 1technophile** [comment]
@dakky if you have more details don't hesitate to reopen the issue
