### ISSUE TITLE
No Pilight MQTT Topics 0.9.3

### ISSUE THREAD

**Issue by darknessatnoon** [1technophile/OpenMQTTGateway#544]
No Pilight MQTT Topics 0.9.3
With the ZgatewayRF i get on MQTT something like 433toMQTT.
When i use ZgatewayPilight i should get PilighttoMQTT!? I see received Signals on Serial.
I use ESP8285.

#define Gateway_Name "MQTTGateway"
#define Base_Topic "home/"
Full readwrite access to home/MQTTGateway/ is set.

**Comment by akasma74** [comment]
it's `home/MQTTGateway/PilighttoMQTT`
so you can see that your OMG receives something but cannot see anything in MQTT?
would be great to see serial log.
