### ISSUE TITLE
esp8266 open wifi network

### ISSUE THREAD

**Issue by glasruit** [1technophile/OpenMQTTGateway#55]
The esp8266 is visible as an open wifi network with a SSID like ESP_12345. It is possible to connect to it and get an ip-number.

To avoid this, you can set the esp8266 in station mode:
In OpenMQTTTGateway.ino add, after line 146 `delay(10)`  :
```
WiFi.mode(WIFI_STA);
```

**Comment by 1technophile** [comment]
@glasruit Added, please close the issue if OK for you
