### ISSUE TITLE
MQTTtoONOFF bug

### ISSUE THREAD

**Issue by a-roz** [1technophile/OpenMQTTGateway#551]
Board: SONOFF-BASIC-RFR3 hacked as described

Been used precompiled version with RF module from GitHub , 
and also compiled version with recommended
```
  '-DZactuatorONOFF="ONOFF"'
  '-DZsensorGPIOInput="GPIOInput"'
  '-DACTUATOR_ONOFF_PIN=12'
  '-DGPIOInput_PIN=0'
  '-DRF_RECEIVER_PIN=4'
  '-DZgatewayPilight="Pilight"'
```

Pilight and GPIOInput (pin 0) they are work as expected

While ACTUATOR_ONOFF_PIN is defined, it should work with no additional.
But when I've try publish wrong payload (empty in this case), example
`mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoONOFF/setON
`

I get response on serial
```
Hey I got a callback
MQTTtoONOFF
pin number
0
Pub ack into:
home/RFR3/ONOFFtoMQTT
```
but it should be 12, not 0. it means - actuator doesn't work
To check this I've put following to **ZactuatorONOFF.ino** line 67
`    int pin = 12;
`
and it works as expected.
can be easy sorted modifying line 67 as
`    int pin = strtol(datacallback, NULL, 10) | ACTUATOR_ONOFF_PIN; // we will not be able to pass values > 4294967295
`
Please correct this.

Also, need a MQTT message or parameter which contains Actuator state like
{ power: ON }

**Comment by 1technophile** [comment]
could you indicate the version you are using?

**Comment by a-roz** [comment]
the latest 0.9.3 downloaded week ago

**Comment by 1technophile** [comment]
Thanks for the feedback

**Comment by 1technophile** [comment]
corrected
