### ISSUE TITLE
Is MDNS enabled by default?

### ISSUE THREAD

**Issue by agoralive** [1technophile/OpenMQTTGateway#554]
Not a bug/request but more a question.

Is mdns enabled by default within all the releases?

I can't seem to find this information anywhere :(

**Comment by 1technophile** [comment]
it is not enable by default , the parameter is [here](https://github.com/1technophile/OpenMQTTGateway/blob/8842ea1f4b7d277245307ee2b3699692ccf09658/main/User_config.h#L86)

**Comment by agoralive** [comment]
Then I need to compile myself in order to get at version with mdns enabled?

Or will OMG be able to connect to at MQTT broker using "server.local" even if this parameter is not enabled?

**Comment by 1technophile** [comment]
> Then I need to compile myself in order to get at version with mdns enabled?

Yes  you need to compile it yourself

**Comment by agoralive** [comment]
Thank you for the answer
