### ISSUE TITLE
Retain on Binary Sensor workaround in Home Assistant

### ISSUE THREAD

**Issue by byte4geek** [1technophile/OpenMQTTGateway#560]
Hi,

We do not have retain on sensor like window sensors using the OMG then on Home Assistant restart you loose the state of the sensors.
if someone need the retain on the binary sensor i followed this guide:
https://community.home-assistant.io/t/sonoff-rf-bridge-strategies-for-receiving-data/108181
follow Strategy 2: Demultiplexer

only you need to modify the automation that call the python script as follow:
`
- alias: '[SYS] OpenMqttGW_demultiplexer'
  trigger:
  - platform: mqtt
    topic: home/OpenMQTTGateway_ESP8266_RF/433toMQTT
  action:
  - service: python_script.open_mqtt_gateway_demux
    data_template:
      payload: '{{trigger.payload_json.value}}'
`

**Comment by 1technophile** [comment]
Hi,

thanks for the info, maybe this could be added as an example into home assistant integration docs?
https://github.com/1technophile/OpenMQTTGateway/edit/development/docs/integrate/home_assistant.md
