### ISSUE TITLE
Compatible lora sx1276

### ISSUE THREAD

**Issue by lscosta90br** [1technophile/OpenMQTTGateway#565]
Hello,

i get some months esp32 lora:
https://en.aliexpress.com/item/32838347451.html?spm=a2g0s.9042311.0.0.2742b90a53urcO
Can you tell if they are compatible with your firmware?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 1technophile** [comment]
Hello, the url seems incorrect, could you correct it?

**Comment by lscosta90br** [comment]
Excuse me,

Test it on the link and it's not in my purchase history

```code
Description:
Dominant Frequency: 240MHZ
Flash: 8Mbyte
Processor: Tensilica LX6 Dual Core
Master chip: ESP32
LoRa chip: SX1276
Support frequency band: 868-915MHZ
Open communication distance: 2.8KM
Computing capacity: up to 600DMIPS
Dual-mode Bluetooth: traditional Bluetooth and BLE low-power Bluetooth
Development environment: perfect support for Arduino
Operating voltage: 3.3-7V
Operating temperature range: -40-90 ℃
Receiver sensitivity: -139dbm (SD12, 125KHz)
UDP continuous throughput: 135Mbps
USB adapter chip: CP2102
Support mode: Sniffer, Station, softAP and Wi-Fi Direct
```
![image](https://user-images.githubusercontent.com/29935375/75895711-c70b8800-5e14-11ea-8063-dd2d9a7eb79f.png)
![image](https://user-images.githubusercontent.com/29935375/75895801-e7d3dd80-5e14-11ea-8792-8a2cd7e06433.png)
![image](https://user-images.githubusercontent.com/29935375/75895920-0d60e700-5e15-11ea-8c24-319044c95ead.png)

**Comment by 1technophile** [comment]
Now they are https://github.com/1technophile/OpenMQTTGateway/releases/tag/v1.0.0
