### ISSUE TITLE
Garagem Open/Close x LoRA X distance 2km x OpenMQTTGateway

### ISSUE THREAD

**Issue by lscosta90br** [1technophile/OpenMQTTGateway#566]
HI,
I am designing an IoT project to automate my need to open and close an electronic gate that is 2km away.
Here are some suggestions that I can use in the project:
- On the motherboard of the garage door, I can use push button activation.
- I have 2 lora esp32 equipment with the following specification:
868 mhz / 915 mhz lora esp32 oled wifi sx1276 iot module & antenna-
- The gate is activated via 433mhz

How can I employ OpenMQTTGateway in this project?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 1technophile** [comment]
Hi,
You could use it like that

Controller ->OMG on ESP32 LORA ->Custom firmware on ESP32 LORA -> Push button
....................Wifi..........................................LORA..............................................................Wire

The custom firmware consist on a program based on modified version of [LoraReceiver.ino](https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaReceiver/LoRaReceiver.ino) which trigger a relay or equivalent to simulate the push button of your door.

Added to that I would add a sensor to know the door state:
Controller <-OMG on ESP32 LORA <-Custom firmware on ESP32 LORA <- Sensor
....................Wifi..........................................LORA..............................................................Wire
