### ISSUE TITLE
Sonoff RF Bridge won´t connect to unlisted WiFi after powercycle

### ISSUE THREAD

**Issue by marrobHD** [1technophile/OpenMQTTGateway#578]
Before submitting a problem please check the troubleshooting section
https://github.com/1technophile/OpenMQTTGateway/wiki/Troubleshooting

**Describe the bug**
After powercycle my Sonoff RF Bridge it won´t connect back to unlisted WiFi network. But after running http://192.168.4.1/restart it connects to wifi

**To Reproduce**
1. Configure 'WiFi and MQTT'
2. Wait until it connects to WiFi
3. Powercycle the bridge
4. See error at its AP

**Expected behavior**
It should connect to my unlisted WiFi network.

**Screenshots**
<img width="390" alt="779-606-max 1" src="https://user-images.githubusercontent.com/29308361/78574543-695ec700-782a-11ea-9571-7a799413e2aa.png">

**Environment (please complete the following information):**
* OpenMQTTGateway version used: v0.9.3

**Additional context**
It connects to wifi after about 120 seconds.

**Comment by 1technophile** [comment]
I have done a bypass on the development branch related to wifi connections problem at restart.
Would it be possible to test the last development branch to see if you reproduce the issue?
Or maybe you've already tried with this modification?

**Comment by marrobHD** [comment]
After few restarts it works now instantly

**Comment by 1technophile** [comment]
Ok it could have be an issue with the flash memory. OMG format it automaticaly if it doesn't connect at first start.
