### ISSUE TITLE
Support for A7129 receiver

### ISSUE THREAD

**Issue by milnovako** [1technophile/OpenMQTTGateway#582]
Would it be possible to add A7129 RX support?

This module is used for kinetic switches.
The idea is to make a gateway if possible?
Nowhere could I find his datasheet.
![Kinetic switch reciever 1](https://user-images.githubusercontent.com/13822352/79254007-5ed4ab00-7e84-11ea-853d-c8480e2cda80.JPG)
![Kinetic switch reciever 2](https://user-images.githubusercontent.com/13822352/79254015-61370500-7e84-11ea-89f2-aa1a5eb0d1b8.JPG)
![Kinetic switch reciever 3](https://user-images.githubusercontent.com/13822352/79254020-63995f00-7e84-11ea-8f30-bf33099c47fd.JPG)

**Comment by 1technophile** [comment]
Hi,

If it is a rare module I'm not sure it is worth to spend time on it.
Did you try with a classic module like the ones proposed on the docs?

**Comment by milnovako** [comment]
I tried everything but nothing. This module is increasingly being used. But the manufacturer only supplies a switch to a single receiver. When rf bridge could be made, because the switches are without batteries, they use kinetic energy, I think it would be good to integrate this.
![IMG-2538](https://user-images.githubusercontent.com/13822352/79256472-60a06d80-7e88-11ea-8b5a-152200447658.jpg)

**Comment by 1technophile** [comment]
The kinetic switches use a shorter impulse waveform compared to powered ones.
One test you could try is using a basic receiver with a decreased [separation limit ](https://github.com/sui77/rc-switch/blob/7fec3904a2f6f567766d0afb7d1bb4d0abf990c7/RCSwitch.cpp#L101)(2000 or less)

**Comment by milnovako** [comment]
I tried everything but not successfully :)

**Comment by milnovako** [comment]
Anyway, thanks !

**Comment by 1technophile** [comment]
Let me think about it, I will go back to you
