### ISSUE TITLE
Is it possible to make BT beacon beap?

### ISSUE THREAD

**Issue by untitledlt** [1technophile/OpenMQTTGateway#583]
**Is your feature request related to a problem? Please describe.**
I'm using ESP32 and BT beacon from https://www.aliexpress.com/item/32866018860.html?spm=a2g0s.9042311.0.0.65fd4c4dUK78f7
I can see periodic data from BT beacon. 

If I connect beacon to a phone, it is possible to trigger beap using an app on my phone.
Would it be possible to trigger the same beep from MQTT?

**Comment by 1technophile** [comment]
Not for the moment as we are not connecting to the BLE devices (only scanning data) but it could be done in the future.
