### ISSUE TITLE
OMG floods my brooker with messages

### ISSUE THREAD

**Issue by opl-git** [1technophile/OpenMQTTGateway#589]
Before submitting a problem please check the troubleshooting section
https://github.com/1technophile/OpenMQTTGateway/wiki/Troubleshooting

**Describe the bug**
The OMG floods my MQTT Broker so much, it actually goes down.
Here an output of the Serial Connection:
_MQTT connection...
Connected to broker
Subscription OK to the subjects_
This mesage comes alsmost 5x every second
I really can't the problem. This is my second gateway with OMG, the first runs without any problems. 
All I did was change the Base_Topic... (first OMG uses "og/", the second "wg/" 

**To Reproduce**
I flashed the OMG again for several times

**Expected behavior**
A normal Login to the brooker

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version 0.93
Using the Arduino way to flash OMG on my ESP32 Dev Kit

**Additional context**

**Comment by 1technophile** [comment]
This can be due to the fact that you are using the same gateway name on both boards, did you changed the second one?

**Comment by opl-git** [comment]
Thank you so much! Your awesome!
That was the problem!
I thought I only had to change the basic topic.

**Comment by 1technophile** [comment]
You're welcome, if you would like to add a description of the issue/solution in the [troubleshooting ](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/upload/troubleshoot.md) page don't hesitate
