### ISSUE TITLE
Low Power Mode changes GPIO pin even when disabled

### ISSUE THREAD

**Issue by jmw6773** [1technophile/OpenMQTTGateway#593]
**Describe the bug**
The GPIO used for LOW_POWER_LED is unuable even when LOW_POWER_MODE is disabled when using the BT module no ESP32.

The error occurs in ZgatewayBT.ino:583 as there is no condition to check if LOW_POWER_MODE is enabled before setting the GPIO to value LOW_POWER_LED_OFF. 
https://github.com/1technophile/OpenMQTTGateway/blob/cf641851afc96796f341b7e512a7b57a81cbcada/main/ZgatewayBT.ino#L583

**To Reproduce**
Try to use GPIO2 on ESP32 when BT module is enabled. 

**Expected behavior**
When LOW_POWER_MODE isn't enabled, the pin defined by LOW_POWER_LED shouldn't be changed.

**Proposed fix**
ZgatewayBT.ino:583
```
//only change LOW_POWER_LED if low power mode is enabled
if (low_power_mode > 0)
  digitalWrite(LOW_POWER_LED, LOW_POWER_LED_OFF);
```

**Environment (please complete the following information):**
OpenMQTTGateway version used V0.9.4beta
BT module for ESP32

**Comment by 1technophile** [comment]
Thanks for pointing that
