### ISSUE TITLE
Make more options configurable via platformio.ini

### ISSUE THREAD

**Issue by jmw6773** [1technophile/OpenMQTTGateway#595]
**Is your feature request related to a problem? Please describe.**
I have a few different designs that use OpenMQTTPlatform that use different modules and pins. It is a hassle to have multiple versions of the code. It would be much easier to be able to create an entry in the platform.ini file and be able to define the pin and some of the commonly changed attributes for the sensors.

**Describe the solution you'd like**
Where possible, I'd like to add definition checks, like is done in User_config.h for the Gateway_name, so that if the variable/pin is defined in the platform.ini file, that value is used.

i.e. For config_ADC.h:38
```
#if defined(ESP8266) || !defined(ADC_PIN)
  #define ADC_PIN A0 //on nodeMCU this is D3 GPIO0
#endif
```

**Describe alternatives you've considered**
Some pins can't be changed depending on the platform. (i.e. ADC for ESP8266 can only be A0, and only analog pins for ATMEGA and ESP32. It's up to the user to specify an appropriate pin.)

The user may put bad data for non-pin defines. (i.e. Negative values for TimeBetweenReadingADC.)
Can users be trusted to not do this?

One drawback to this is that it could make the header files more cluttered and difficult to read if it's overdone. But if done for pin assignments and commonly changed values, it might be okay.

**Comment by 1technophile** [comment]
I agree to generalize the use of ifndef in config files for all pertinents parameters
