### ISSUE TITLE
Add the ability to updates  ESP8266 via OTA / OTA Uploading

### ISSUE THREAD

**Issue by ctripodi** [1technophile/OpenMQTTGateway#62]
Another features that could be great to have in this excellent project.
Add the ability to updates  ESP8266 via OTA / OTA Uploading
http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html
Thanks.

**Comment by PatteWi** [comment]
Its already implemented: [https://github.com/1technophile/OpenMQTTGateway/pull/59](click here)

**Comment by 1technophile** [comment]
@ctripodi Indeed implemented into the master, I added some [doc ](https://github.com/1technophile/OpenMQTTGateway/wiki/OTA-Update-(ESP8266))about it

Please close the issue if OK for you

**Comment by ctripodi** [comment]
Thanks!
