### ISSUE TITLE
feature request: make white-list persistent

### ISSUE THREAD

**Issue by aHVzY2g** [1technophile/OpenMQTTGateway#622]
After evrey restart the white-list is lost.
It would be nice, if we can programm the white-list into the ESP.
An alternative would be of cource to write the white-list to SPIFFS.

**Comment by 1technophile** [comment]
if you want it to be persistent you may publish it with a retain flag, this way the broker will keep it. And when OMG restart it will get it back.

**Comment by aHVzY2g** [comment]
oh that's smart 😂, thx

**Comment by 1technophile** [comment]
We may add it to the docs. Thanks for the idea !;-)
