### ISSUE TITLE
Unable to flash ESP32 with default DS1820 pin

### ISSUE THREAD

**Issue by jmw6773** [1technophile/OpenMQTTGateway#625]
On the ESP32, GPIO2 must be driven low or floating for the ESP32 to enter the serial bootloader to flash.
The DS1820 sensor is set to use GPIO2 as the default pin and requires a 4.7k pull-up resistor on its data pin. This prevents the ESP32 from entering the serial bootloader, so it can't be flashed.

**Proposed Fix**
 Change the default GPIO for the ESP32 devices for the DS1820 sensor. 

 @1technophile, do you have a pinout reference for the ESP32 or a preference on which pin should be used as the default pin for this sensor?

**Expected behavior**
ESP32 shouldn't be prevented to enter the serial bootloader be connecting a sensor.

**References**
- [Powering Diagram for DS18b20 sensor](https://cdn-shop.adafruit.com/datasheets/DS18B20.pdf)
- [ESP32 Book Mode Selection Reference](https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection)

**Comment by 1technophile** [comment]
> @1technophile, do you have a pinout reference for the ESP32 or a preference on which pin should be used as the default pin for this sensor?

You can find the default pinout [there](https://docs.google.com/spreadsheets/d/1_5fQjAixzRtepkykmL-3uN3G5bLfQ0zMajM9OBZ1bx0/edit#gid=1617051124)

You can take the one you prefer while it is free from other module and tested working.
