### ISSUE TITLE
IR SONY does not work on last development branch

### ISSUE THREAD

**Issue by Minims** [1technophile/OpenMQTTGateway#630]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
mosquitto_pub  -t home/OpenMQTTGateway/commands/MQTTtoIR -m '{"hex":"0x490","protocol_name":"SONY","repeat":3}'

Works on master branch, not on current dev branch 0.9.4beta

Protocol NEC is working in both version.

**To Reproduce**
Compile latest master branch  0.9.3
Compile latest dev branch 0.9.4beta

**Expected behavior**
mosquitto_pub  -t home/OpenMQTTGateway/commands/MQTTtoIR -m '{"hex":"0x490","protocol_name":"SONY","repeat":3}'

TV react to the ir code

**Comment by 1technophile** [comment]
Hi,

Thanks for pointing this, giving a look now

**Comment by 1technophile** [comment]
Could you try with the last development branch not the v0.9.4beta. I have made [corrections ](https://github.com/1technophile/OpenMQTTGateway/pull/619) since the v0.9.4beta.

**Comment by Minims** [comment]
Ok, i will try in few minutes :-)

**Comment by Minims** [comment]
Same issue with last dev branch.

LED is blinking 3 times as expected, but the TV does not understand : 

```
home/OpenMQTTGateway/commands/MQTTtoIR {"hex":"0x490","protocol_name":"SONY", repeat:3}
home/OpenMQTTGateway/IRtoMQTT {"hex":"0x490","protocol_name":"SONY","repeat":3}

```

**Comment by Minims** [comment]
found it , here is the fix : 

```
[MINIMS]$ git diff main/ZgatewayIR.ino
diff --git a/main/ZgatewayIR.ino b/main/ZgatewayIR.ino
index ee2623e..6c09aff 100644
--- a/main/ZgatewayIR.ino
+++ b/main/ZgatewayIR.ino
@@ -322,7 +322,7 @@ bool sendIdentifiedProtocol(const char* protocol_name, unsigned long long data,
   }
 #  endif
 #  ifdef IR_SONY
-  if (strcmp(protocol_name, "SONY") == 1) {
+  if (strstr(protocol_name, "SONY") != NULL) {
     Log.notice(F("Sending IR signal with %s"), protocol_name);
     if (valueBITS == 0)
       valueBITS = SONY_12_BITS;
```

**Comment by 1technophile** [comment]
Thanks, it should be:
`if (strcmp(protocol_name, "SONY") == 0) {`

**Comment by 1technophile** [comment]
Dev branch updated

**Comment by Minims** [comment]
Thanks it's working great ! :-)
