### ISSUE TITLE
433MHz Wireless Outdoor Waterproof Infrared Beam Detector compatibility. 

### ISSUE THREAD

**Issue by duyuelryel** [1technophile/OpenMQTTGateway#635]
Greetings! Does anyone tryed this to work with OMG? Seller describes it as 433mhz.

https://a.aliexpress.com/_d6ayT9G

**Comment by 1technophile** [comment]
Hello,

Your link doesn't work

**Comment by 1technophile** [comment]
I didn't know that this kind of device exist. I will be interested by your feedback if your buy it. 
When I see the electronic and the different other components there is a big change that it will be compatible.

**Comment by duyuelryel** [comment]
> I didn't know that this kind of device exist. I will be interested by your feedback if your buy it.
> When I see the electronic and the different other components there is a big change that it will be compatible.

Item description say, it sends a command to security systems by 433. I have askes seller and he said, it works with different security centers too. So i ordered it. It will arrive in the next weeks and will send infos about it. Photos etc.

**Comment by duyuelryel** [comment]
So, the sensor just arrived. I dry tested it and it seems very good.
My OMG device is set to pilight, but my tasmotised sonof 433 rf bridge sees the code flawlessly. So it must be OMG compatible too. If you want, i can make a review just tell me where.

**Comment by 1technophile** [comment]
> So, the sensor just arrived. I dry tested it and it seems very good.

nice !

> If you want, i can make a review just tell me where.

It would be cool, you can write it on the [forum](https://community.openmqttgateway.com) and I will add a link to it on the compatible devices list.

**Comment by duyuelryel** [comment]
> It would be cool, you can write it on the [forum](https://community.openmqttgateway.com) and I will add a link to it on the compatible devices list.

All right. I'll do it in the next days!

**Comment by 1technophile** [comment]
[Added ](https://compatible.openmqttgateway.com/index.php/product/gsmwond-wired-433mhz-wireless-barrier-2-beams-detector/)to the list of compatible devices
