### ISSUE TITLE
i have a idea，make it in Wall switch box

### ISSUE THREAD

**Issue by Wulicheng321** [1technophile/OpenMQTTGateway#639]
i draw a pcb for make it in Wall switch box 
in plan A，i use esp01m with IR+RF~

but i encountered a difficulty
how can i compile the .bin file for esp01m?

**Comment by debegr92** [comment]
You don't have to compile the BIN file, you have to compile the source code to get a BIN file.
Clone the repository and start with the Arduino IDE.

**Comment by Wulicheng321** [comment]
Sorry i'm just a rookie with ideas

**Comment by 1technophile** [comment]
> Sorry i'm just a rookie with ideas

No problem, ideas are welcome ;-)
