### ISSUE TITLE
ESP8266 builds

### ISSUE THREAD

**Issue by jj-uk** [1technophile/OpenMQTTGateway#645]
**Is your feature request related to a problem? Please describe.**
There do not seem to be any ESP8266 builds since 0.92.
Has the ESP8266 been deprecated?

**Comment by 1technophile** [comment]
Not, ESP8266 is always supported. All the nodemcuv2 * are for ESP8266
https://github.com/1technophile/OpenMQTTGateway/releases

**Comment by jj-uk** [comment]
Thanks, (closed).
