### ISSUE TITLE
Sonoff RF Bridge - Installed OMG but no AP is visible - Bridge is no longer flashable.

### ISSUE THREAD

**Issue by gaussey** [1technophile/OpenMQTTGateway#708]
Solder connection broke on the board after flashing so is no longer able to flash, no AP is visible but the device is flashing when I send a command from an RF device. Am I screwed? I’ve ordered another Sonoff RF in the meantime.

**Comment by 1technophile** [comment]
> Solder connection broke on the board after flashing so is no longer able to flash

You can try to scratch the circuit path with a cutter and solder there.

> no AP is visible but the device is flashing when I send a command from an RF device. 
A flashing led just mean that the internal RF decoder receive a signal (not linked with ESP8285)

**Comment by 1technophile** [comment]
I close the issue, if you have other questions, do not hesitate to ask on the [forum](https://community.openmqttgateway.com/)
