### ISSUE TITLE
Memory leakage in getting manufacture data and the fix.

### ISSUE THREAD

**Issue by l8l8l** [1technophile/OpenMQTTGateway#725]
BLE Scan runs out of memory when processing manufacture data, 'freemem'  reduced very quickly and leads frequent crash.

---------ZgatewayBT.ino-------------

      if (advertisedDevice.haveManufacturerData()) {
        char* manufacturerdata = BLEUtils::buildHexData(NULL, (uint8_t*)advertisedDevice.getManufacturerData().data(), advertisedDevice.getManufacturerData().length());
        Log.trace(F("Manufacturer Data: %s" CR), manufacturerdata);
        BLEdata.set("manufacturerdata", manufacturerdata);
        free(manufacturerdata); **<-  Add the pointer free here.**
      }
-------------------------------------
Tested with default_envs = esp32dev-ble, pubUnknownBLEServiceData, pubBLEManufacturerData, pubBLEServiceUUID are enabled to scan BLE Beacons. freemem stays at 50KB.

**Comment by 1technophile** [comment]
Thanks for pointing that

**Comment by jmw6773** [comment]
@l8l8l , great find. This seems to have resolved the random crashing I was seeing on my ESP32 device.
