### ISSUE TITLE
Not all parameters allow prod_env.ini configuration

### ISSUE THREAD

**Issue by mpember** [1technophile/OpenMQTTGateway#726]
**Is your feature request related to a problem? Please describe.**
The User_config.h has some parameters that are unable to be changed by prod_env.ini values.

e.g. OMG_VERSION and ota_* parameters cannot be set in prod_end.ini

**Describe the solution you'd like**
wrapping the User_config.h definition lines with #ifndef and #endif lines makes it possible to override the parameters with values in prod_env.ini

e.g.
```
#ifndef ota_password
#  define ota_password "OTAPASSWORD"
#endif
```

**Comment by 1technophile** [comment]
good catch, if you are interested do not hesitate to submit a PR

**Comment by mpember** [comment]
> good catch, if you are interested do not hesitate to submit a PR

I tend to use master releases for my builds.  I'll try rebase my fork and have a look.

**Comment by 1technophile** [comment]
> I'll try rebase my fork and have a look.

Do it from the `development` branch please

**Comment by mpember** [comment]
> Do it from the `development` branch please

PR created.  It is 1:30am and I didn't do too many tests apart from a trial build on for of the boards.  If there are any issues, just shout.

**Comment by 1technophile** [comment]
> It is 1:30am and I didn't do too many tests apart

Do not worry no rush ;-)
