### ISSUE TITLE
Arduino UNO + EthernetShield RF gateway works for pi based homeassistant but NUC

### ISSUE THREAD

**Issue by shahglobal** [1technophile/OpenMQTTGateway#739]
Hi,
My NUC PC based homeassisant works fine for mqtt clients, my sonoff based RF bridge connects to it okay. But not the Arduino UNO and ethernet shield based OMG setup. 
The Arduino plus ethernet shield setup works fine if I point it to a raspberry pi based homeassistant setup, so this tells that the Arduino setup is fine.
What could be the problem,  any pointers would be awesome.
Thanks in advance
Shah
---------------------
Goal is to use an ethernet-based RF gateway to homeassistant that is running on NUC PC. Hence removing the WiFi dependency from my IoT devices.

**Comment by 1technophile** [comment]
Hi,

Did you checked the mosquitto version, firewalls issues, do you have authentication activated on your broker?

Please format your text correctly for all the people that are going to read it and try to help you ;-)

**Comment by shahglobal** [comment]
Thank you so much for responding sir, 
Yes, the mosquito version in pi and nuc is the same (version 1.6.3). Yes, authentication is enabled.
There is no firewall in between, I tested even the same IP from sonoff rf bridge which already works to nuc pc. ( I want to decommission the sonoff rf bridge since it is using wifi).
I tested an Arduino MQTT test sketch and the nuc pc does show connection attempts (at mosquito broker logs) from Arduino, the test sketch has no authentication info so it shows failed attempts. Another test sketch with authentication info shows no connection attempts to nuc pc at all, just like the problem in question.
btw the Arduino ethernet IP is pingable. I only have UNO at the moment but would love to try Mega which is on order, if this helps at all.  Any tweak that makes it work would be great.  I am wondering if someone can confirm it works with nuc pc homeassistant.
Thanks and cheers.
(Error showing in console,, failure_number_mqtt: 9,, -> W: failed, rc=-2).

**Comment by 1technophile** [comment]
Are the gateway and the broker on the same switch or router?

**Comment by shahglobal** [comment]
Everything is on the same network and switch/gateway, if the  Arduino OMG IP is pointed to pi homeassistant it works right away, but I want to use nuc pc since its an upgrade.  strange!
Cheers and thanks

**Comment by 1technophile** [comment]
Could you compare the NUC and the PI in terms of network configuration and align the NUC to the PI ones.

**Comment by shahglobal** [comment]
Hi, I repaced my Arduino Uno with Mega, and this combination resolved the problem with my NUC setup don't know what exactly it was but hey it is working now to NUC PC. thanks for your help.

**Comment by shahglobal** [comment]
Hi,
The RF receive function works and can be used okay but the sending portion did not work. I tried the older version of OMG v0.93 which did show a message "hey I got a call back" while in version v0.9.4 shows no responses for RF "sending" from MQTT.
Please advise what to tweak to debug this.
I try to use mqtt home/OpenMQTTGateway/commands/MQTTto433  with payload to send a message from homeassistant/nodered to turn on/off a plug. My setup is now Arduino Mega with an ethernet shield and two recommended RF modules connected to it.
Kind Regards.
Shah

**Comment by 1technophile** [comment]
Hi

> but the sending portion did not work

Did you tried the troubleshooting section ? 
https://docs.openmqttgateway.com/upload/troubleshoot.html#not-able-to-send-or-receive-rf-or-ir

**Comment by shahglobal** [comment]
Thanks for your reply sir, I tried external power supply, plus tried different emitter GPIO even tried Arduino UNO to the old system, receiving is fine but the transmitter is no go. by the way, even if the RF emitter is disconnected from the pin it should show something in Arduino serial monitor upon MQTT receipt for transmission, it does not, while the older version does acknowledge call back in the Arduino the serial monitor but don't work actually. strange! if this unit works I would prefer it over my sonoff gateways, and even the rflink rf hardware which I recently received. Any further pointers would be appreciated
Thanks and kind regards

**Comment by shahglobal** [comment]
Update:  it turned out to be a command format issue, once I used full MQTT payload with the brackets, it did the trick, The wiki documentation did help. I was sending MQTT payload as rf code only while full string should have been used e.g {"value":4443146}.
That is great, now I can move on, thanks for pointing me in the right direction.
Kind regards and thanks again.

**Comment by shahglobal** [comment]
Hi,
I tested OMG Arduino mega is working fine, after each power cycle the ethernet shield IP fails to ping unless the reset button on this shield is pushed. Is it possible to modify the Arduino code to reset the Ethernet Shield after bootup?
Kind Regards

**Comment by shahglobal** [comment]
update-
Adding a 100nf capacitor across the reset pushbutton on the ethernet shield solved this problem. Hint got from youtube video.
Now the OMG ethernet+Arduino is behaving as expected and is reliable so far, for re-flashing I may have to remove the capacitor but I will not be flashing this device that often.
Kind regards and thanks for your help.
cheers

**Comment by 1technophile** [comment]
Great!

**Comment by shahglobal** [comment]
I noticed one issue, I saw that the omg was flooding the mqtt by sending a repetitive code may times a second all  LEDs  on ethernet was showing so busy, this state will continue unless I power cycle the unit. This phenomenon happened few times over the past few days. When its flooding the mqtt, it does work but very slow.
What could be causing this issue, the power cycle helps, but makes this unit unreliable.  I have to use a timer or something  to have it power  cycled say every day for reliable operation.  Please advice if an updated is needed of some kind. 
Cheers
Shah

**Comment by 1technophile** [comment]
I don't think this is related to the topic of this issue, could you ask into the [community](https://community.openmqttgateway.com/) please
