### ISSUE TITLE
Multiple ir emitters 

### ISSUE THREAD

**Issue by sukhdeepgill1** [1technophile/OpenMQTTGateway#74]
Can we use multiple ir emitter with openmqtt gateway?

**Comment by 1technophile** [comment]
You mean send8ng the same signal or different signal ?

**Comment by sukhdeepgill1** [comment]
Sending the same signal.
THANKS

**Comment by 1technophile** [comment]
With the current circuit i have two leds emitters, you can increase the number of led in parallel if you size correctly the transistor and the power supply.

**Comment by sukhdeepgill1** [comment]
Thanks a lot.
