### ISSUE TITLE
Missing 'include' folder

### ISSUE THREAD

**Issue by leeuwa** [1technophile/OpenMQTTGateway#748]
After compiling the OpenMQTTGateway in PlatformIO on VS-Code there are 2 problems reported. In the file `c_cpp_properties.json` are 2 lines pointing to the 'include'-folder, but the folder is not there. 
(It is compiling successfully, and everything is working on a ESP32).
Screenshot:
<img width="1655" alt="Schermafbeelding 2020-08-28 om 20 11 49" src="https://user-images.githubusercontent.com/69637464/91602017-e53ce580-e96a-11ea-8380-25ab5cbb0992.png">

**Comment by 1technophile** [comment]
You may try to add
`include_dir = main`
into platformio.ini file, in the `[platformio]` section.

**Comment by leeuwa** [comment]
It works, thanks.
