### ISSUE TITLE
Query - now that the BLE library is NimBLE, is there a plan to support getting the included beacon specifics from the manufacturerdata?

### ISSUE THREAD

**Issue by DigiH** [1technophile/OpenMQTTGateway#766]
Just played around a bit with the example code at

.pio/libdeps/esp32dev-ble-ha/NimBLE-Arduino/examples/BLE_Beacon_Scanner/BLE_Beacon_Scanner.ino

and copied the iBeacon relevant part and includes to ZgatewayBT.ino, converting the Serial.printf only info there to

BLEdata.set("ID:" , oBeacon.getManufacturerId());
BLEdata.set("Major:" , ENDIAN_CHANGE_U16(oBeacon.getMajor()));
BLEdata.set("Minor:" , ENDIAN_CHANGE_U16(oBeacon.getMinor()));
BLEdata.set("UUID:" , oBeacon.getProximityUUID().toString().c_str());
BLEdata.set("Power:" , oBeacon.getSignalPower());

to get more informative info for my iBeacons.

Just wondering if this now existing NimBLE possiblity might be included in the future, for iBeacons and Eddystone beacons?

Not too sure though, how relevant this is to how many poeple.

**Comment by 1technophile** [comment]
Signal Power is interesting so as to have a better distance calculation (beacon/gateway), we may add the others when use cases will come.
Thanks for pointing that!
