### ISSUE TITLE
ZactuatorONOFF is replying gibberish on mqtt .../ONOFFtoMQTT

### ISSUE THREAD

**Issue by fabsenet** [1technophile/OpenMQTTGateway#769]
Hi,

I am sending 16 to home/OpenMQTTGateway_ESP8266_IR/commands/MQTTtoONOFF/setON

and I am observing:
![grafik](https://user-images.githubusercontent.com/2065705/94582810-fb490900-027c-11eb-9b2b-d7dbe9dd6213.png)

BTW: actual pin switching works.

I tracked it down to this code:

https://github.com/1technophile/OpenMQTTGateway/blob/178045868325b0d1bc717ca917901ae4597652d6/main/ZactuatorONOFF.ino#L65-L74

What I think is happening, it prints beyond the single char because it is not null terminated?!

**Comment by 1technophile** [comment]
Thanks for pointing that, I will take a look
