### ISSUE TITLE
Bt is not working on esp8266

### ISSUE THREAD

**Issue by killermatz** [1technophile/OpenMQTTGateway#77]
Pin in User_config.h is not correct.

Set it to 12 and 13.

Serial Monitor say "connection hm-10ok" but dont detect any bluetooth device.

**Comment by 1technophile** [comment]
Hello,
 are you using keyes hm10 ? 
You get serial connection ok with which pin ? 
What are your hm10 firmware version ?

**Comment by killermatz** [comment]
Im using hm10 soft version 549
Serial monitor in arduino ide say connected

Set RX to gpio 12
Set TX to gpio 13

MfG Martin

**Comment by 1technophile** [comment]
hm10 detect bluetooth low energy beacons and not bluetooth devices, did  you tested with beacons or a beacon simulator?

**Comment by killermatz** [comment]
Did you mean that the hm10 does not detect smartphones???

No i didnt test it with beaconsimulator.

MfG Martin

**Comment by 1technophile** [comment]
it detect smartphone if your smartphone is compatible with BLE beacons simulation and install a beacon simulator app

**Comment by 1technophile** [comment]
Did you advance in your test?

**Comment by 1technophile** [comment]
I'm closing this issue as I have no news, please reopen it if necessary
