### ISSUE TITLE
330MHz compatibility?

### ISSUE THREAD

**Issue by joshuakoh1** [1technophile/OpenMQTTGateway#774]
Hi,

Looking for a way to send a 330MHz signal, is there anything out there that goes on a ESP32 board? I'm seeing that FS1000A is supposed to have 315/330/433 chips but I'm only able to see the 315/433 on sale everywhere. Or more specifically, has anyone managed to interact with 330MHz on any device?

Thanks!

**Comment by 1technophile** [comment]
Hi, CC1101 may be a track to explore.
Nevertheless, the most challenging part could be to find a suitable library for your device protocol.
