### ISSUE TITLE
Zgatewayrf2 does not send autorecovery msgs for detected switches

### ISSUE THREAD

**Issue by aaddame** [1technophile/OpenMQTTGateway#785]
The gateway itself is discovered, but not the devices connected.
In ZgatewayRF there is a call to RFtoMQTTdiscovery
There is no call to discovery in ZgatewayRF2

**Comment by qistoph** [comment]
It seems this is being worked on: https://github.com/1technophile/OpenMQTTGateway/commit/cabc8695eb146848dd8dd88fc5fa438f2ed31104

**Comment by 1technophile** [comment]
Thanks
