### ISSUE TITLE
Autodiscovered rf2 device remains in status unkwown (Home assistant)

### ISSUE THREAD

**Issue by aaddame** [1technophile/OpenMQTTGateway#786]
The following auto discovery msgs are send to mqtt:

homeassistant/switch/CC50E355C75Erestart/config {"stat_t":"home/OpenMQTTGateway/LWT","name":"restart OMG","uniq_id":"CC50E355C75Erestart","pl_on":"{\"cmd\":\"restart\"}","pl_avail":"online","pl_not_avail":"offline","cmd_t":"home/OpenMQTTGateway/commands/MQTTtoSYS/config","device":{"name":"OpenMQTTGateway","manufacturer":"OMG_community","sw_version":"v0.9.5","identifiers":["CC50E355C75E"]}}
homeassistant/switch/CC50E355C75Eerase/config {"stat_t":"home/OpenMQTTGateway/LWT","name":"erase OMG","uniq_id":"CC50E355C75Eerase","pl_on":"{\"cmd\":\"erase\"}","pl_avail":"online","pl_not_avail":"offline","cmd_t":"home/OpenMQTTGateway/commands/MQTTtoSYS/config","device":{"name":"OpenMQTTGateway","manufacturer":"OMG_community","sw_version":"v0.9.5","identifiers":["CC50E355C75E"]}}
homeassistant/sensor/CC50E355C75EgatewayRF2/config {"stat_t":"home/OpenMQTTGateway/RF2toMQTT","name":"gatewayRF2","uniq_id":"CC50E355C75EgatewayRF2","val_tpl":"{{ value_json.value | is_defined }}","device":{"name":"OpenMQTTGateway","manufacturer":"OMG_community","sw_version":"v0.9.5","identifiers":["CC50E355C75E"]}}

For status the json msg send to mqtt should contain "value"

When I press a button on a remote I see the following msg:

home/OpenMQTTGateway/RF2toMQTT {"unit":0,"groupBit":0,"period":255,"address":9050646,"switchType":0}
It doesn't contain "value"

**Comment by 1technophile** [comment]
You are right it should be `address`
