### ISSUE TITLE
Static IP for Gateway with ESP*

### ISSUE THREAD

**Issue by duemchen** [1technophile/OpenMQTTGateway#790]
Alternative to DNS it would be good, to use a static IP.
For esp*
The parameter NetworkAdvancedSetup exists already in user_config.

**Comment by 1technophile** [comment]
It is planned in the code [here](https://github.com/1technophile/OpenMQTTGateway/blob/e7cecf64d2aef3353a18d6d5a882ce09fd2ceb45/main/main.ino#L830) but not documented properly, could you try to replace `ESPWifiAdvancedSetup` by `NetworkAdvancedSetup` and uncomment the last one in [user_config.h](https://github.com/1technophile/OpenMQTTGateway/blob/e7cecf64d2aef3353a18d6d5a882ce09fd2ceb45/main/User_config.h#L65)
