### ISSUE TITLE
mqtt_user is missing or not saved into the config

### ISSUE THREAD

**Issue by gborus** [1technophile/OpenMQTTGateway#793]
**Describe the bug**
After configuring the RF gateway through Wifi Manager, MQTT login failed, when I checked the Serial console for details, I cannot see the mqtt_user value I setup on the config page.

**To Reproduce**
1. After firmware upload, configure the device through the website
2. Check through serial console if you see mqtt_user info.

**Screenshots**
![image](https://user-images.githubusercontent.com/4707121/98282975-46062100-1f9f-11eb-8c27-74d13b4ff224.png)

**Environment (please complete the following information):**
* OpenMQTTGateway v0.9.5
* I also tried, OpenMQTTGateway v0.9.4
* nodemcuv2-rf-firmware.bin I used

**Comment by 1technophile** [comment]
Could you indicate the length of your mqtt_user?

**Comment by gborus** [comment]
Hey,

yeah, I tried 'test' and 'a' as well, but the result was the same.

thanks,

**Comment by 1technophile** [comment]
This is due to the length of your mqtt password, the max size is 60

**Comment by gborus** [comment]
cool, that's easy to fix, let me try, will report back shortly

**Comment by gborus** [comment]
this gonna take sometime, I used the auto generated homeassitant mqtt user and pwd, but that's I cannot change through the web interface, I need to dig into it.
probably this will be an issue for new homeassistant users. What do you think?

**Comment by 1technophile** [comment]
>probably this will be an issue for new homeassistant users. What do you think?

If you add a new user into home assistant and use it for OMG you should be ok

**Comment by gborus** [comment]
Thank you, that helped. I created a homeassitant account for the bridge and with the shorter password I can see now the mqtt user password in the serial console also managed to connect to the broker.

**Comment by 1technophile** [comment]
If you are interested, do not hesitate to contribute to the [doc](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/integrate/home_assistant.md) by submitting a PR :-)
