### ISSUE TITLE
Support fot DYPA02YYxX Ultrasonic sensor

### ISSUE THREAD

**Issue by ituHA** [1technophile/OpenMQTTGateway#800]
I was wondering if there is a chance to support the [DYPA02YYxx ](https://wiki.dfrobot.com/A02YYUW%20Waterproof%20Ultrasonic%20Sensor%20SKU:%20SEN0311) ultrasonic sensor.

I built a plant watering system using OMG 0.9.5 in an ESP32 board, Miflora sensors, and water pumps connected to relays. I use an HC-SR04 as a water level sensor, but unfortunately, the humidity ends damaging the sensor after a couple of months. The DYPA02YYxx is a waterproof sensor with separated emitting/receiving probes. The combination of ruggedness and small blind area (3 cm) makes it ideal for this use.

**Comment by 1technophile** [comment]
Closing, PR welcome
