### ISSUE TITLE
BLE Mi Scale - add check

### ISSUE THREAD

**Issue by michapr** [1technophile/OpenMQTTGateway#801]
Would be nice to add the check of the "stabilized" value before reporting (flag in byte 0):
https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale

I have some "undefined" values in database - I think it is because of this...

Thanks!

**Comment by 1technophile** [comment]
Are you using XMTZC04HM or XMTZC05HM?

**Comment by michapr** [comment]
XMTZC04HM

**Comment by 1technophile** [comment]
ok, will be solved by the linked PR
