### ISSUE TITLE
Sonoff rf bridge

### ISSUE THREAD

**Issue by prahjister** [1technophile/OpenMQTTGateway#81]
Any plans to port over to new sonoff rf bridge?

**Comment by 1technophile** [comment]
need to buy the device first, good idea

**Comment by prahjister** [comment]
Email me prahjister0 at the gmail domain and I will see if I can get one sent. I would send the one that I have but it looks like you are in France. I would try to port but it is beyond my skill set. Hardware seems solid on the review sample I have. Do you have the ability to reverse engineer. Looks like 2 chips are working together to make this work?

**Comment by 1technophile** [comment]
if it is based on esp8266 like the other sonoff it shouldn't be a problem.
I sent you an email.

**Comment by prahjister** [comment]
I never got the email. prahjister0

**Comment by prahjister** [comment]
Did they ship it and you receive it?

**Comment by 1technophile** [comment]
Not received it yet

**Comment by 1technophile** [comment]
Received  !

**Comment by prahjister** [comment]
Awesome. Maybe you can improve latency over other firmware that I'm using.
Also still getting duplicates.

**Comment by prahjister** [comment]
How goes it?

**Comment by 1technophile** [comment]
I didn't put my hands on it still

**Comment by 1technophile** [comment]
Begining to look at sonoff rf,
there is already some interesting work about it especialy:
http://tinkerman.cat/hacking-sonoff-rf-bridge-433/

At this time I'm able to receive RF with a mixed code between tinkerman one and mine (mainly tinkerman ;-)).

**Comment by prahjister** [comment]
Great. I'm using https://github.com/arendst/Sonoff-Tasmota

Latency and still getting duplicates. I think the way he is stopping duplicates is fooled when it missintepretes one of the duplicate transmission. I haven't looked into it much

**Comment by 1technophile** [comment]
You should take a look at @xoseperez code he is well removing the duplicates code (key RF_RECEIVE_DELAY)
http://tinkerman.cat/hacking-sonoff-rf-bridge-433/

**Comment by 1technophile** [comment]
done based on Xose Pérez work ESPURNA

**Comment by 1technophile** [comment]
Sending RF
`sudo mosquitto_pub -t home/commands/MQTTtoSRFB -m 1314884`

Receiving RF
```
home/433toMQTT 34009
home/SRFBtoMQTT/Raw 2A80015E042E0084D9
home/SRFBtoMQTT 34009
home/SRFBtoMQTT/Tsyn 10880
home/SRFBtoMQTT/Thigh 350
home/SRFBtoMQTT/Tlow 1070
```

**Comment by 1technophile** [comment]
@prahjister Hello, finally did you get it working with OpenMQTTGateway?

**Comment by MACscr** [comment]
I actually have espurna installed, but i dont think it can work as a receiver that way. Seems like it couldnt do both receiver and send. Only send after its learned. Im looking for something that can do both. At least receive since my broadlink can already do the sending part. I need the receive so that I can actually use RF remotes with it. Also, the RF Bridge is esp8265, not 66 afaik.

**Comment by 1technophile** [comment]
OpenMQTTGateway will do the job you are requesting on the platform you want (sonoff rf bridge, ESP8266, arduino, ESP32)

**Comment by xoseperez** [comment]
@MACscr You can send arbitrary codes using the 0xA5 action, no need to have them learned beforehand. Using ESPurna you can send the code to "<base_topic>/rfout/set" topic and the device will broadcast it.

**Comment by MACscr** [comment]
@xoseperez im not sure what you are talking about. i need the bridge to act as a RF/MQTT gateway. So it can receive commands from my RF remote and pass that to my MQTT gateway. As @1technophile and I have figured out, it doesnt reliable work that way. It works fine for learning a code and sending that code, but it cant consistently receive commands. seems the same remote (etekcity) buttons are inconsistent on which code they send.

**Comment by AKA-47** [comment]
i saw the same problem like @MACscr on some cheap self learning plugs. if i debug this with my gateway based on STX88 receiver it shows that the remote sends 5 different codes of which my plug only reacts on one of this if i resend it via my STX Gateway. Receiving or Sending the same code via RFbridge doesnt work. it only works on very static transmissions as i see so we maybe need to maintain an additional section in the compatibility list for this "additional microprocessor" based device
