### ISSUE TITLE
I only get servicedata from Xiaomi LYWSD03MMC

### ISSUE THREAD

**Issue by agoralive** [1technophile/OpenMQTTGateway#813]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
I only get servicedata

**To Reproduce**
I really don't know, bacause I see other people are able to get information

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.3, 0.8, development)
* Library version related to the problem you have (if you have troubles with RF provide the version of RCSwitch library)
* For IR and RF clarify if you tested with the basic examples given with these libraries

**Additional context**

This is the entire message I get from MQTT when trying to read data from a Xiaomi Temp/Hum sensor though BLE
{"id":"A4:C1:38:41:DB:7B","name":"LYWSD03MMC","rssi":-69,"distance":3.119501,"servicedata":"30585b05f97bdb4138c1a408"}

I am using the v0.9.5  and the esp32dev-ble-firmware on an ESP32-WROOM-32D

If I start up the app, it connects just fine to the temp sensor, but the ESP32 never makes a connection, how can I pair these?

**Comment by 1technophile** [comment]
You will get the data every 10minutes if not flashed with the tutorial below : 
https://community.openmqttgateway.com/t/xiaomi-lywsd03mmc-temperature-and-humidity-sensor-esp32-or-hm10/1237?u=1technophile

With this tutorial you will get the data every minutes with less battery consumption.

**Comment by agoralive** [comment]
Yeah, mine just goes like 20-30 minutes between publishing


THX

**Comment by 1technophile** [comment]
You can change it below for info : 
https://docs.openmqttgateway.com/use/ble.html#setting-the-number-of-scans-between-before-connect-attempt
