### ISSUE TITLE
Multiple IR emitters

### ISSUE THREAD

**Issue by rjchu** [1technophile/OpenMQTTGateway#823]
Not a feature in terms of the code but in the sense of the Gateway itself. Apologies if this isn't the right posting location.

Just wanted to confirm the best way to try and accomplish this - note I'm using ESP8266's (D1 Mini's) as IR Gateways.

As noted here, https://github.com/1technophile/OpenMQTTGateway/issues/104 it is recommended to add additional IR LED's in parallel but if going this route would I still just have the one current limiting resistor going to the LED "array" or should each IR LED have it's own resistor (still 220ohm I assume?) and all of them tied together to the 5v pin on the D1 Mini?

Thanks,

-joni-

**Comment by 1technophile** [comment]
This is well explained below:
https://electronics.stackexchange.com/questions/22291/why-exactly-cant-a-single-resistor-be-used-for-many-parallel-leds
