### ISSUE TITLE
Home Assistant shows binary.sensor as disconnected

### ISSUE THREAD

**Issue by jlaitinen81** [1technophile/OpenMQTTGateway#824]
I'm experiencing issues with my Open MQTT Gateway on an ESP32 Wroom with firmware 0.9.5.

The exposed binary.sensor shows as disconnected in Home Assistant since last night and even if I power cycled the ESP, the status does not change. However, I can see mqtt messages coming nicely through in my Mosquitto MQTT broker, and the ESP also looks to be perfectly well connected to my Unifi network (static IP) and packets flow both ways.

How can I force an update on the binary sensor status? I have a node red automation alerting me constantly of a disconnected device.

**Comment by 1technophile** [comment]
If you take a look to the broker, does it publish regularly a SYStoMQTT message?
If yes does this one fit with your switch definition?

**Comment by jlaitinen81** [comment]
Yes it does:

{"uptime":37082,"version":"v0.9.5","freemem":174800,"rssi":-38,"SSID":"xxx","ip":"yyy.yyy.yyy.yyy","mac":"zz:zz:zz:zz:zz","wifiprt":0,"lowpowermode":0,"interval":55555,"scanbcnct":10,"modules":"BTHADiscovery"}

How do I compare this to a switch definition? In my HA I can see binary_sensor.openmqttgateway_esp32_ble_7 as disconnected.

**Comment by 1technophile** [comment]
So the gateway is publishing regularly.

The switch status is based on this message:
![image](https://user-images.githubusercontent.com/12672732/101190206-ae3b3780-361d-11eb-84d6-b694b2d84552.png)
LWT = online

So if you see this one online, all is fine on the gateway to broker side.

We should look to the binary sensor definition published for auto discovery below:
![image](https://user-images.githubusercontent.com/12672732/101190457-02461c00-361e-11eb-85d1-05502455ea8e.png)

And see if it fits with the online message (topic/payload)

**Comment by jlaitinen81** [comment]
Thanks! This is under homeassistant/binary_sensor:

![image](https://user-images.githubusercontent.com/67101282/101191135-f419ef00-3661-11eb-8d5d-7bc4d601dd91.png)

and this is the one under home:

![image](https://user-images.githubusercontent.com/67101282/101191256-1ad82580-3662-11eb-9e21-799fc13ecbe4.png)

**Comment by jlaitinen81** [comment]
I'm confused but on a higher level 😀. The above pasted info looks correct to me but the binary sensor is still disconnected. Where is the link from this data to the actual binary sensor in HA? My binary sensor is called binary_sensor.openmqttgateway_esp32_ble_7 and I can not find any reference to that.

**Comment by 1technophile** [comment]
In Home Assistant->Configuration->Devices
Click on the gateway
Click on MQTT info
![image](https://user-images.githubusercontent.com/12672732/101248916-b7420c80-36e2-11eb-86eb-2e2b8190b662.png)

You should be able to check the topic definition for the gateway and see if it fits with the broker inputs.
If not I advise you to delete the device, delete the topics with MQTT explorer and restart the gateway.
