### ISSUE TITLE
Configuration Webserver

### ISSUE THREAD

**Issue by Trickx** [1technophile/OpenMQTTGateway#83]
This is a feature request for a webserver to configure the device.
Currently the sources need to be touched for every individual device.
What about a webinterface to store the configuration into EEPROM?

- If WLAN settings are not properly read from EEPROM or invalid change into AP mode.
- Provide IP addresses to connected clients (DHCP) server.
- Announce webservie via mDNS (bonjour).
- Provide webinterface to configure MQTT and WiFi settings.
- Provide webinterface to configure services.

**Comment by cosmocracy** [comment]
Definitely a use case for integrating [WiFiManager](https://github.com/tzapu/WiFiManager)

**Comment by tobiasfaust** [comment]
Its possible to integrate WifiManager in ESP32 too?

**Comment by 1technophile** [comment]
In fact i'm waiting for the integration into wifimanager main repo : 
https://github.com/tzapu/WiFiManager/issues/241

**Comment by thundergreen** [comment]
Will we get a gui in the future?
