### ISSUE TITLE
Official combability for ESP32-WROOM-32 (Adafruit ESP32 Feather)

### ISSUE THREAD

**Issue by samip5** [1technophile/OpenMQTTGateway#836]
**Is your feature request related to a problem? Please describe.**
No, but I want it to be officially supported.

**Describe the solution you'd like**
The Feather to be added to the board listing.

**Describe alternatives you've considered**
N/A

**Comment by 1technophile** [comment]
Would you be interested in proposing it as a PR, you need to add the board definition to platformio.ini, you may take the [esp32dev-ble](https://github.com/1technophile/OpenMQTTGateway/blob/a83f725bada72eb0c5e055f526c5c1a9a4a47871/platformio.ini#L319) as an example

**Comment by samip5** [comment]
Yes, I think I could do that, but I still need to try to get the platformio IDE installed.

**Comment by 1technophile** [comment]
Could you test with the board the PR linked please?

**Comment by samip5** [comment]
> Could you test with the board the PR linked please?

Could you please eloborate as to what do you mean? Test it how?

**Comment by 1technophile** [comment]
Verify that after the upload to the board following the new env, it worse properly.
* No crash
* The led flash when receiving BLE signal

**Comment by samip5** [comment]
> * The led flash when receiving BLE signal

I have nothing to test that with?

**Comment by 1technophile** [comment]
There is a big chance that you have BLE devices around you that will be detected by the gateway.
Even if they are not sensors, the gateway detect smartphone or other bLE device
