### ISSUE TITLE
Can't disable HADiscovery at compile

### ISSUE THREAD

**Issue by ProfEngr** [1technophile/OpenMQTTGateway#864]
**Describe the bug**
HADiscovery is commented "//" in user_config.h but still gets compiled in by VS Code.

**Expected behavior**
HADiscovery should not be compiled into the bin.

**Screenshots**

![discovery2](https://user-images.githubusercontent.com/44645861/107217662-7b763c80-69dc-11eb-80a6-e075e471a3d5.png)
![discovery1](https://user-images.githubusercontent.com/44645861/107217663-7c0ed300-69dc-11eb-9c1d-a09e3035d7f3.png)

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.5)

**Comment by 1technophile** [comment]
Yes, the doc has been updated in the [development branch ](https://github.com/1technophile/OpenMQTTGateway/commit/2d377a1c3f8350bf423452fc2dcadea5f9fe9ed5) but not yet published.

Could you try to add:
`'-UZmqttDiscovery="HADiscovery"'`

To your environment or remove 

`  '-DZmqttDiscovery="HADiscovery"'`

from [platformio.ini](https://github.com/1technophile/OpenMQTTGateway/blob/14fedfdf53dd1e4d9b28ff186f8b64a280d62206/platformio.ini#L144)

**Comment by 1technophile** [comment]
Closing, for info HAdiscovery can be disable also at [runtime ](https://docs.openmqttgateway.com/use/gateway.html#auto-discovery)
