### ISSUE TITLE
Missing elements from SYStoMQTT

### ISSUE THREAD

**Issue by csiki2** [1technophile/OpenMQTTGateway#866]
**Describe the bug**
SYStoMQTT might have missing elements due to the small buffer.

**To Reproduce**
1) Probably ZgatewayBT with ZboardM5STACK (very strong guess, not tried)
2) I have added extra lines to ZgatewayBT part of stateMeasures():
<pre>
#  ifdef ZgatewayBT
#    ifdef ESP32
  SYSdata["lowpowermode"] = (int)lowpowermode;
  SYSdata["btqfull"] = btMaxQueueLengthReached;
  SYSdata["btqsum"] = btQueueLengthSum;
  SYSdata["btqsnd"] = btQueueLengthCount;
  SYSdata["btqavg"] = (btQueueLengthCount>0 ? btQueueLengthSum/(float) btQueueLengthCount : 0);
#    endif
  SYSdata["interval"] = BLEinterval;
  SYSdata["scanbcnct"] = BLEscanBeforeConnect;
</pre>
It began not to post the interval, scanbcnct etc.

**Expected behavior**
Working SYStoMQTT. :)

**Environment (please complete the following information):**
* OpenMQTTGateway version used: development
* simple esp32dev

**Additional context**
The cause of the issue is that JSON_MSG_BUFFER is relatively small (512 bytes default) for such a big message as the JsonObject is extra unefficient memorywise (you can add something like SYSdata["BufferLeft"] =(int) jsonBuffer.size() after some lines to check it at MQTT server...).
So, after nth element, SYSdata will do nothing with the input (good behavior, doesn't crash: see JsonObject::set_impl(TStringRef key, TValueRef value)).
Short solution is to have a separate size define for the system, like JSON_SYSMSG_BUFFER.
It could even take into account big usages like ZboardM5*.

**Comment by 1technophile** [comment]
Thanks for pointing this.
JSON_MSG_BUFFER has been increased to 768 for ESP
Arduino MEGA publishes fewer attributes in SYStoMQTT so should not be an issue for it to stay at 512.

We may also come up with a more accurate JSON Buffer allocation depending on the context.
