### ISSUE TITLE
antenna question

### ISSUE THREAD

**Issue by kiralikbeyin** [1technophile/OpenMQTTGateway#91]
Is it safe to share receiver and transmitter antenna like this :https://tr.aliexpress.com/item/433Mhz-6dbi-OMNI-antenna-SMA-male-19cm-rotatable-2/32506670386.html?spm=a2g10.10010108.1000016.1.3c0375a481gJk0&isOrigTitle=true

**Comment by 1technophile** [comment]
Nerver tested it, i can't say. If you find something by googling and testing i will be interested by some feedback.
Please better post your questions on the chat (see readme page).
