### ISSUE TITLE
Compilation error: 'CLEARGRASSCGH1Discovery' was not declared in this scope

### ISSUE THREAD

**Issue by combatistor** [1technophile/OpenMQTTGateway#920]
Hi everyone, I found a bug, hopefully I could fix it but I post it for anyone having the same issue as me.

**Describe the bug**
When I compile OMG v0.9.6 using the release sources on the arduino IDE, with Bluetooth, I get the following error:
`'CLEARGRASSCGH1Discovery' was not declared in this scope`

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.6 release from github)

**Additional context**
Using Wemos D1 mini board

**How to solve the problem:**
the definition of "CLEARGRASSCGH1Discovery" function is missing, simply add this
`void CLEARGRASSCGH1Discovery(char* mac, char* sensorModel) {} `
on line 523 of the ZgatewayBT.ino file

Thank you

**Comment by 1technophile** [comment]
Thanks for pointing this !
