### ISSUE TITLE
Add PJON compatibility

### ISSUE THREAD

**Issue by gioblu** [1technophile/OpenMQTTGateway#923]
PJON could enable [single wire communication](https://github.com/gioblu/PJON/tree/master/src/strategies/SoftwareBitBang) for up to 255 devices over up to 2000m, as well as a very cheap [laser or optic-fibre link](https://github.com/gioblu/PJON/tree/master/src/strategies/AnalogSampling). PJON is a network protocol with a wide data-link support, and there is no alternative which implement a single wire data link with comparable performance and range. It would be also the first protocol supported that was developed by the marker's community for the maker's community :) if you need more info check out www.pjon.org

I noticed @1technophile starred PJON and so digging in his account I found this beautiful project. 
Keep up the good work and compliments for what you have built.

**Comment by 1technophile** [comment]
Hi,

Pjon is very interesting, thank you for the public contribution ! 

Outside of the wire capabilities how do you think we could use it in OMG  ?

**Comment by gioblu** [comment]
@1technophile the router classes: https://github.com/gioblu/PJON/blob/master/documentation/routing.md may be interesting for you being rather simple and portable.
