### ISSUE TITLE
Link to ESP32 bootloader 404 on "upload binary" page

### ISSUE THREAD

**Issue by witnessmenow** [1technophile/OpenMQTTGateway#928]
Webpage: https://docs.openmqttgateway.com/upload/binaries.html#esp32

Link is currently this: https://github.com/espressif/arduino-esp32/raw/master/tools/sdk/bin/bootloader_dio_80m.bin

It should now be this (note "esp32" folder after "sdk"): https://github.com/espressif/arduino-esp32/raw/master/tools/sdk/esp32/bin/bootloader_dio_80m.bin

**Comment by 1technophile** [comment]
Thanks for pointing this, please note that you can submit a pull request by clicking on the [edit this page](https://github.com/1technophile/OpenMQTTGateway/edit/development/docs/upload/binaries.md) of the doc if you are interested

**Comment by witnessmenow** [comment]
Sure, opened one there.
