### ISSUE TITLE
Reset bluetooth white/black list - wiki/documentation update

### ISSUE THREAD

**Issue by tomcat-xx** [1technophile/OpenMQTTGateway#935]
Bit off topic but related: Thanks for v0.9.6! I set a white list because I had huge problem with stable operation. Even with white list I had to restart the gateways sometimes after only 1-2 days. With v0.9.6 all are running since 5 weeks now.

Back to question in header: How can I reset a (persistent) white list? I think I did before by setting an empty list. But could not get it working now.

**Comment by 1technophile** [comment]
You will have to remove the white list message from the MQTT broker if it was send as "retained" (Mqtt explorer advised to do this)
And restart the gateway

**Comment by tomcat-xx** [comment]
Thanks!
