### ISSUE TITLE
Sonoff RFB wiki page image link broken

### ISSUE THREAD

**Issue by gh0stter** [1technophile/OpenMQTTGateway#987]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
images are broken

**To Reproduce**
visit: https://github.com/1technophile/OpenMQTTGateway/wiki/Sonoff-RFB#prerequisites

**Expected behavior**
images should show

**Screenshots**
![image](https://user-images.githubusercontent.com/604535/121829115-c353fa00-cd15-11eb-83a9-a063017412ef.png)

**Comment by 1technophile** [comment]
I'm not maintaining the wiki anymore, the information related to the gateway are into the [documentation](https://docs.openmqttgateway.com), regarding how to flash the bridge you can follow this [tutorial ](https://tinkerman.cat/post/hacking-sonoff-rf-bridge-433) to flash it
