### ISSUE TITLE
WifiManager password is lost if we trigger a configuration reset of the gateway

### ISSUE THREAD

**Issue by 1technophile** [1technophile/OpenMQTTGateway#994]
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
The WifiManager_password  is not required after a gateway reset by long press

**To Reproduce**
- Switch on the gateway on an ESP32
- Connect to the Wifi AP with a smartphone
- Enter WifiManager_password
- Configure it through the WM web portal
- Save the configuration
- The gateway connects to the wifi and mqtt broker
- Do a long press on TRIGGER_GPIO
- Remove the wifi AP from your smartphone
- Connect to the Wifi AP with a smartphone
- WifiManager_password is not needed anymore, it should be requested

**Expected behavior**
The WifiManager_password  should still be requested

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.6)

**Comment by h2zero** [comment]
If I'm interpreting the steps correctly, the password would stored in the phones cache. So unless it changes on resetting I think this is normal behavior.

**Comment by 1technophile** [comment]
I was thinking about this at the beginning, but unfortunately, if I remove the network/erase it from my smartphone wifi list, I can still reconnect to it without the wifi password.
A good indicator could be the lock symbol close to the wifi symbol. My home wifi has it always, and the wifi of OMG disappears after an init by a long button press.
